#!/bin/sh

##########################################################
###### Zabbix agent daemon init script
##########################################################

case $1 in

start)
	/home/zabbix/zabbix_agentd -c /home/zabbix/zabbix_agentd.conf;;

stop)
	kill -TERM `cat /home/zabbix/run/zabbix_agentd.pid` ;;

restart)
	$0 stop
	sleep 5
	$0 start
	;;

*)
	echo "Usage: $0 start|stop|restart"
	exit 1
esac
