ALTER TABLE operations ALTER COLUMN operationid SET WITH DEFAULT NULL;
REORG TABLE operations;
ALTER TABLE operations ALTER COLUMN actionid SET WITH DEFAULT NULL;
REORG TABLE operations;
ALTER TABLE operations ADD mediatypeid BIGINT NULL;
REORG TABLE operations;
DELETE FROM operations WHERE NOT actionid IN (SELECT actionid FROM actions);
ALTER TABLE operations ADD CONSTRAINT c_operations_1 FOREIGN KEY (actionid) REFERENCES actions (actionid) ON DELETE CASCADE;
REORG TABLE operations;
ALTER TABLE operations ADD CONSTRAINT c_operations_2 FOREIGN KEY (mediatypeid) REFERENCES media_type (mediatypeid) ON DELETE CASCADE;
REORG TABLE operations;
UPDATE operations SET mediatypeid=(SELECT mediatypeid FROM opmediatypes WHERE operationid = operations.operationid);
DROP TABLE opmediatypes;
