#!/bin/bash

COPYR=$(cat << 'EOF'
/*
** Zabbix
** Copyright (C) 2001-2019 Zabbix SIA
**
** This program is free software; you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation; either version 2 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program; if not, write to the Free Software
** Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
**/
EOF
)
trim(){
	[[ "$1" =~ [^[:space:]](.*[^[:space:]])? ]]
	printf "%s" "$BASH_REMATCH"
}

echo "" > /tmp/routesdef

# for view in $(cat $1 | ag CCont | cut -d '|' -f 6 | ag admin);do
for action in $(cat $1 | ag admin | cut -d '|' -f 5);do
	action=$(trim $action)
	f=app/views/administration.$action.php
	fj=app/views/administration.$action.js.php
	if [ -e $f ]; then
		echo $f exists. Skipping
		continue
	fi
	echo "| $action"
	tee $f <<EOF >/dev/null
<?php
$COPYR


\$this->includeJSfile('$fj');

\$widget = (new CWidget())
	->setTitle(_('$action :data-demo: '.\$data['demo']))
	->setControls((new CTag('nav', true,
		(new CForm())
			->cleanItems()
			->addItem((new CList())
				->addItem(makeAdministrationGeneralMenu((new CUrl('zabbix.php'))
					->setArgument('action', '$action')
					->getUrl()
				))
			)
		))
			->setAttribute('aria-label', _('Content controls'))
	);

\$form = (new CForm())
	->setId('autoreg-form')
	->setName('autoreg-form')
	->setAction((new CUrl('zabbix.php'))
		->setArgument('action', '$action')
		->getUrl()
	)
	->setAttribute('aria-labeledby', ZBX_STYLE_PAGE_TITLE);

\$widget
	->addItem(\$form)
	->show();
EOF


	if [ -e $fj ]; then
		echo $fj exists. Skipping
		continue
	fi
	echo "| $action | js"
	tee $fj <<EOF >/dev/null
<?php
$COPYR
?>

<script type="text/javascript">
	jQuery(function() {
		console.log('dom ready: $action');
	});
</script>
EOF

done

for cc in $(cat $1 | ag CCont | cut -d '|' -f 7);do
	cc=$(trim $cc)
	f=app/controllers/$cc.php
	if [ -e $f ]; then
		echo $f. Skipping
		continue
	fi

	action=$(cat $1 | ag $cc | cut -d '|' -f 5)
	action=$(trim $action)
	echo "'$action' => ['$cc', 'layout.htmlpage', 'administration.$action']," >> /tmp/routesdef

	echo "| $cc"
	tee $f <<EOF >/dev/null
<?php
$COPYR


class $cc extends CController {

	protected function init() {
		\$this->disableSIDValidation();
	}

	protected function checkInput() {
		\$fields = [
			'demo' => ''
		];

		\$ret = \$this->validateInput(\$fields);

		if (!\$ret) {
			\$this->setResponse(new CControllerResponseFatal());
		}

		return \$ret;
	}

	protected function checkPermissions() {
		return (\$this->getUserType() == USER_TYPE_SUPER_ADMIN);
	}

	protected function doAction() {
		\$data = [
			'demo' => __FILE__
		];

		\$response = new CControllerResponseData(\$data);
		\$response->setTitle(_('$cc'));
		\$this->setResponse(\$response);
	}
}
EOF

done

cat /tmp/routesdef

