<?php declare(strict_types=1);
/*
** Zabbix
** Copyright (C) 2001-2022 Zabbix SIA
**
** This program is free software; you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation; either version 2 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program; if not, write to the Free Software
** Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
**/


class C44ImportConverterTest extends CImportConverterTest {

	public function dataProviderConvert() {
		return [
			[
				[],
				[]
			],
			[
				[
					'templates' => [
						[
							'items' => [
								[
									'type' => 'SNMPV1',
									'snmp_community' => 'public',
									'snmp_oid' => 'test',
									'port' => '',
									'snmpv3_contextname' => '',
									'snmpv3_securityname' => 'test',
									'snmpv3_securitylevel' => '0',
									'snmpv3_authprotocol' => '0',
									'snmpv3_authpassphrase' => '',
									'snmpv3_privprotocol' => '0',
									'snmpv3_privpassphrase' => ''
								]
							],
							'discovery_rules' => [
								[
									'type' => 'SNMPV2',
									'snmp_community' => 'public',
									'snmp_oid' => 'test',
									'port' => '',
									'snmpv3_contextname' => '',
									'snmpv3_securityname' => 'test',
									'snmpv3_securitylevel' => '0',
									'snmpv3_authprotocol' => '0',
									'snmpv3_authpassphrase' => '',
									'snmpv3_privprotocol' => '0',
									'snmpv3_privpassphrase' => '',
									'item_prototypes' => [
										[
											'type' => 'SNMPV3',
											'snmp_community' => '',
											'snmp_oid' => 'test',
											'port' => '162',
											'snmpv3_contextname' => 'test',
											'snmpv3_securityname' => 'test',
											'snmpv3_securitylevel' => '0',
											'snmpv3_authprotocol' => '1',
											'snmpv3_authpassphrase' => 'test',
											'snmpv3_privprotocol' => '0',
											'snmpv3_privpassphrase' => 'test'
										]
									]
								]
							]
						]
					]
				],
				[
					'templates' => [
						[
							'items' => [
								[
									'type' => 'SNMP_AGENT',
									'snmp_oid' => 'test'
								]
							],
							'discovery_rules' => [
								[
									'type' => 'SNMP_AGENT',
									'snmp_oid' => 'test',
									'item_prototypes' => [
										[
											'type' => 'SNMP_AGENT',
											'snmp_oid' => 'test'
										]
									]
								]
							]
						]
					]
				]
			],
			[
				[
					'hosts' => [
						[
							'interfaces' => [
								[
									'interface_ref' => 'if1',
									'ip' => '127.0.0.1',
									'type' => 'SNMP',
									'dns' => '',
									'port' => '161',
									'useip' => 'YES',
									'default' => 'YES',
									'bulk' => 'NO'
								]
							],
							'items' => [
								[
									'interface_ref' => 'if1',
									'key' => 'test1',
									'type' => 'SNMPV3',
									'snmp_community' => 'test',
									'snmp_oid' => 'test',
									'port' => '162',
									'snmpv3_contextname' => 'test',
									'snmpv3_securityname' => 'test',
									'snmpv3_securitylevel' => 'AUTHPRIV',
									'snmpv3_authprotocol' => 'SHA',
									'snmpv3_authpassphrase' => 'test',
									'snmpv3_privprotocol' => 'AES',
									'snmpv3_privpassphrase' => 'test'
								]
							],
							'discovery_rules' => [
								[
									'interface_ref' => 'if1',
									'key' => 'test2',
									'type' => 'SNMPV2',
									'snmp_community' => 'test',
									'snmp_oid' => 'test',
									'port' => '163',
									'snmpv3_contextname' => 'test',
									'snmpv3_securityname' => 'test',
									'snmpv3_securitylevel' => 'AUTHPRIV',
									'snmpv3_authprotocol' => 'SHA',
									'snmpv3_authpassphrase' => 'test',
									'snmpv3_privprotocol' => 'AES',
									'snmpv3_privpassphrase' => 'test',
									'item_prototypes' => [
										[
											'interface_ref' => 'if1',
											'key' => 'test3',
											'type' => 'SNMPV1',
											'snmp_community' => 'test',
											'snmp_oid' => 'test',
											'port' => '',
											'snmpv3_contextname' => 'test',
											'snmpv3_securityname' => 'test',
											'snmpv3_securitylevel' => 'AUTHPRIV',
											'snmpv3_authprotocol' => 'SHA',
											'snmpv3_authpassphrase' => 'test',
											'snmpv3_privprotocol' => 'AES',
											'snmpv3_privpassphrase' => 'test'
										]
									]
								]
							]
						]
					]
				],
				[
					'hosts' => [
						[
							'interfaces' => [
								1 => [
									'interface_ref' => 'if2',
									'ip' => '127.0.0.1',
									'type' => 'SNMP',
									'dns' => '',
									'port' => '161',
									'useip' => 'YES',
									'default' => 'YES',
									'details' => [
										'bulk' => 'NO',
										'version' => 'SNMPV3',
										'contextname' => 'test',
										'securityname' => 'test',
										'securitylevel' => 'AUTHPRIV',
										'authprotocol' => 'SHA',
										'authpassphrase' => 'test',
										'privprotocol' => 'AES',
										'privpassphrase' => 'test'
									]
								],
								2 => [
									'interface_ref' => 'if3',
									'ip' => '127.0.0.1',
									'type' => 'SNMP',
									'dns' => '',
									'port' => '162',
									'useip' => 'YES',
									'default' => 'NO',
									'details' => [
										'bulk' => 'NO',
										'version' => 'SNMPV3',
										'contextname' => 'test',
										'securityname' => 'test',
										'securitylevel' => 'AUTHPRIV',
										'authprotocol' => 'SHA',
										'authpassphrase' => 'test',
										'privprotocol' => 'AES',
										'privpassphrase' => 'test'
									]
								],
								3 => [
									'interface_ref' => 'if4',
									'ip' => '127.0.0.1',
									'type' => 'SNMP',
									'dns' => '',
									'port' => '163',
									'useip' => 'YES',
									'default' => 'NO',
									'details' => [
										'bulk' => 'NO',
										'version' => 'SNMPV2',
										'community' => 'test'
									]
								],
								4 => [
									'interface_ref' => 'if5',
									'ip' => '127.0.0.1',
									'type' => 'SNMP',
									'dns' => '',
									'port' => '161',
									'useip' => 'YES',
									'default' => 'NO',
									'details' => [
										'bulk' => 'NO',
										'version' => 'SNMPV1',
										'community' => 'test'
									]
								]
							],
							'items' => [
								[
									'interface_ref' => 'if3',
									'key' => 'test1',
									'type' => 'SNMP_AGENT',
									'snmp_oid' => 'test'
								]
							],
							'discovery_rules' => [
								[
									'interface_ref' => 'if4',
									'key' => 'test2',
									'type' => 'SNMP_AGENT',
									'snmp_oid' => 'test',
									'item_prototypes' => [
										[
											'interface_ref' => 'if5',
											'key' => 'test3',
											'type' => 'SNMP_AGENT',
											'snmp_oid' => 'test'
										]
									]
								]
							]
						]
					]
				]
			],
			[
				[
					'hosts' => [
						[
							'interfaces' => [
								[
									'interface_ref' => 'if1',
								],
								[
									'interface_ref' => 'if2',
									'type' => 'SNMP',
									'port' => '161'
								]
							],
							'items' => [
								[
									'interface_ref' => 'if2',
									'key' => 'snmptrap.fallback',
									'type' => 'SNMP_TRAP',
									'name' => 'SNMp trap',
									'delay' => 0
								],
								[
									'interface_ref' => 'if2',
									'key' => 'snmptrap[asd]',
									'type' => 'SNMP_TRAP',
									'name' => 'Snmp trap item',
									'delay' => 0
								]
							]
						]
					]
				],
				[
					'hosts' => [
						[
							'interfaces' => [
								0 => [
									'interface_ref' => 'if1',
								],
								2 => [
									'interface_ref' => 'if2',
									'type' => 'SNMP',
									'port' => '161',
									'details' => [
										'bulk' => 'YES',
										'version' => 'SNMPV1',
										'community' => 'public'
									],
									'default' => 'YES',
									'useip' => 'YES',
									'ip' => '127.0.0.1',
									'dns' => ''
								]
							],
							'items' => [
								[
									'interface_ref' => 'if2',
									'key' => 'snmptrap.fallback',
									'type' => 'SNMP_TRAP',
									'name' => 'SNMp trap',
									'delay' => 0
								],
								[
									'interface_ref' => 'if2',
									'key' => 'snmptrap[asd]',
									'type' => 'SNMP_TRAP',
									'name' => 'Snmp trap item',
									'delay' => 0
								]
							]
						]
					]
				]
			],
			[
				[

						"hosts"   => [
							"host"   => [
								"host"   => "HOST",
								"name"   => "HOST",
								"description"   => [],
								"proxy"   => [],
								"status"   => "0",
								"ipmi_authtype"   => "-1",
								"ipmi_privilege"   => "2",
								"ipmi_username"   => [],
								"ipmi_password"   => [],
								"tls_connect"   => "1",
								"tls_accept"   => "1",
								"tls_issuer"   => [],
								"tls_subject"   => [],
								"tls_psk_identity"   => [],
								"tls_psk"   => [],
								"templates"   => [],
								"groups"   => [
									"group"   => [
										"name"   => "Zabbix servers"
									]
								],
								"interfaces"   => [
									[
										"default"   => "1",
										"type"   => "1",
										"useip"   => "1",
										"ip"   => "127.0.0.1",
										"dns"   => [],
										"port"   => "10050",
										"bulk"   => "1",
										"interface_ref"   => "if1"
									],
									[
										"default"   => "1",
										"type"   => "2",
										"useip"   => "1",
										"ip"   => "127.0.0.1",
										"dns"   => "SNMP",
										"port"   => "161",
										"bulk"   => "1",
										"interface_ref"   => "if2"
									]
								],
								"applications"   => [],
								"items"   => [
									[
										"name"   => "snmp trap",
										"type"   => "17",
										"snmp_community"   => [],
										"snmp_oid"   => [],
										"key"   => "snmptrap.fallback",
										"delay"   => "0",
										"history"   => "90d",
										"trends"   => "365d",
										"status"   => "0",
										"value_type"   => "3",
										"allowed_hosts"   => [],
										"units"   => [],
										"snmpv3_contextname"   => [],
										"snmpv3_securityname"   => [],
										"snmpv3_securitylevel"   => "0",
										"snmpv3_authprotocol"   => "0",
										"snmpv3_authpassphrase"   => [],
										"snmpv3_privprotocol"   => "0",
										"snmpv3_privpassphrase"   => [],
										"params"   => [],
										"ipmi_sensor"   => [],
										"authtype"   => "0",
										"username"   => [],
										"password"   => [],
										"publickey"   => [],
										"privatekey"   => [],
										"port"   => [],
										"description"   => [],
										"inventory_link"   => "0",
										"applications"   => [],
										"valuemap"   => [],
										"logtimefmt"   => [],
										"preprocessing"   => [],
										"jmx_endpoint"   => [],
										"timeout"   => "3s",
										"url"   => [],
										"query_fields"   => [],
										"posts"   => [],
										"status_codes"   => "200",
										"follow_redirects"   => "1",
										"post_type"   => "0",
										"http_proxy"   => [],
										"headers"   => [],
										"retrieve_mode"   => "0",
										"request_method"   => "0",
										"output_format"   => "0",
										"allow_traps"   => "0",
										"ssl_cert_file"   => [],
										"ssl_key_file"   => [],
										"ssl_key_password"   => [],
										"verify_peer"   => "0",
										"verify_host"   => "0",
										"master_item"   => [],
										"interface_ref"   => "if2"
									],
									[
										"name"   => "V1  public same port",
										"type"   => "1",
										"snmp_community"   => "public",
										"snmp_oid"   => "123",
										"key"   => "test",
										"delay"   => "30s",
										"history"   => "90d",
										"trends"   => "365d",
										"status"   => "0",
										"value_type"   => "3",
										"allowed_hosts"   => [],
										"units"   => [],
										"snmpv3_contextname"   => [],
										"snmpv3_securityname"   => [],
										"snmpv3_securitylevel"   => "0",
										"snmpv3_authprotocol"   => "0",
										"snmpv3_authpassphrase"   => [],
										"snmpv3_privprotocol"   => "0",
										"snmpv3_privpassphrase"   => [],
										"params"   => [],
										"ipmi_sensor"   => [],
										"authtype"   => "0",
										"username"   => [],
										"password"   => [],
										"publickey"   => [],
										"privatekey"   => [],
										"port"   => "161",
										"description"   => [],
										"inventory_link"   => "0",
										"applications"   => [],
										"valuemap"   => [],
										"logtimefmt"   => [],
										"preprocessing"   => [],
										"jmx_endpoint"   => [],
										"timeout"   => "3s",
										"url"   => [],
										"query_fields"   => [],
										"posts"   => [],
										"status_codes"   => "200",
										"follow_redirects"   => "1",
										"post_type"   => "0",
										"http_proxy"   => [],
										"headers"   => [],
										"retrieve_mode"   => "0",
										"request_method"   => "0",
										"output_format"   => "0",
										"allow_traps"   => "0",
										"ssl_cert_file"   => [],
										"ssl_key_file"   => [],
										"ssl_key_password"   => [],
										"verify_peer"   => "0",
										"verify_host"   => "0",
										"master_item"   => [],
										"interface_ref"   => "if2"
									],
									[
										"name"   => "V1  public empty port",
										"type"   => "1",
										"snmp_community"   => "public",
										"snmp_oid"   => "123",
										"key"   => "test1",
										"delay"   => "30s",
										"history"   => "90d",
										"trends"   => "365d",
										"status"   => "0",
										"value_type"   => "3",
										"allowed_hosts"   => [],
										"units"   => [],
										"snmpv3_contextname"   => [],
										"snmpv3_securityname"   => [],
										"snmpv3_securitylevel"   => "0",
										"snmpv3_authprotocol"   => "0",
										"snmpv3_authpassphrase"   => [],
										"snmpv3_privprotocol"   => "0",
										"snmpv3_privpassphrase"   => [],
										"params"   => [],
										"ipmi_sensor"   => [],
										"authtype"   => "0",
										"username"   => [],
										"password"   => [],
										"publickey"   => [],
										"privatekey"   => [],
										"port"   => [],
										"description"   => [],
										"inventory_link"   => "0",
										"applications"   => [],
										"valuemap"   => [],
										"logtimefmt"   => [],
										"preprocessing"   => [],
										"jmx_endpoint"   => [],
										"timeout"   => "3s",
										"url"   => [],
										"query_fields"   => [],
										"posts"   => [],
										"status_codes"   => "200",
										"follow_redirects"   => "1",
										"post_type"   => "0",
										"http_proxy"   => [],
										"headers"   => [],
										"retrieve_mode"   => "0",
										"request_method"   => "0",
										"output_format"   => "0",
										"allow_traps"   => "0",
										"ssl_cert_file"   => [],
										"ssl_key_file"   => [],
										"ssl_key_password"   => [],
										"verify_peer"   => "0",
										"verify_host"   => "0",
										"master_item"   => [],
										"interface_ref"   => "if2"
									],
									[
										"name"   => "V1  public 99 port",
										"type"   => "1",
										"snmp_community"   => "public",
										"snmp_oid"   => "123",
										"key"   => "test2",
										"delay"   => "30s",
										"history"   => "90d",
										"trends"   => "365d",
										"status"   => "0",
										"value_type"   => "3",
										"allowed_hosts"   => [],
										"units"   => [],
										"snmpv3_contextname"   => [],
										"snmpv3_securityname"   => [],
										"snmpv3_securitylevel"   => "0",
										"snmpv3_authprotocol"   => "0",
										"snmpv3_authpassphrase"   => [],
										"snmpv3_privprotocol"   => "0",
										"snmpv3_privpassphrase"   => [],
										"params"   => [],
										"ipmi_sensor"   => [],
										"authtype"   => "0",
										"username"   => [],
										"password"   => [],
										"publickey"   => [],
										"privatekey"   => [],
										"port"   => "99",
										"description"   => [],
										"inventory_link"   => "0",
										"applications"   => [],
										"valuemap"   => [],
										"logtimefmt"   => [],
										"preprocessing"   => [],
										"jmx_endpoint"   => [],
										"timeout"   => "3s",
										"url"   => [],
										"query_fields"   => [],
										"posts"   => [],
										"status_codes"   => "200",
										"follow_redirects"   => "1",
										"post_type"   => "0",
										"http_proxy"   => [],
										"headers"   => [],
										"retrieve_mode"   => "0",
										"request_method"   => "0",
										"output_format"   => "0",
										"allow_traps"   => "0",
										"ssl_cert_file"   => [],
										"ssl_key_file"   => [],
										"ssl_key_password"   => [],
										"verify_peer"   => "0",
										"verify_host"   => "0",
										"master_item"   => [],
										"interface_ref"   => "if2"
									],
									[
										"name"   => "V2 same port public",
										"type"   => "4",
										"snmp_community"   => "public",
										"snmp_oid"   => "123",
										"key"   => "test3",
										"delay"   => "30s",
										"history"   => "90d",
										"trends"   => "365d",
										"status"   => "0",
										"value_type"   => "3",
										"allowed_hosts"   => [],
										"units"   => [],
										"snmpv3_contextname"   => [],
										"snmpv3_securityname"   => [],
										"snmpv3_securitylevel"   => "0",
										"snmpv3_authprotocol"   => "0",
										"snmpv3_authpassphrase"   => [],
										"snmpv3_privprotocol"   => "0",
										"snmpv3_privpassphrase"   => [],
										"params"   => [],
										"ipmi_sensor"   => [],
										"authtype"   => "0",
										"username"   => [],
										"password"   => [],
										"publickey"   => [],
										"privatekey"   => [],
										"port"   => "161",
										"description"   => [],
										"inventory_link"   => "0",
										"applications"   => [],
										"valuemap"   => [],
										"logtimefmt"   => [],
										"preprocessing"   => [],
										"jmx_endpoint"   => [],
										"timeout"   => "3s",
										"url"   => [],
										"query_fields"   => [],
										"posts"   => [],
										"status_codes"   => "200",
										"follow_redirects"   => "1",
										"post_type"   => "0",
										"http_proxy"   => [],
										"headers"   => [],
										"retrieve_mode"   => "0",
										"request_method"   => "0",
										"output_format"   => "0",
										"allow_traps"   => "0",
										"ssl_cert_file"   => [],
										"ssl_key_file"   => [],
										"ssl_key_password"   => [],
										"verify_peer"   => "0",
										"verify_host"   => "0",
										"master_item"   => [],
										"interface_ref"   => "if2"
									],
									[
										"name"   => "V2 empty port public",
										"type"   => "4",
										"snmp_community"   => "public",
										"snmp_oid"   => "123",
										"key"   => "test4",
										"delay"   => "30s",
										"history"   => "90d",
										"trends"   => "365d",
										"status"   => "0",
										"value_type"   => "3",
										"allowed_hosts"   => [],
										"units"   => [],
										"snmpv3_contextname"   => [],
										"snmpv3_securityname"   => [],
										"snmpv3_securitylevel"   => "0",
										"snmpv3_authprotocol"   => "0",
										"snmpv3_authpassphrase"   => [],
										"snmpv3_privprotocol"   => "0",
										"snmpv3_privpassphrase"   => [],
										"params"   => [],
										"ipmi_sensor"   => [],
										"authtype"   => "0",
										"username"   => [],
										"password"   => [],
										"publickey"   => [],
										"privatekey"   => [],
										"port"   => [],
										"description"   => [],
										"inventory_link"   => "0",
										"applications"   => [],
										"valuemap"   => [],
										"logtimefmt"   => [],
										"preprocessing"   => [],
										"jmx_endpoint"   => [],
										"timeout"   => "3s",
										"url"   => [],
										"query_fields"   => [],
										"posts"   => [],
										"status_codes"   => "200",
										"follow_redirects"   => "1",
										"post_type"   => "0",
										"http_proxy"   => [],
										"headers"   => [],
										"retrieve_mode"   => "0",
										"request_method"   => "0",
										"output_format"   => "0",
										"allow_traps"   => "0",
										"ssl_cert_file"   => [],
										"ssl_key_file"   => [],
										"ssl_key_password"   => [],
										"verify_peer"   => "0",
										"verify_host"   => "0",
										"master_item"   => [],
										"interface_ref"   => "if2"
									],
									[
										"name"   => "V2  port 99 public",
										"type"   => "4",
										"snmp_community"   => "public",
										"snmp_oid"   => "123",
										"key"   => "test5",
										"delay"   => "30s",
										"history"   => "90d",
										"trends"   => "365d",
										"status"   => "0",
										"value_type"   => "3",
										"allowed_hosts"   => [],
										"units"   => [],
										"snmpv3_contextname"   => [],
										"snmpv3_securityname"   => [],
										"snmpv3_securitylevel"   => "0",
										"snmpv3_authprotocol"   => "0",
										"snmpv3_authpassphrase"   => [],
										"snmpv3_privprotocol"   => "0",
										"snmpv3_privpassphrase"   => [],
										"params"   => [],
										"ipmi_sensor"   => [],
										"authtype"   => "0",
										"username"   => [],
										"password"   => [],
										"publickey"   => [],
										"privatekey"   => [],
										"port"   => "99",
										"description"   => [],
										"inventory_link"   => "0",
										"applications"   => [],
										"valuemap"   => [],
										"logtimefmt"   => [],
										"preprocessing"   => [],
										"jmx_endpoint"   => [],
										"timeout"   => "3s",
										"url"   => [],
										"query_fields"   => [],
										"posts"   => [],
										"status_codes"   => "200",
										"follow_redirects"   => "1",
										"post_type"   => "0",
										"http_proxy"   => [],
										"headers"   => [],
										"retrieve_mode"   => "0",
										"request_method"   => "0",
										"output_format"   => "0",
										"allow_traps"   => "0",
										"ssl_cert_file"   => [],
										"ssl_key_file"   => [],
										"ssl_key_password"   => [],
										"verify_peer"   => "0",
										"verify_host"   => "0",
										"master_item"   => [],
										"interface_ref"   => "if2"
									],
									[
										"name"   => "V3 same port public context security",
										"type"   => "6",
										"snmp_community"   => [],
										"snmp_oid"   => "123",
										"key"   => "test6",
										"delay"   => "30s",
										"history"   => "90d",
										"trends"   => "365d",
										"status"   => "0",
										"value_type"   => "3",
										"allowed_hosts"   => [],
										"units"   => [],
										"snmpv3_contextname"   => "context1",
										"snmpv3_securityname"   => "name1",
										"snmpv3_securitylevel"   => "0",
										"snmpv3_authprotocol"   => "0",
										"snmpv3_authpassphrase"   => [],
										"snmpv3_privprotocol"   => "0",
										"snmpv3_privpassphrase"   => [],
										"params"   => [],
										"ipmi_sensor"   => [],
										"authtype"   => "0",
										"username"   => [],
										"password"   => [],
										"publickey"   => [],
										"privatekey"   => [],
										"port"   => "161",
										"description"   => [],
										"inventory_link"   => "0",
										"applications"   => [],
										"valuemap"   => [],
										"logtimefmt"   => [],
										"preprocessing"   => [],
										"jmx_endpoint"   => [],
										"timeout"   => "3s",
										"url"   => [],
										"query_fields"   => [],
										"posts"   => [],
										"status_codes"   => "200",
										"follow_redirects"   => "1",
										"post_type"   => "0",
										"http_proxy"   => [],
										"headers"   => [],
										"retrieve_mode"   => "0",
										"request_method"   => "0",
										"output_format"   => "0",
										"allow_traps"   => "0",
										"ssl_cert_file"   => [],
										"ssl_key_file"   => [],
										"ssl_key_password"   => [],
										"verify_peer"   => "0",
										"verify_host"   => "0",
										"master_item"   => [],
										"interface_ref"   => "if2"
									],
									[
										"name"   => "V3 empty port public context2 security2",
										"type"   => "6",
										"snmp_community"   => [],
										"snmp_oid"   => "123",
										"key"   => "test7",
										"delay"   => "30s",
										"history"   => "90d",
										"trends"   => "365d",
										"status"   => "0",
										"value_type"   => "3",
										"allowed_hosts"   => [],
										"units"   => [],
										"snmpv3_contextname"   => "context2",
										"snmpv3_securityname"   => "name2",
										"snmpv3_securitylevel"   => "0",
										"snmpv3_authprotocol"   => "0",
										"snmpv3_authpassphrase"   => [],
										"snmpv3_privprotocol"   => "0",
										"snmpv3_privpassphrase"   => [],
										"params"   => [],
										"ipmi_sensor"   => [],
										"authtype"   => "0",
										"username"   => [],
										"password"   => [],
										"publickey"   => [],
										"privatekey"   => [],
										"port"   => [],
										"description"   => [],
										"inventory_link"   => "0",
										"applications"   => [],
										"valuemap"   => [],
										"logtimefmt"   => [],
										"preprocessing"   => [],
										"jmx_endpoint"   => [],
										"timeout"   => "3s",
										"url"   => [],
										"query_fields"   => [],
										"posts"   => [],
										"status_codes"   => "200",
										"follow_redirects"   => "1",
										"post_type"   => "0",
										"http_proxy"   => [],
										"headers"   => [],
										"retrieve_mode"   => "0",
										"request_method"   => "0",
										"output_format"   => "0",
										"allow_traps"   => "0",
										"ssl_cert_file"   => [],
										"ssl_key_file"   => [],
										"ssl_key_password"   => [],
										"verify_peer"   => "0",
										"verify_host"   => "0",
										"master_item"   => [],
										"interface_ref"   => "if2"
									],
									[
										"name"   => "V3  port  88 public context3 security3",
										"type"   => "6",
										"snmp_community"   => [],
										"snmp_oid"   => "88",
										"key"   => "test8",
										"delay"   => "30s",
										"history"   => "90d",
										"trends"   => "365d",
										"status"   => "0",
										"value_type"   => "3",
										"allowed_hosts"   => [],
										"units"   => [],
										"snmpv3_contextname"   => "context3",
										"snmpv3_securityname"   => "name3",
										"snmpv3_securitylevel"   => "1",
										"snmpv3_authprotocol"   => "0",
										"snmpv3_authpassphrase"   => "33",
										"snmpv3_privprotocol"   => "0",
										"snmpv3_privpassphrase"   => [],
										"params"   => [],
										"ipmi_sensor"   => [],
										"authtype"   => "0",
										"username"   => [],
										"password"   => [],
										"publickey"   => [],
										"privatekey"   => [],
										"port"   => "88",
										"description"   => [],
										"inventory_link"   => "0",
										"applications"   => [],
										"valuemap"   => [],
										"logtimefmt"   => [],
										"preprocessing"   => [],
										"jmx_endpoint"   => [],
										"timeout"   => "3s",
										"url"   => [],
										"query_fields"   => [],
										"posts"   => [],
										"status_codes"   => "200",
										"follow_redirects"   => "1",
										"post_type"   => "0",
										"http_proxy"   => [],
										"headers"   => [],
										"retrieve_mode"   => "0",
										"request_method"   => "0",
										"output_format"   => "0",
										"allow_traps"   => "0",
										"ssl_cert_file"   => [],
										"ssl_key_file"   => [],
										"ssl_key_password"   => [],
										"verify_peer"   => "0",
										"verify_host"   => "0",
										"master_item"   => [],
										"interface_ref"   => "if2"
									]
								],
								"discovery_rules"   => [
									"discovery_rule"   => [
										"name"   => "test",
										"type"   => "0",
										"snmp_community"   => [],
										"snmp_oid"   => [],
										"key"   => "vfs.file.contents[/tmp/discovery2.txt]",
										"delay"   => "30s",
										"status"   => "0",
										"allowed_hosts"   => [],
										"snmpv3_contextname"   => [],
										"snmpv3_securityname"   => [],
										"snmpv3_securitylevel"   => "0",
										"snmpv3_authprotocol"   => "0",
										"snmpv3_authpassphrase"   => [],
										"snmpv3_privprotocol"   => "0",
										"snmpv3_privpassphrase"   => [],
										"params"   => [],
										"ipmi_sensor"   => [],
										"authtype"   => "0",
										"username"   => [],
										"password"   => [],
										"publickey"   => [],
										"privatekey"   => [],
										"port"   => [],
										"filter"   => [
											"evaltype"   => "0",
											"formula"   => [],
											"conditions"   => []
										],
										"lifetime"   => "30d",
										"description"   => [],
										"item_prototypes"   => [
											"item_prototype"   => [
												"name"   => "snmp empty port",
												"type"   => "6",
												"snmp_community"   => [],
												"snmp_oid"   => "123",
												"key"   => "test9",
												"delay"   => "30s",
												"history"   => "90d",
												"trends"   => "365d",
												"status"   => "0",
												"value_type"   => "3",
												"allowed_hosts"   => [],
												"units"   => [],
												"snmpv3_contextname"   => [],
												"snmpv3_securityname"   => [],
												"snmpv3_securitylevel"   => "0",
												"snmpv3_authprotocol"   => "0",
												"snmpv3_authpassphrase"   => [],
												"snmpv3_privprotocol"   => "0",
												"snmpv3_privpassphrase"   => [],
												"params"   => [],
												"ipmi_sensor"   => [],
												"authtype"   => "0",
												"username"   => [],
												"password"   => [],
												"publickey"   => [],
												"privatekey"   => [],
												"port"   => [],
												"description"   => [],
												"inventory_link"   => "0",
												"applications"   => [],
												"valuemap"   => [],
												"logtimefmt"   => [],
												"preprocessing"   => [],
												"jmx_endpoint"   => [],
												"timeout"   => "3s",
												"url"   => [],
												"query_fields"   => [],
												"posts"   => [],
												"status_codes"   => "200",
												"follow_redirects"   => "1",
												"post_type"   => "0",
												"http_proxy"   => [],
												"headers"   => [],
												"retrieve_mode"   => "0",
												"request_method"   => "0",
												"output_format"   => "0",
												"allow_traps"   => "0",
												"ssl_cert_file"   => [],
												"ssl_key_file"   => [],
												"ssl_key_password"   => [],
												"verify_peer"   => "0",
												"verify_host"   => "0",
												"application_prototypes"   => [],
												"master_item"   => [],
												"interface_ref"   => "if2"
											]
										],
										"trigger_prototypes"   => [],
										"graph_prototypes"   => [],
										"host_prototypes"   => [],
										"jmx_endpoint"   => [],
										"timeout"   => "3s",
										"url"   => [],
										"query_fields"   => [],
										"posts"   => [],
										"status_codes"   => "200",
										"follow_redirects"   => "1",
										"post_type"   => "0",
										"http_proxy"   => [],
										"headers"   => [],
										"retrieve_mode"   => "0",
										"request_method"   => "0",
										"allow_traps"   => "0",
										"ssl_cert_file"   => [],
										"ssl_key_file"   => [],
										"ssl_key_password"   => [],
										"verify_peer"   => "0",
										"verify_host"   => "0",
										"interface_ref"   => "if1"
									]
								],
								"httptests"   => [],
								"macros"   => [],
								"inventory"   => [
									"inventory_mode"   => "-1"
								]
							]
						]
					],
				[
					[
						"hosts" => [
							"host" => [
								"host" => "HOST",
								"name" => "HOST",
								"groups" => [
									"group" => [
										"name" => "Zabbix servers"
									]
								],
								"interfaces" => [
									[
										"interface_ref" => "if1"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "88",
										"details" => [
											"version" => "SNMPV3",
											"contextname" => "context3",
											"securityname" => "name3",
											"securitylevel" => "AUTHNOPRIV",
											"authpassphrase" => "33"
										],
										"interface_ref" => "if8"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "99",
										"details" => [
											"version" => "SNMPV1",
											"community" => "public"
										],
										"interface_ref" => "if3"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "99",
										"details" => [
											"community" => "public"
										],
										"interface_ref" => "if5"
									],
									[
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "161",
										"details" => [
											"version" => "SNMPV1",
											"community" => "public"
										],
										"interface_ref" => "if2"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "161",
										"details" => [
											"community" => "public"
										],
										"interface_ref" => "if4"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "161",
										"details" => [
											"version" => "SNMPV3",
											"contextname" => "context1",
											"securityname" => "name1"
										],
										"interface_ref" => "if6"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "161",
										"details" => [
											"version" => "SNMPV3",
											"contextname" => "context2",
											"securityname" => "name2"
										],
										"interface_ref" => "if7"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "161",
										"details" => [
											"version" => "SNMPV3"
										],
										"interface_ref" => "if9"
									]
								],
								"items" => [
									[
										"name" => "snmp trap",
										"type" => "SNMP_TRAP",
										"key" => "snmptrap.fallback",
										"delay" => "0",
										"interface_ref" => "if2"
									],
									[
										"name" => "V1  public same port",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test",
										"delay" => "30s",
										"interface_ref" => "if2"
									],
									[
										"name" => "V1  public empty port",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test1",
										"delay" => "30s",
										"interface_ref" => "if2"
									],
									[
										"name" => "V1  public 99 port",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test2",
										"delay" => "30s",
										"interface_ref" => "if3"
									],
									[
										"name" => "V2 same port public",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test3",
										"delay" => "30s",
										"interface_ref" => "if4"
									],
									[
										"name" => "V2 empty port public",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test4",
										"delay" => "30s",
										"interface_ref" => "if4"
									],
									[
										"name" => "V2  port 99 public",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test5",
										"delay" => "30s",
										"interface_ref" => "if5"
									],
									[
										"name" => "V3 same port public context security",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test6",
										"delay" => "30s",
										"interface_ref" => "if6"
									],
									[
										"name" => "V3 empty port public context2 security2",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test7",
										"delay" => "30s",
										"interface_ref" => "if7"
									],
									[
										"name" => "V3  port  88 public context3 security3",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "88",
										"key" => "test8",
										"delay" => "30s",
										"interface_ref" => "if8"
									]
								],
								"discovery_rules" => [
									[
										"name" => "drule_snmp",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "1.3.6.1.2.1.1.1.0",
										"key" => "agent.ping",
										"delay" => "30s",
										"interface_ref" => "if4",
										"item_prototypes" => [
											[
												"name" => "prot_snmp",
												"type" => "SNMP_AGENT",
												"snmp_oid" => "1.3.6.1.2.1.1.1.0",
												"key" => "cpu.load.average",
												"delay" => "30s",
												"interface_ref" => "if2"
											],
											[
												"name" => "prot_agent",
												"key" => "net.tcp.service.perf[http]",
												"delay" => "30s",
												"interface_ref" => "if1"
											]
										]
									],
									[
										"name" => "test",
										"key" => "vfs.file.contents[/tmp/discovery2.txt]",
										"delay" => "30s",
										"interface_ref" => "if1",
										"item_prototypes" => [
											"item_prototype" => [
												"name" => "snmp empty port",
												"type" => "SNMP_AGENT",
												"snmp_oid" => "123",
												"key" => "test9",
												"delay" => "30s",
												"interface_ref" => "if9"
											]
										]
									]
								],
								"inventory_mode" => "DISABLED"
							]
						]
					]
				]
			],
			[
				[
					[
						"hosts" => [
							"host" => [
								"host" => "HOST",
								"name" => "HOST",
								"description" => [],
								"proxy" => [],
								"status" => "0",
								"ipmi_authtype" => "-1",
								"ipmi_privilege" => "2",
								"ipmi_username" => [],
								"ipmi_password" => [],
								"tls_connect" => "1",
								"tls_accept" => "1",
								"tls_issuer" => [],
								"tls_subject" => [],
								"tls_psk_identity" => [],
								"tls_psk" => [],
								"templates" => [],
								"groups" => [
									"group" => [
										"name" => "Zabbix servers"
									]
								],
								"interfaces" => [
									[
										"default" => "1",
										"type" => "1",
										"useip" => "1",
										"ip" => "127.0.0.1",
										"dns" => [],
										"port" => "10050",
										"bulk" => "1",
										"interface_ref" => "if1"
									],
									[
										"default" => "1",
										"type" => "2",
										"useip" => "1",
										"ip" => "127.0.0.1",
										"dns" => "SNMP",
										"port" => "161",
										"bulk" => "1",
										"interface_ref" => "if2"
									]
								],
								"applications" => [],
								"items" => [
									[
										"name" => "snmp trap",
										"type" => "17",
										"snmp_community" => [],
										"snmp_oid" => [],
										"key" => "snmptrap.fallback",
										"delay" => "0",
										"history" => "90d",
										"trends" => "365d",
										"status" => "0",
										"value_type" => "3",
										"allowed_hosts" => [],
										"units" => [],
										"snmpv3_contextname" => [],
										"snmpv3_securityname" => [],
										"snmpv3_securitylevel" => "0",
										"snmpv3_authprotocol" => "0",
										"snmpv3_authpassphrase" => [],
										"snmpv3_privprotocol" => "0",
										"snmpv3_privpassphrase" => [],
										"params" => [],
										"ipmi_sensor" => [],
										"authtype" => "0",
										"username" => [],
										"password" => [],
										"publickey" => [],
										"privatekey" => [],
										"port" => [],
										"description" => [],
										"inventory_link" => "0",
										"applications" => [],
										"valuemap" => [],
										"logtimefmt" => [],
										"preprocessing" => [],
										"jmx_endpoint" => [],
										"timeout" => "3s",
										"url" => [],
										"query_fields" => [],
										"posts" => [],
										"status_codes" => "200",
										"follow_redirects" => "1",
										"post_type" => "0",
										"http_proxy" => [],
										"headers" => [],
										"retrieve_mode" => "0",
										"request_method" => "0",
										"output_format" => "0",
										"allow_traps" => "0",
										"ssl_cert_file" => [],
										"ssl_key_file" => [],
										"ssl_key_password" => [],
										"verify_peer" => "0",
										"verify_host" => "0",
										"master_item" => [],
										"interface_ref" => "if2"
									],
									[
										"name" => "V1  public same port",
										"type" => "1",
										"snmp_community" => "public",
										"snmp_oid" => "123",
										"key" => "test",
										"delay" => "30s",
										"history" => "90d",
										"trends" => "365d",
										"status" => "0",
										"value_type" => "3",
										"allowed_hosts" => [],
										"units" => [],
										"snmpv3_contextname" => [],
										"snmpv3_securityname" => [],
										"snmpv3_securitylevel" => "0",
										"snmpv3_authprotocol" => "0",
										"snmpv3_authpassphrase" => [],
										"snmpv3_privprotocol" => "0",
										"snmpv3_privpassphrase" => [],
										"params" => [],
										"ipmi_sensor" => [],
										"authtype" => "0",
										"username" => [],
										"password" => [],
										"publickey" => [],
										"privatekey" => [],
										"port" => "161",
										"description" => [],
										"inventory_link" => "0",
										"applications" => [],
										"valuemap" => [],
										"logtimefmt" => [],
										"preprocessing" => [],
										"jmx_endpoint" => [],
										"timeout" => "3s",
										"url" => [],
										"query_fields" => [],
										"posts" => [],
										"status_codes" => "200",
										"follow_redirects" => "1",
										"post_type" => "0",
										"http_proxy" => [],
										"headers" => [],
										"retrieve_mode" => "0",
										"request_method" => "0",
										"output_format" => "0",
										"allow_traps" => "0",
										"ssl_cert_file" => [],
										"ssl_key_file" => [],
										"ssl_key_password" => [],
										"verify_peer" => "0",
										"verify_host" => "0",
										"master_item" => [],
										"interface_ref" => "if2"
									],
									[
										"name" => "V1  public empty port",
										"type" => "1",
										"snmp_community" => "public",
										"snmp_oid" => "123",
										"key" => "test1",
										"delay" => "30s",
										"history" => "90d",
										"trends" => "365d",
										"status" => "0",
										"value_type" => "3",
										"allowed_hosts" => [],
										"units" => [],
										"snmpv3_contextname" => [],
										"snmpv3_securityname" => [],
										"snmpv3_securitylevel" => "0",
										"snmpv3_authprotocol" => "0",
										"snmpv3_authpassphrase" => [],
										"snmpv3_privprotocol" => "0",
										"snmpv3_privpassphrase" => [],
										"params" => [],
										"ipmi_sensor" => [],
										"authtype" => "0",
										"username" => [],
										"password" => [],
										"publickey" => [],
										"privatekey" => [],
										"port" => [],
										"description" => [],
										"inventory_link" => "0",
										"applications" => [],
										"valuemap" => [],
										"logtimefmt" => [],
										"preprocessing" => [],
										"jmx_endpoint" => [],
										"timeout" => "3s",
										"url" => [],
										"query_fields" => [],
										"posts" => [],
										"status_codes" => "200",
										"follow_redirects" => "1",
										"post_type" => "0",
										"http_proxy" => [],
										"headers" => [],
										"retrieve_mode" => "0",
										"request_method" => "0",
										"output_format" => "0",
										"allow_traps" => "0",
										"ssl_cert_file" => [],
										"ssl_key_file" => [],
										"ssl_key_password" => [],
										"verify_peer" => "0",
										"verify_host" => "0",
										"master_item" => [],
										"interface_ref" => "if2"
									],
									[
										"name" => "V1  public 99 port",
										"type" => "1",
										"snmp_community" => "public",
										"snmp_oid" => "123",
										"key" => "test2",
										"delay" => "30s",
										"history" => "90d",
										"trends" => "365d",
										"status" => "0",
										"value_type" => "3",
										"allowed_hosts" => [],
										"units" => [],
										"snmpv3_contextname" => [],
										"snmpv3_securityname" => [],
										"snmpv3_securitylevel" => "0",
										"snmpv3_authprotocol" => "0",
										"snmpv3_authpassphrase" => [],
										"snmpv3_privprotocol" => "0",
										"snmpv3_privpassphrase" => [],
										"params" => [],
										"ipmi_sensor" => [],
										"authtype" => "0",
										"username" => [],
										"password" => [],
										"publickey" => [],
										"privatekey" => [],
										"port" => "99",
										"description" => [],
										"inventory_link" => "0",
										"applications" => [],
										"valuemap" => [],
										"logtimefmt" => [],
										"preprocessing" => [],
										"jmx_endpoint" => [],
										"timeout" => "3s",
										"url" => [],
										"query_fields" => [],
										"posts" => [],
										"status_codes" => "200",
										"follow_redirects" => "1",
										"post_type" => "0",
										"http_proxy" => [],
										"headers" => [],
										"retrieve_mode" => "0",
										"request_method" => "0",
										"output_format" => "0",
										"allow_traps" => "0",
										"ssl_cert_file" => [],
										"ssl_key_file" => [],
										"ssl_key_password" => [],
										"verify_peer" => "0",
										"verify_host" => "0",
										"master_item" => [],
										"interface_ref" => "if2"
									],
									[
										"name" => "V2 same port public",
										"type" => "4",
										"snmp_community" => "public",
										"snmp_oid" => "123",
										"key" => "test3",
										"delay" => "30s",
										"history" => "90d",
										"trends" => "365d",
										"status" => "0",
										"value_type" => "3",
										"allowed_hosts" => [],
										"units" => [],
										"snmpv3_contextname" => [],
										"snmpv3_securityname" => [],
										"snmpv3_securitylevel" => "0",
										"snmpv3_authprotocol" => "0",
										"snmpv3_authpassphrase" => [],
										"snmpv3_privprotocol" => "0",
										"snmpv3_privpassphrase" => [],
										"params" => [],
										"ipmi_sensor" => [],
										"authtype" => "0",
										"username" => [],
										"password" => [],
										"publickey" => [],
										"privatekey" => [],
										"port" => "161",
										"description" => [],
										"inventory_link" => "0",
										"applications" => [],
										"valuemap" => [],
										"logtimefmt" => [],
										"preprocessing" => [],
										"jmx_endpoint" => [],
										"timeout" => "3s",
										"url" => [],
										"query_fields" => [],
										"posts" => [],
										"status_codes" => "200",
										"follow_redirects" => "1",
										"post_type" => "0",
										"http_proxy" => [],
										"headers" => [],
										"retrieve_mode" => "0",
										"request_method" => "0",
										"output_format" => "0",
										"allow_traps" => "0",
										"ssl_cert_file" => [],
										"ssl_key_file" => [],
										"ssl_key_password" => [],
										"verify_peer" => "0",
										"verify_host" => "0",
										"master_item" => [],
										"interface_ref" => "if2"
									],
									[
										"name" => "V2 empty port public",
										"type" => "4",
										"snmp_community" => "public",
										"snmp_oid" => "123",
										"key" => "test4",
										"delay" => "30s",
										"history" => "90d",
										"trends" => "365d",
										"status" => "0",
										"value_type" => "3",
										"allowed_hosts" => [],
										"units" => [],
										"snmpv3_contextname" => [],
										"snmpv3_securityname" => [],
										"snmpv3_securitylevel" => "0",
										"snmpv3_authprotocol" => "0",
										"snmpv3_authpassphrase" => [],
										"snmpv3_privprotocol" => "0",
										"snmpv3_privpassphrase" => [],
										"params" => [],
										"ipmi_sensor" => [],
										"authtype" => "0",
										"username" => [],
										"password" => [],
										"publickey" => [],
										"privatekey" => [],
										"port" => [],
										"description" => [],
										"inventory_link" => "0",
										"applications" => [],
										"valuemap" => [],
										"logtimefmt" => [],
										"preprocessing" => [],
										"jmx_endpoint" => [],
										"timeout" => "3s",
										"url" => [],
										"query_fields" => [],
										"posts" => [],
										"status_codes" => "200",
										"follow_redirects" => "1",
										"post_type" => "0",
										"http_proxy" => [],
										"headers" => [],
										"retrieve_mode" => "0",
										"request_method" => "0",
										"output_format" => "0",
										"allow_traps" => "0",
										"ssl_cert_file" => [],
										"ssl_key_file" => [],
										"ssl_key_password" => [],
										"verify_peer" => "0",
										"verify_host" => "0",
										"master_item" => [],
										"interface_ref" => "if2"
									],
									[
										"name" => "V2  port 99 public",
										"type" => "4",
										"snmp_community" => "public",
										"snmp_oid" => "123",
										"key" => "test5",
										"delay" => "30s",
										"history" => "90d",
										"trends" => "365d",
										"status" => "0",
										"value_type" => "3",
										"allowed_hosts" => [],
										"units" => [],
										"snmpv3_contextname" => [],
										"snmpv3_securityname" => [],
										"snmpv3_securitylevel" => "0",
										"snmpv3_authprotocol" => "0",
										"snmpv3_authpassphrase" => [],
										"snmpv3_privprotocol" => "0",
										"snmpv3_privpassphrase" => [],
										"params" => [],
										"ipmi_sensor" => [],
										"authtype" => "0",
										"username" => [],
										"password" => [],
										"publickey" => [],
										"privatekey" => [],
										"port" => "99",
										"description" => [],
										"inventory_link" => "0",
										"applications" => [],
										"valuemap" => [],
										"logtimefmt" => [],
										"preprocessing" => [],
										"jmx_endpoint" => [],
										"timeout" => "3s",
										"url" => [],
										"query_fields" => [],
										"posts" => [],
										"status_codes" => "200",
										"follow_redirects" => "1",
										"post_type" => "0",
										"http_proxy" => [],
										"headers" => [],
										"retrieve_mode" => "0",
										"request_method" => "0",
										"output_format" => "0",
										"allow_traps" => "0",
										"ssl_cert_file" => [],
										"ssl_key_file" => [],
										"ssl_key_password" => [],
										"verify_peer" => "0",
										"verify_host" => "0",
										"master_item" => [],
										"interface_ref" => "if2"
									],
									[
										"name" => "V3 same port public context security",
										"type" => "6",
										"snmp_community" => [],
										"snmp_oid" => "123",
										"key" => "test6",
										"delay" => "30s",
										"history" => "90d",
										"trends" => "365d",
										"status" => "0",
										"value_type" => "3",
										"allowed_hosts" => [],
										"units" => [],
										"snmpv3_contextname" => "context1",
										"snmpv3_securityname" => "name1",
										"snmpv3_securitylevel" => "0",
										"snmpv3_authprotocol" => "0",
										"snmpv3_authpassphrase" => [],
										"snmpv3_privprotocol" => "0",
										"snmpv3_privpassphrase" => [],
										"params" => [],
										"ipmi_sensor" => [],
										"authtype" => "0",
										"username" => [],
										"password" => [],
										"publickey" => [],
										"privatekey" => [],
										"port" => "161",
										"description" => [],
										"inventory_link" => "0",
										"applications" => [],
										"valuemap" => [],
										"logtimefmt" => [],
										"preprocessing" => [],
										"jmx_endpoint" => [],
										"timeout" => "3s",
										"url" => [],
										"query_fields" => [],
										"posts" => [],
										"status_codes" => "200",
										"follow_redirects" => "1",
										"post_type" => "0",
										"http_proxy" => [],
										"headers" => [],
										"retrieve_mode" => "0",
										"request_method" => "0",
										"output_format" => "0",
										"allow_traps" => "0",
										"ssl_cert_file" => [],
										"ssl_key_file" => [],
										"ssl_key_password" => [],
										"verify_peer" => "0",
										"verify_host" => "0",
										"master_item" => [],
										"interface_ref" => "if2"
									],
									[
										"name" => "V3 empty port public context2 security2",
										"type" => "6",
										"snmp_community" => [],
										"snmp_oid" => "123",
										"key" => "test7",
										"delay" => "30s",
										"history" => "90d",
										"trends" => "365d",
										"status" => "0",
										"value_type" => "3",
										"allowed_hosts" => [],
										"units" => [],
										"snmpv3_contextname" => "context2",
										"snmpv3_securityname" => "name2",
										"snmpv3_securitylevel" => "0",
										"snmpv3_authprotocol" => "0",
										"snmpv3_authpassphrase" => [],
										"snmpv3_privprotocol" => "0",
										"snmpv3_privpassphrase" => [],
										"params" => [],
										"ipmi_sensor" => [],
										"authtype" => "0",
										"username" => [],
										"password" => [],
										"publickey" => [],
										"privatekey" => [],
										"port" => [],
										"description" => [],
										"inventory_link" => "0",
										"applications" => [],
										"valuemap" => [],
										"logtimefmt" => [],
										"preprocessing" => [],
										"jmx_endpoint" => [],
										"timeout" => "3s",
										"url" => [],
										"query_fields" => [],
										"posts" => [],
										"status_codes" => "200",
										"follow_redirects" => "1",
										"post_type" => "0",
										"http_proxy" => [],
										"headers" => [],
										"retrieve_mode" => "0",
										"request_method" => "0",
										"output_format" => "0",
										"allow_traps" => "0",
										"ssl_cert_file" => [],
										"ssl_key_file" => [],
										"ssl_key_password" => [],
										"verify_peer" => "0",
										"verify_host" => "0",
										"master_item" => [],
										"interface_ref" => "if2"
									],
									[
										"name" => "V3  port  88 public context3 security3",
										"type" => "6",
										"snmp_community" => [],
										"snmp_oid" => "88",
										"key" => "test8",
										"delay" => "30s",
										"history" => "90d",
										"trends" => "365d",
										"status" => "0",
										"value_type" => "3",
										"allowed_hosts" => [],
										"units" => [],
										"snmpv3_contextname" => "context3",
										"snmpv3_securityname" => "name3",
										"snmpv3_securitylevel" => "1",
										"snmpv3_authprotocol" => "0",
										"snmpv3_authpassphrase" => "33",
										"snmpv3_privprotocol" => "0",
										"snmpv3_privpassphrase" => [],
										"params" => [],
										"ipmi_sensor" => [],
										"authtype" => "0",
										"username" => [],
										"password" => [],
										"publickey" => [],
										"privatekey" => [],
										"port" => "88",
										"description" => [],
										"inventory_link" => "0",
										"applications" => [],
										"valuemap" => [],
										"logtimefmt" => [],
										"preprocessing" => [],
										"jmx_endpoint" => [],
										"timeout" => "3s",
										"url" => [],
										"query_fields" => [],
										"posts" => [],
										"status_codes" => "200",
										"follow_redirects" => "1",
										"post_type" => "0",
										"http_proxy" => [],
										"headers" => [],
										"retrieve_mode" => "0",
										"request_method" => "0",
										"output_format" => "0",
										"allow_traps" => "0",
										"ssl_cert_file" => [],
										"ssl_key_file" => [],
										"ssl_key_password" => [],
										"verify_peer" => "0",
										"verify_host" => "0",
										"master_item" => [],
										"interface_ref" => "if2"
									]
								],
								"discovery_rules" => [
									[
										"name" => "drule_snmp",
										"type" => "4",
										"snmp_community" => "public",
										"snmp_oid" => "1.3.6.1.2.1.1.1.0",
										"key" => "agent.ping",
										"delay" => "30s",
										"status" => "0",
										"allowed_hosts" => [],
										"snmpv3_contextname" => [],
										"snmpv3_securityname" => [],
										"snmpv3_securitylevel" => "0",
										"snmpv3_authprotocol" => "0",
										"snmpv3_authpassphrase" => [],
										"snmpv3_privprotocol" => "0",
										"snmpv3_privpassphrase" => [],
										"params" => [],
										"ipmi_sensor" => [],
										"authtype" => "0",
										"username" => [],
										"password" => [],
										"publickey" => [],
										"privatekey" => [],
										"port" => [],
										"filter" => [
											"evaltype" => "0",
											"formula" => [],
											"conditions" => []
										],
										"lifetime" => "30d",
										"description" => [],
										"item_prototypes" => [
											[
												"name" => "prot_snmp",
												"type" => "1",
												"snmp_community" => "public",
												"snmp_oid" => "1.3.6.1.2.1.1.1.0",
												"key" => "cpu.load.average",
												"delay" => "30s",
												"history" => "90d",
												"trends" => "365d",
												"status" => "0",
												"value_type" => "3",
												"allowed_hosts" => [],
												"units" => [],
												"snmpv3_contextname" => [],
												"snmpv3_securityname" => [],
												"snmpv3_securitylevel" => "0",
												"snmpv3_authprotocol" => "0",
												"snmpv3_authpassphrase" => [],
												"snmpv3_privprotocol" => "0",
												"snmpv3_privpassphrase" => [],
												"params" => [],
												"ipmi_sensor" => [],
												"authtype" => "0",
												"username" => [],
												"password" => [],
												"publickey" => [],
												"privatekey" => [],
												"port" => [],
												"description" => [],
												"inventory_link" => "0",
												"applications" => [],
												"valuemap" => [],
												"logtimefmt" => [],
												"preprocessing" => [],
												"jmx_endpoint" => [],
												"timeout" => "3s",
												"url" => [],
												"query_fields" => [],
												"posts" => [],
												"status_codes" => "200",
												"follow_redirects" => "1",
												"post_type" => "0",
												"http_proxy" => [],
												"headers" => [],
												"retrieve_mode" => "0",
												"request_method" => "0",
												"output_format" => "0",
												"allow_traps" => "0",
												"ssl_cert_file" => [],
												"ssl_key_file" => [],
												"ssl_key_password" => [],
												"verify_peer" => "0",
												"verify_host" => "0",
												"application_prototypes" => [],
												"master_item" => [],
												"interface_ref" => "if2"
											],
											[
												"name" => "prot_agent",
												"type" => "0",
												"snmp_community" => [],
												"snmp_oid" => [],
												"key" => "net.tcp.service.perf[http]",
												"delay" => "30s",
												"history" => "90d",
												"trends" => "365d",
												"status" => "0",
												"value_type" => "3",
												"allowed_hosts" => [],
												"units" => [],
												"snmpv3_contextname" => [],
												"snmpv3_securityname" => [],
												"snmpv3_securitylevel" => "0",
												"snmpv3_authprotocol" => "0",
												"snmpv3_authpassphrase" => [],
												"snmpv3_privprotocol" => "0",
												"snmpv3_privpassphrase" => [],
												"params" => [],
												"ipmi_sensor" => [],
												"authtype" => "0",
												"username" => [],
												"password" => [],
												"publickey" => [],
												"privatekey" => [],
												"port" => [],
												"description" => [],
												"inventory_link" => "0",
												"applications" => [],
												"valuemap" => [],
												"logtimefmt" => [],
												"preprocessing" => [],
												"jmx_endpoint" => [],
												"timeout" => "3s",
												"url" => [],
												"query_fields" => [],
												"posts" => [],
												"status_codes" => "200",
												"follow_redirects" => "1",
												"post_type" => "0",
												"http_proxy" => [],
												"headers" => [],
												"retrieve_mode" => "0",
												"request_method" => "0",
												"output_format" => "0",
												"allow_traps" => "0",
												"ssl_cert_file" => [],
												"ssl_key_file" => [],
												"ssl_key_password" => [],
												"verify_peer" => "0",
												"verify_host" => "0",
												"application_prototypes" => [],
												"master_item" => [],
												"interface_ref" => "if1"
											]
										],
										"trigger_prototypes" => [],
										"graph_prototypes" => [],
										"host_prototypes" => [],
										"jmx_endpoint" => [],
										"timeout" => "3s",
										"url" => [],
										"query_fields" => [],
										"posts" => [],
										"status_codes" => "200",
										"follow_redirects" => "1",
										"post_type" => "0",
										"http_proxy" => [],
										"headers" => [],
										"retrieve_mode" => "0",
										"request_method" => "0",
										"allow_traps" => "0",
										"ssl_cert_file" => [],
										"ssl_key_file" => [],
										"ssl_key_password" => [],
										"verify_peer" => "0",
										"verify_host" => "0",
										"interface_ref" => "if2"
									],
									[
										"name" => "test",
										"type" => "0",
										"snmp_community" => [],
										"snmp_oid" => [],
										"key" => "vfs.file.contents[/tmp/discovery2.txt]",
										"delay" => "30s",
										"status" => "0",
										"allowed_hosts" => [],
										"snmpv3_contextname" => [],
										"snmpv3_securityname" => [],
										"snmpv3_securitylevel" => "0",
										"snmpv3_authprotocol" => "0",
										"snmpv3_authpassphrase" => [],
										"snmpv3_privprotocol" => "0",
										"snmpv3_privpassphrase" => [],
										"params" => [],
										"ipmi_sensor" => [],
										"authtype" => "0",
										"username" => [],
										"password" => [],
										"publickey" => [],
										"privatekey" => [],
										"port" => [],
										"filter" => [
											"evaltype" => "0",
											"formula" => [],
											"conditions" => []
										],
										"lifetime" => "30d",
										"description" => [],
										"item_prototypes" => [
											"item_prototype" => [
												"name" => "snmp empty port",
												"type" => "6",
												"snmp_community" => [],
												"snmp_oid" => "123",
												"key" => "test9",
												"delay" => "30s",
												"history" => "90d",
												"trends" => "365d",
												"status" => "0",
												"value_type" => "3",
												"allowed_hosts" => [],
												"units" => [],
												"snmpv3_contextname" => [],
												"snmpv3_securityname" => [],
												"snmpv3_securitylevel" => "0",
												"snmpv3_authprotocol" => "0",
												"snmpv3_authpassphrase" => [],
												"snmpv3_privprotocol" => "0",
												"snmpv3_privpassphrase" => [],
												"params" => [],
												"ipmi_sensor" => [],
												"authtype" => "0",
												"username" => [],
												"password" => [],
												"publickey" => [],
												"privatekey" => [],
												"port" => [],
												"description" => [],
												"inventory_link" => "0",
												"applications" => [],
												"valuemap" => [],
												"logtimefmt" => [],
												"preprocessing" => [],
												"jmx_endpoint" => [],
												"timeout" => "3s",
												"url" => [],
												"query_fields" => [],
												"posts" => [],
												"status_codes" => "200",
												"follow_redirects" => "1",
												"post_type" => "0",
												"http_proxy" => [],
												"headers" => [],
												"retrieve_mode" => "0",
												"request_method" => "0",
												"output_format" => "0",
												"allow_traps" => "0",
												"ssl_cert_file" => [],
												"ssl_key_file" => [],
												"ssl_key_password" => [],
												"verify_peer" => "0",
												"verify_host" => "0",
												"application_prototypes" => [],
												"master_item" => [],
												"interface_ref" => "if2"
											]
										],
										"trigger_prototypes" => [],
										"graph_prototypes" => [],
										"host_prototypes" => [],
										"jmx_endpoint" => [],
										"timeout" => "3s",
										"url" => [],
										"query_fields" => [],
										"posts" => [],
										"status_codes" => "200",
										"follow_redirects" => "1",
										"post_type" => "0",
										"http_proxy" => [],
										"headers" => [],
										"retrieve_mode" => "0",
										"request_method" => "0",
										"allow_traps" => "0",
										"ssl_cert_file" => [],
										"ssl_key_file" => [],
										"ssl_key_password" => [],
										"verify_peer" => "0",
										"verify_host" => "0",
										"interface_ref" => "if1"
									]
								],
								"httptests" => [],
								"macros" => [],
								"inventory" => [
									"inventory_mode" => "-1"
								]
							]
						]
					]
				],
				[
					[
						"hosts" => [
							"host" => [
								"host" => "HOST",
								"name" => "HOST",
								"groups" => [
									"group" => [
										"name" => "Zabbix servers"
									]
								],
								"interfaces" => [
									[
										"interface_ref" => "if1"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "88",
										"details" => [
											"version" => "SNMPV3",
											"contextname" => "context3",
											"securityname" => "name3",
											"securitylevel" => "AUTHNOPRIV",
											"authpassphrase" => "33"
										],
										"interface_ref" => "if8"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "99",
										"details" => [
											"version" => "SNMPV1",
											"community" => "public"
										],
										"interface_ref" => "if3"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "99",
										"details" => [
											"community" => "public"
										],
										"interface_ref" => "if5"
									],
									[
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "161",
										"details" => [
											"version" => "SNMPV1",
											"community" => "public"
										],
										"interface_ref" => "if2"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "161",
										"details" => [
											"community" => "public"
										],
										"interface_ref" => "if4"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "161",
										"details" => [
											"version" => "SNMPV3",
											"contextname" => "context1",
											"securityname" => "name1"
										],
										"interface_ref" => "if6"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "161",
										"details" => [
											"version" => "SNMPV3",
											"contextname" => "context2",
											"securityname" => "name2"
										],
										"interface_ref" => "if7"
									],
									[
										"default" => "NO",
										"type" => "SNMP",
										"dns" => "SNMP",
										"port" => "161",
										"details" => [
											"version" => "SNMPV3"
										],
										"interface_ref" => "if9"
									]
								],
								"items" => [
									[
										"name" => "snmp trap",
										"type" => "SNMP_TRAP",
										"key" => "snmptrap.fallback",
										"delay" => "0",
										"interface_ref" => "if2"
									],
									[
										"name" => "V1  public same port",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test",
										"delay" => "30s",
										"interface_ref" => "if2"
									],
									[
										"name" => "V1  public empty port",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test1",
										"delay" => "30s",
										"interface_ref" => "if2"
									],
									[
										"name" => "V1  public 99 port",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test2",
										"delay" => "30s",
										"interface_ref" => "if3"
									],
									[
										"name" => "V2 same port public",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test3",
										"delay" => "30s",
										"interface_ref" => "if4"
									],
									[
										"name" => "V2 empty port public",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test4",
										"delay" => "30s",
										"interface_ref" => "if4"
									],
									[
										"name" => "V2  port 99 public",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test5",
										"delay" => "30s",
										"interface_ref" => "if5"
									],
									[
										"name" => "V3 same port public context security",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test6",
										"delay" => "30s",
										"interface_ref" => "if6"
									],
									[
										"name" => "V3 empty port public context2 security2",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "123",
										"key" => "test7",
										"delay" => "30s",
										"interface_ref" => "if7"
									],
									[
										"name" => "V3  port  88 public context3 security3",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "88",
										"key" => "test8",
										"delay" => "30s",
										"interface_ref" => "if8"
									]
								],
								"discovery_rules" => [
									[
										"name" => "drule_snmp",
										"type" => "SNMP_AGENT",
										"snmp_oid" => "1.3.6.1.2.1.1.1.0",
										"key" => "agent.ping",
										"delay" => "30s",
										"interface_ref" => "if4",
										"item_prototypes" => [
											[
												"name" => "prot_snmp",
												"type" => "SNMP_AGENT",
												"snmp_oid" => "1.3.6.1.2.1.1.1.0",
												"key" => "cpu.load.average",
												"delay" => "30s",
												"interface_ref" => "if2"
											],
											[
												"name" => "prot_agent",
												"key" => "net.tcp.service.perf[http]",
												"delay" => "30s",
												"interface_ref" => "if1"
											]
										]
									],
									[
										"name" => "test",
										"key" => "vfs.file.contents[/tmp/discovery2.txt]",
										"delay" => "30s",
										"interface_ref" => "if1",
										"item_prototypes" => [
											"item_prototype" => [
												"name" => "snmp empty port",
												"type" => "SNMP_AGENT",
												"snmp_oid" => "123",
												"key" => "test9",
												"delay" => "30s",
												"interface_ref" => "if9"
											]
										]
									]
								],
								"inventory_mode" => "DISABLED"
							]
						]
					]
				]
			]
		];
	}

	/**
	 * @dataProvider dataProviderConvert
	 *
	 * @param array $data
	 * @param array $expected
	 */
	public function testConvert(array $data, array $expected) {
		$this->assertConvert($this->createExpectedResult($expected), $this->createSource($data));
	}

	protected function createSource(array $data = []) {
		return [
			'zabbix_export' => array_merge([
				'version' => '4.4',
				'date' => '2020-01-01T00:00:00Z'
			], $data)
		];
	}

	protected function createExpectedResult(array $data = []) {
		return [
			'zabbix_export' => array_merge([
				'version' => '5.0',
				'date' => '2020-01-01T00:00:00Z'
			], $data)
		];
	}

	protected function assertConvert(array $expected, array $source) {
		$result = $this->createConverter()->convert($source);
		$this->assertSame($expected, $result);
	}

	protected function createConverter() {
		return new C44ImportConverter();
	}
}
