
# cmocka dependencies
MOCK_DATA_DEPS = \
	$(top_srcdir)/tests/libzbxmockdata.a \
	$(top_srcdir)/src/libs/zbxtime/libzbxtime.a \
	$(top_srcdir)/src/libs/zbxalgo/libzbxalgo.a \
	$(top_srcdir)/src/libs/zbxstr/libzbxstr.a \
	$(top_srcdir)/src/libs/zbxnum/libzbxnum.a \
	$(top_srcdir)/src/libs/zbxcommon/libzbxcommon.a \
	$(CMOCKA_LIBS) $(YAML_LIBS) $(TLS_LIBS)

MOCK_TEST_DEPS = \
	$(top_srcdir)/tests/libzbxmocktest.a \
	$(top_srcdir)/src/libs/zbxnix/libzbxnix.a \
	$(top_srcdir)/tests/libzbxmockdata.a \
	$(top_srcdir)/src/libs/zbxlog/libzbxlog.a \
	$(top_srcdir)/src/libs/zbxnum/libzbxnum.a \
	$(top_srcdir)/src/libs/zbxthreads/libzbxthreads.a \
	$(top_srcdir)/src/libs/zbxcomms/libzbxcomms.a \
	$(top_builddir)/src/libs/zbxresolver/libzbxresolver.a \
	$(top_srcdir)/src/libs/zbxcommon/libzbxcommon.a


ZBX_COMMON_LIBS = \
	$(top_builddir)/src/libs/zbxlog/libzbxlog.a \
	$(top_builddir)/src/libs/zbxcommon/libzbxcommon.a \
	$(top_builddir)/src/libs/zbxstr/libzbxstr.a \
	$(top_builddir)/src/libs/zbxnum/libzbxnum.a \
	$(top_builddir)/src/libs/zbxtime/libzbxtime.a \
	$(top_builddir)/src/libs/zbxjson/libzbxjson.a \
	$(top_builddir)/src/libs/zbxalgo/libzbxalgo.a \
	$(top_builddir)/src/libs/zbxthreads/libzbxthreads.a \
	$(top_builddir)/src/libs/zbxmutexs/libzbxmutexs.a \
	$(top_builddir)/src/libs/zbxprof/libzbxprof.a \
	$(top_builddir)/src/libs/zbxfile/libzbxfile.a \
	$(top_builddir)/src/libs/zbxvariant/libzbxvariant.a \
	$(top_builddir)/src/libs/zbxparam/libzbxparam.a \
	$(top_builddir)/src/libs/zbxexpr/libzbxexpr.a \
	$(top_builddir)/src/libs/zbxcompress/libzbxcompress.a \
	$(top_builddir)/src/libs/zbxgetopt/libzbxgetopt.a \
	$(top_builddir)/src/libs/zbxhash/libzbxhash.a \
	$(top_builddir)/src/libs/zbxcrypto/libzbxcrypto.a \
	$(top_builddir)/src/libs/zbxexec/libzbxexec.a \
	$(top_builddir)/src/libs/zbxip/libzbxip.a \
	$(top_builddir)/src/libs/zbxcfg/libzbxcfg.a \
	$(top_builddir)/src/libs/zbxinterface/libzbxinterface.a \
	$(top_builddir)/src/libs/zbxcomms/libzbxcomms.a \
	$(top_builddir)/src/libs/zbxcommshigh/libzbxcommshigh.a \
	$(top_builddir)/src/libs/zbxresolver/libzbxresolver.a \
	$(top_builddir)/src/libs/zbxregexp/libzbxregexp.a \
	$(top_builddir)/src/libs/zbxnix/libzbxnix.a \
	$(top_builddir)/src/libs/zbxcurl/libzbxcurl.a \
	$(top_builddir)/src/libs/zbxhttp/libzbxhttp.a \
	$(top_builddir)/src/libs/zbxsysinfo/common/libcommonsysinfo_httpmetrics.a \
	$(top_builddir)/src/libs/zbxsysinfo/common/libcommonsysinfo_http.a \
	$(top_builddir)/src/libs/zbxsysinfo/$(ARCH)/libspecsysinfo.a \
	$(top_builddir)/src/libs/zbxsysinfo/alias/libalias.a \
	$(top_builddir)/src/libs/zbxsysinfo/common/libcommonsysinfo.a \
	$(top_builddir)/src/libs/zbxsysinfo/simple/libsimplesysinfo.a \
	$(top_builddir)/src/libs/zbxmodules/libzbxmodules.a


ZBX_COMMON_LIBS += \
	$(top_srcdir)/tests/libzbxmockdata.a \
	$(top_srcdir)/tests/libzbxmocktest.a \
	$(top_srcdir)/tests/libzbxmockdummy.a


ZBX_SERVER_PROXY_LIBS = \
	$(top_builddir)/src/libs/zbxcalc/libzbxcalc.a \
	$(top_builddir)/src/libs/zbxdbsyncer/libzbxdbsyncer.a \
	$(top_builddir)/src/libs/zbxpinger/libzbxpinger.a \
	$(top_builddir)/src/libs/zbxsupervisor/libzbxsupervisor.a \
	$(top_builddir)/src/libs/zbxdiscoverer/libzbxdiscoverer.a \
	$(top_builddir)/src/libs/zbxtrapper/libzbxtrapper.a \
	$(top_builddir)/src/libs/zbxhttppoller/libzbxhttppoller.a \
	$(top_builddir)/src/libs/zbxpoller/libzbxpoller.a \
	$(top_builddir)/src/libs/zbxautoreg/libzbxautoreg.a \
	$(top_builddir)/src/libs/zbxsnmptrapper/libzbxsnmptrapper.a \
	$(top_builddir)/src/libs/zbxsnmp/libzbxsnmp.a \
	$(top_builddir)/src/libs/zbxvmware/libzbxvmware.a \
	$(top_builddir)/src/libs/zbxscripts/libzbxscripts.a \
	$(top_builddir)/src/libs/zbxodbc/libzbxodbc.a \
	$(top_builddir)/src/libs/zbxembed/libzbxembed.a \
	$(top_builddir)/src/libs/zbxdiscovery/libzbxdiscovery.a \
	$(top_builddir)/src/libs/zbxexport/libzbxexport.a \
	$(top_builddir)/src/libs/zbxsupervisor_client/libzbxsupervisor_client.a \
	$(top_builddir)/src/libs/zbxprometheus/libzbxprometheus.a \
	$(top_builddir)/src/libs/zbxcacheconfig/libzbxcacheconfig.a \
	$(top_builddir)/src/libs/zbxpgservice/libzbxpgservice.a \
	$(top_builddir)/src/libs/zbxcachehistory/libzbxcachehistory.a \
	$(top_builddir)/src/libs/zbxcachevalue/libzbxcachevalue.a \
	$(top_builddir)/src/libs/zbxevent/libzbxevent.a \
	$(top_builddir)/src/libs/zbxpreproc/libzbxpreproc.a \
	$(top_builddir)/src/libs/zbxpreprocbase/libzbxpreprocbase.a \
	$(top_builddir)/src/libs/zbxeval/libzbxeval.a \
	$(top_builddir)/src/libs/zbxserialize/libzbxserialize.a \
	$(top_builddir)/src/libs/zbxhistory/libzbxhistory.a \
	$(top_builddir)/src/libs/zbxshmem/libzbxshmem.a \
	$(top_builddir)/src/libs/zbxstats/libzbxstats.a \
	$(top_builddir)/src/libs/zbxself/libzbxself.a \
	$(top_builddir)/src/libs/zbxtimekeeper/libzbxtimekeeper.a \
	$(top_builddir)/src/libs/zbxescalations/libzbxescalations.a \
	$(top_builddir)/src/libs/zbxipcservice/libzbxipcservice.a \
	$(top_builddir)/src/libs/zbxxml/libzbxxml.a \
	$(top_builddir)/src/libs/zbxvault/libzbxvault.a \
	$(top_builddir)/src/libs/zbxkvs/libzbxkvs.a \
	$(top_builddir)/src/libs/zbxicmpping/libzbxicmpping.a \
	$(top_builddir)/src/libs/zbxdbupgrade/libzbxdbupgrade.a \
	$(top_builddir)/src/libs/zbxdbhigh/libzbxdbhigh.a \
	$(top_builddir)/src/libs/zbxdbwrap/libzbxdbwrap.a \
	$(top_builddir)/src/libs/zbxdb/libzbxdb.a \
	$(top_builddir)/src/libs/zbxdbschema/libzbxdbschema.a \
	$(top_builddir)/src/libs/zbxtagfilter/libzbxtagfilter.a \
	$(top_builddir)/src/libs/zbxtasks/libzbxtasks.a \
	$(top_builddir)/src/libs/zbxdiag/libzbxdiag.a \
	$(top_builddir)/src/libs/zbxtrends/libzbxtrends.a \
	$(top_builddir)/src/libs/zbxrtc/libzbxrtc_service.a \
	$(top_builddir)/src/libs/zbxrtc/libzbxrtc.a \
	$(top_builddir)/src/libs/zbxavailability/libzbxavailability.a \
	$(top_builddir)/src/libs/zbxconnector/libzbxconnector.a \
	$(top_builddir)/src/libs/zbxaudit/libzbxaudit.a \
	$(top_builddir)/src/libs/zbxversion/libzbxversion.a \
	$(top_builddir)/src/libs/zbxasyncpoller/libzbxasyncpoller.a \
	$(top_builddir)/src/libs/zbxasynchttppoller/libzbxasynchttppoller.a \
	$(top_builddir)/src/libs/zbxagentget/libzbxagentget.a \
	$(top_builddir)/src/libs/zbxbincommon/libzbxbincommon.a

# alerter,media and service should not be public libraries..
ZBX_SERVER_LIBS = \
	$(top_builddir)/src/libs/zbxsysinfo/libzbxserversysinfo.a \
	$(top_builddir)/src/libs/zbxalerter/libzbxalerter.a \
	$(top_builddir)/src/libs/zbxmedia/libzbxmedia.a \
	$(top_builddir)/src/libs/zbxservice/libzbxservice.a \
	$(top_builddir)/src/zabbix_server/audit/libzbxaudit_server.a \
	$(top_builddir)/src/zabbix_server/rtc/libzbxrtc_server.a \
	$(top_builddir)/src/zabbix_server/dbconfigworker/libdbconfigworker.a \
	$(top_builddir)/src/zabbix_server/preproc/libpreproc_server.a \
	$(top_builddir)/src/zabbix_server/poller/libzbxpoller_server.a \
	$(top_builddir)/src/zabbix_server/lld/libzbxlld.a \
	$(top_builddir)/src/zabbix_server/operations/libzbxoperations.a \
	$(top_builddir)/src/zabbix_server/stats/libzbxstats_server.a \
	$(top_builddir)/src/zabbix_server/ha/libzbxha.a \
	$(top_builddir)/src/zabbix_server/pgmanager/libzbxpgmanager.a \
	$(top_builddir)/src/zabbix_server/discovery/libzbxdiscovery_server.a \
	$(top_builddir)/src/zabbix_server/taskmanager/libzbxtaskmanager_server.a \
	$(top_builddir)/src/zabbix_server/connector/libconnector.a \
	$(top_builddir)/src/zabbix_server/service/libservice_server.a \
	$(top_builddir)/src/zabbix_server/escalator/libzbxescalator.a \
	$(top_builddir)/src/zabbix_server/proxypoller/libzbxproxypoller.a \
	$(top_builddir)/src/zabbix_server/proxyconfigread/libzbxproxyconfigread.a \
	$(top_builddir)/src/zabbix_server/reporter/libzbxreporter.a \
	$(top_builddir)/src/zabbix_server/autoreg/libzbxautoreg_server.a \
	$(top_builddir)/src/zabbix_server/trapper/libzbxtrapper_server.a \
	$(top_builddir)/src/zabbix_server/events/libzbxevents.a \
	$(top_builddir)/src/zabbix_server/actions/libzbxactions.a \
	$(top_builddir)/src/zabbix_server/housekeeper/libzbxhousekeeper_server.a \
	$(top_builddir)/src/zabbix_server/timer/libzbxtimer.a \
	$(top_builddir)/src/zabbix_server/dbconfig/libzbxdbconfig.a \
	$(top_builddir)/src/zabbix_server/diag/libzbxdiag_server.a \
	$(top_builddir)/src/zabbix_server/cachehistory/libzbxcachehistory_server.a \
	@SERVER_LIBS@

ZBX_PROXY_LIBS = \
	$(top_builddir)/src/libs/zbxsysinfo/libzbxproxysysinfo.a \
	$(top_builddir)/src/libs/zbxsysinfo/$(ARCH)/libspechostnamesysinfo.a \
	$(top_builddir)/src/libs/zbxproxybuffer/libzbxproxybuffer.a \
	$(top_builddir)/src/zabbix_proxy/taskmanager/libzbxtaskmanager_proxy.a \
	$(top_builddir)/src/zabbix_proxy/datasender/libzbxdatasender.a \
	$(top_builddir)/src/zabbix_proxy/proxyconfigwrite/libzbxproxyconfigwrite.a \
	$(top_builddir)/src/zabbix_proxy/preproc/libpreproc_proxy.a \
	$(top_builddir)/src/zabbix_proxy/trapper/libzbxtrapper_proxy.a \
	$(top_builddir)/src/zabbix_proxy/poller/libzbxpoller_proxy.a \
	$(top_builddir)/src/zabbix_proxy/housekeeper/libzbxhousekeeper_proxy.a \
	$(top_builddir)/src/zabbix_proxy/diag/libzbxdiag_proxy.a \
	$(top_builddir)/src/zabbix_proxy/proxyconfig/libzbxproxyconfig.a \
	$(top_builddir)/src/zabbix_proxy/cachehistory/libzbxcachehistory_proxy.a \
	$(top_builddir)/src/zabbix_proxy/stats/libzbxstats_proxy.a \
	$(top_builddir)/src/zabbix_proxy/autoreg/libzbxautoreg_proxy.a \
	$(top_builddir)/src/zabbix_proxy/discovery/libzbxdiscovery_proxy.a \
	$(top_builddir)/src/zabbix_proxy/rtc/libzbxrtc_proxy.a \
	@PROXY_LIBS@

ZBX_AGENT_LIBS = \
	$(top_builddir)/src/zabbix_agent/active_checks/libzbxactive_checks.a \
	$(top_builddir)/src/zabbix_agent/listener/libzbxlistener.a \
	$(top_builddir)/src/zabbix_agent/agent_conf/libagent_conf.a \
	$(top_builddir)/src/zabbix_agent/logfiles/libzbxlogfiles.a \
	$(top_builddir)/src/zabbix_agent/metrics/libzbxmetrics.a \
	$(top_builddir)/src/libs/zbxsysinfo/libzbxagentsysinfo.a \
	$(top_builddir)/src/libs/zbxsysinfo/$(ARCH)/libfunclistsysinfo.a \
	$(top_builddir)/src/libs/zbxsysinfo/$(ARCH)/libspechostnamesysinfo.a \
	$(top_builddir)/src/libs/zbxsysinfo/agent/libagentsysinfo.a \
	@AGENT_LIBS@


# libzbxipmi.a cannot be inside archive group since it contains server cache references
if HAVE_IPMI
ZBX_IPMI_LIB = $(top_builddir)/src/libs/zbxipmi/libzbxipmi.a
else
ZBX_IPMI_LIB =
endif

include $(top_srcdir)/tests/libs/grouped-libs.mk.inc

if SERVER
ANY_GROUPED_LIBS = $(SERVER_GROUPED_LIBS)
else
if PROXY
ANY_GROUPED_LIBS = $(PROXY_GROUPED_LIBS)
else
if AGENT
ANY_GROUPED_LIBS = $(AGENT_GROUPED_LIBS)
endif
endif
endif
