ALTER TABLE ONLY escalations ALTER actionid DROP DEFAULT;
ALTER TABLE ONLY escalations ALTER triggerid DROP DEFAULT;
ALTER TABLE ONLY escalations ALTER eventid DROP DEFAULT;
ALTER TABLE ONLY escalations ALTER r_eventid DROP DEFAULT;
ALTER TABLE ONLY escalations ALTER r_eventid DROP NOT NULL;
DELETE FROM escalations WHERE NOT actionid IN (SELECT actionid FROM actions);
DELETE FROM escalations WHERE NOT triggerid IN (SELECT triggerid FROM triggers);
DELETE FROM escalations WHERE NOT eventid IN (SELECT eventid FROM events);
UPDATE escalations SET r_eventid=NULL WHERE r_eventid=0;
DELETE FROM escalations WHERE NOT r_eventid IS NULL AND NOT r_eventid IN (SELECT eventid FROM events);
ALTER TABLE ONLY escalations ADD CONSTRAINT c_escalations_1 FOREIGN KEY (actionid) REFERENCES actions (actionid) ON DELETE CASCADE;
ALTER TABLE ONLY escalations ADD CONSTRAINT c_escalations_2 FOREIGN KEY (triggerid) REFERENCES triggers (triggerid) ON DELETE CASCADE;
ALTER TABLE ONLY escalations ADD CONSTRAINT c_escalations_3 FOREIGN KEY (eventid) REFERENCES events (eventid) ON DELETE CASCADE;
ALTER TABLE ONLY escalations ADD CONSTRAINT c_escalations_4 FOREIGN KEY (r_eventid) REFERENCES events (eventid) ON DELETE CASCADE;
