### Option: Plugins.Docker.Endpoint
#	Docker API endpoint.
#
# Mandatory: no
# Default: unix:///var/run/docker.sock
# Plugins.Docker.Endpoint=unix:///var/run/docker.sock

### Option: Plugins.Docker.Timeout
#   Legacy fallback timeout value. The maximum time (in seconds) for an item
#	check to be performed.
#   This value is only used for passive item checks coming from Zabbix server
#   versions older than 7.0. For newer versions, item check timeout can be
#   configured in the frontend.
#
# Mandatory: no
# Range: 1-30
# Default:
# Plugins.Docker.Timeout=<Global timeout>
