CREATE USER IF NOT EXISTS '${MYSQL_DB_USER}'@'%' IDENTIFIED BY '${MYSQL_DB_PASSWORD}';

GRANT REPLICATION CLIENT, PROCESS, SHOW DATABASES, SHOW VIEW ON *.* TO '${MYSQL_DB_USER}'@'%';
GRANT SLAVE MONITOR ON *.* TO 'zbx_monitor'@'%';
FLUSH PRIVILEGES;

STOP REPLICA;
CHANGE MASTER TO
	MASTER_HOST='mariadb-11.8-master',
	MASTER_USER='${MARIADB_REPLICATION_USER}',
	MASTER_PASSWORD='${MARIADB_REPLICATION_PASSWORD}',
	MASTER_PORT=${MYSQL_MASTER_PORT};
START REPLICA;
