<?php
return array(
	'slideshows' => array(
		'key' => 'slideshowid',
		'fields' => array(
			'slideshowid' => 'slideshowid',
			'name' => 'name',
			'delay' => 'delay',
		),
	),
	'slides' => array(
		'key' => 'slideid',
		'fields' => array(
			'slideid' => 'slideid',
			'slideshowid' => 'slideshowid',
			'screenid' => 'screenid',
			'step' => 'step',
			'delay' => 'delay',
		),
	),
	'drules' => array(
		'key' => 'druleid',
		'fields' => array(
			'druleid' => 'druleid',
			'proxy_hostid' => 'proxy_hostid',
			'name' => 'name',
			'iprange' => 'iprange',
			'delay' => 'delay',
			'nextcheck' => 'nextcheck',
			'status' => 'status',
			'unique_dcheckid' => 'unique_dcheckid',
		),
	),
	'dchecks' => array(
		'key' => 'dcheckid',
		'fields' => array(
			'dcheckid' => 'dcheckid',
			'druleid' => 'druleid',
			'type' => 'type',
			'key_' => 'key_',
			'snmp_community' => 'snmp_community',
			'ports' => 'ports',
			'snmpv' => 'snmpv',
			'snmpv' => 'snmpv',
			'snmpv' => 'snmpv',
			'snmpv' => 'snmpv',
		),
	),
	'dhosts' => array(
		'key' => 'dhostid',
		'fields' => array(
			'dhostid' => 'dhostid',
			'druleid' => 'druleid',
			'status' => 'status',
			'lastup' => 'lastup',
			'lastdown' => 'lastdown',
		),
	),
	'dservices' => array(
		'key' => 'dserviceid',
		'fields' => array(
			'dserviceid' => 'dserviceid',
			'dhostid' => 'dhostid',
			'type' => 'type',
			'key_' => 'key_',
			'value' => 'value',
			'port' => 'port',
			'status' => 'status',
			'lastup' => 'lastup',
			'lastdown' => 'lastdown',
			'dcheckid' => 'dcheckid',
			'ip' => 'ip',
			'nodeid' => 'nodeid',
			'table_name' => 'table_name',
			'field_name' => 'field_name',
			'nextid' => 'nextid',
		),
	),
	'httptest' => array(
		'key' => 'httptestid',
		'fields' => array(
			'httptestid' => 'httptestid',
			'name' => 'name',
			'applicationid' => 'applicationid',
			'lastcheck' => 'lastcheck',
			'nextcheck' => 'nextcheck',
			'curstate' => 'curstate',
			'curstep' => 'curstep',
			'lastfailedstep' => 'lastfailedstep',
			'delay' => 'delay',
			'status' => 'status',
			'macros' => 'macros',
			'agent' => 'agent',
			'time' => 'time',
			'error' => 'error',
			'authentication' => 'authentication',
			'http_user' => 'http_user',
			'http_password' => 'http_password',
		),
	),
	'httpstep' => array(
		'key' => 'httpstepid',
		'fields' => array(
			'httpstepid' => 'httpstepid',
			'httptestid' => 'httptestid',
			'name' => 'name',
			'no' => 'no',
			'url' => 'url',
			'timeout' => 'timeout',
			'posts' => 'posts',
			'required' => 'required',
			'status_codes' => 'status_codes',
		),
	),
	'httpstepitem' => array(
		'key' => 'httpstepitemid',
		'fields' => array(
			'httpstepitemid' => 'httpstepitemid',
			'httpstepid' => 'httpstepid',
			'itemid' => 'itemid',
			'type' => 'type',
		),
	),
	'httptestitem' => array(
		'key' => 'httptestitemid',
		'fields' => array(
			'httptestitemid' => 'httptestitemid',
			'httptestid' => 'httptestid',
			'itemid' => 'itemid',
			'type' => 'type',
		),
	),
	'nodes' => array(
		'key' => 'nodeid',
		'fields' => array(
			'nodeid' => 'nodeid',
			'name' => 'name',
			'timezone' => 'timezone',
			'ip' => 'ip',
			'port' => 'port',
			'slave_history' => 'slave_history',
			'slave_trends' => 'slave_trends',
			'nodetype' => 'nodetype',
			'masterid' => 'masterid',
			'nodeid' => 'nodeid',
			'tablename' => 'tablename',
			'recordid' => 'recordid',
			'cksumtype' => 'cksumtype',
			'cksum' => 'cksum',
			'sync' => 'sync',
		),
	),
	'services_times' => array(
		'key' => 'timeid',
		'fields' => array(
			'timeid' => 'timeid',
			'serviceid' => 'serviceid',
			'type' => 'type',
			'ts_from' => 'ts_from',
			'ts_to' => 'ts_to',
			'note' => 'note',
		),
	),
	'alerts' => array(
		'key' => 'alertid',
		'fields' => array(
			'alertid' => 'alertid',
			'actionid' => 'actionid',
			'eventid' => 'eventid',
			'userid' => 'userid',
			'clock' => 'clock',
			'mediatypeid' => 'mediatypeid',
			'sendto' => 'sendto',
			'subject' => 'subject',
			'message' => 'message',
			'status' => 'status',
			'retries' => 'retries',
			'error' => 'error',
			'nextcheck' => 'nextcheck',
			'esc_step' => 'esc_step',
			'alerttype' => 'alerttype',
			'itemid' => 'itemid',
			'clock' => 'clock',
			'value' => 'value',
		),
	),
	'history_sync' => array(
		'key' => 'id',
		'fields' => array(
			'id' => 'id',
			'nodeid' => 'nodeid',
			'itemid' => 'itemid',
			'clock' => 'clock',
			'value' => 'value',
			'itemid' => 'itemid',
			'clock' => 'clock',
			'value' => 'value',
		),
	),
	'history_uint_sync' => array(
		'key' => 'id',
		'fields' => array(
			'id' => 'id',
			'nodeid' => 'nodeid',
			'itemid' => 'itemid',
			'clock' => 'clock',
			'value' => 'value',
			'itemid' => 'itemid',
			'clock' => 'clock',
			'value' => 'value',
		),
	),
	'history_str_sync' => array(
		'key' => 'id',
		'fields' => array(
			'id' => 'id',
			'nodeid' => 'nodeid',
			'itemid' => 'itemid',
			'clock' => 'clock',
			'value' => 'value',
		),
	),
	'history_log' => array(
		'key' => 'id',
		'fields' => array(
			'id' => 'id',
			'itemid' => 'itemid',
			'clock' => 'clock',
			'timestamp' => 'timestamp',
			'source' => 'source',
			'severity' => 'severity',
			'value' => 'value',
			'logeventid' => 'logeventid',
		),
	),
	'history_text' => array(
		'key' => 'id',
		'fields' => array(
			'id' => 'id',
			'itemid' => 'itemid',
			'clock' => 'clock',
			'value' => 'value',
		),
	),
	'proxy_history' => array(
		'key' => 'id',
		'fields' => array(
			'id' => 'id',
			'itemid' => 'itemid',
			'clock' => 'clock',
			'timestamp' => 'timestamp',
			'source' => 'source',
			'severity' => 'severity',
			'value' => 'value',
			'logeventid' => 'logeventid',
		),
	),
	'proxy_dhistory' => array(
		'key' => 'id',
		'fields' => array(
			'id' => 'id',
			'clock' => 'clock',
			'druleid' => 'druleid',
			'type' => 'type',
			'ip' => 'ip',
			'port' => 'port',
			'key_' => 'key_',
			'value' => 'value',
			'status' => 'status',
			'dcheckid' => 'dcheckid',
		),
	),
	'events' => array(
		'key' => 'eventid',
		'fields' => array(
			'eventid' => 'eventid',
			'source' => 'source',
			'object' => 'object',
			'objectid' => 'objectid',
			'clock' => 'clock',
			'value' => 'value',
			'acknowledged' => 'acknowledged',
			'itemid' => 'itemid',
			'clock' => 'clock',
			'num' => 'num',
			'value_min' => 'value_min',
			'value_avg' => 'value_avg',
			'value_max' => 'value_max',
			'itemid' => 'itemid',
			'clock' => 'clock',
			'num' => 'num',
			'value_min' => 'value_min',
			'value_avg' => 'value_avg',
			'value_max' => 'value_max',
		),
	),
	'acknowledges' => array(
		'key' => 'acknowledgeid',
		'fields' => array(
			'acknowledgeid' => 'acknowledgeid',
			'userid' => 'userid',
			'eventid' => 'eventid',
			'clock' => 'clock',
			'message' => 'message',
		),
	),
	'auditlog' => array(
		'key' => 'auditid',
		'fields' => array(
			'auditid' => 'auditid',
			'userid' => 'userid',
			'clock' => 'clock',
			'action' => 'action',
			'resourcetype' => 'resourcetype',
			'details' => 'details',
			'ip' => 'ip',
			'resourceid' => 'resourceid',
			'resourcename' => 'resourcename',
		),
	),
	'auditlog_details' => array(
		'key' => 'auditdetailid',
		'fields' => array(
			'auditdetailid' => 'auditdetailid',
			'auditid' => 'auditid',
			'table_name' => 'table_name',
			'field_name' => 'field_name',
			'oldvalue' => 'oldvalue',
			'newvalue' => 'newvalue',
		),
	),
	'service_alarms' => array(
		'key' => 'servicealarmid',
		'fields' => array(
			'servicealarmid' => 'servicealarmid',
			'serviceid' => 'serviceid',
			'clock' => 'clock',
			'value' => 'value',
		),
	),
	'actions' => array(
		'key' => 'actionid',
		'fields' => array(
			'actionid' => 'actionid',
			'name' => 'name',
			'eventsource' => 'eventsource',
			'evaltype' => 'evaltype',
			'status' => 'status',
			'esc_period' => 'esc_period',
			'def_shortdata' => 'def_shortdata',
			'def_longdata' => 'def_longdata',
			'recovery_msg' => 'recovery_msg',
			'r_shortdata' => 'r_shortdata',
			'r_longdata' => 'r_longdata',
		),
	),
	'operations' => array(
		'key' => 'operationid',
		'fields' => array(
			'operationid' => 'operationid',
			'actionid' => 'actionid',
			'operationtype' => 'operationtype',
			'object' => 'object',
			'objectid' => 'objectid',
			'shortdata' => 'shortdata',
			'longdata' => 'longdata',
			'esc_period' => 'esc_period',
			'esc_step_from' => 'esc_step_from',
			'esc_step_to' => 'esc_step_to',
			'default_msg' => 'default_msg',
			'evaltype' => 'evaltype',
		),
	),
	'opconditions' => array(
		'key' => 'opconditionid',
		'fields' => array(
			'opconditionid' => 'opconditionid',
			'operationid' => 'operationid',
			'conditiontype' => 'conditiontype',
			'operator' => 'operator',
			'value' => 'value',
		),
	),
	'opmediatypes' => array(
		'key' => 'opmediatypeid',
		'fields' => array(
			'opmediatypeid' => 'opmediatypeid',
			'operationid' => 'operationid',
			'mediatypeid' => 'mediatypeid',
		),
	),
	'escalations' => array(
		'key' => 'escalationid',
		'fields' => array(
			'escalationid' => 'escalationid',
			'actionid' => 'actionid',
			'triggerid' => 'triggerid',
			'eventid' => 'eventid',
			'r_eventid' => 'r_eventid',
			'nextcheck' => 'nextcheck',
			'esc_step' => 'esc_step',
			'status' => 'status',
		),
	),
	'applications' => array(
		'key' => 'applicationid',
		'fields' => array(
			'applicationid' => 'applicationid',
			'hostid' => 'hostid',
			'name' => 'name',
			'templateid' => 'templateid',
		),
	),
	'conditions' => array(
		'key' => 'conditionid',
		'fields' => array(
			'conditionid' => 'conditionid',
			'actionid' => 'actionid',
			'conditiontype' => 'conditiontype',
			'operator' => 'operator',
			'value' => 'value',
		),
	),
	'config' => array(
		'key' => 'configid',
		'fields' => array(
			'configid' => 'configid',
			'alert_history' => 'alert_history',
			'event_history' => 'event_history',
			'refresh_unsupported' => 'refresh_unsupported',
			'work_period' => 'work_period',
			'alert_usrgrpid' => 'alert_usrgrpid',
			'event_ack_enable' => 'event_ack_enable',
			'event_expire' => 'event_expire',
			'event_show_max' => 'event_show_max',
			'default_theme' => 'default_theme',
			'authentication_type' => 'authentication_type',
			'ldap_host' => 'ldap_host',
			'ldap_port' => 'ldap_port',
			'ldap_base_dn' => 'ldap_base_dn',
			'ldap_bind_dn' => 'ldap_bind_dn',
			'ldap_bind_password' => 'ldap_bind_password',
			'ldap_search_attribute' => 'ldap_search_attribute',
			'dropdown_first_entry' => 'dropdown_first_entry',
			'dropdown_first_remember' => 'dropdown_first_remember',
			'discovery_groupid' => 'discovery_groupid',
			'max_in_table' => 'max_in_table',
			'search_limit' => 'search_limit',
		),
	),
	'functions' => array(
		'key' => 'functionid',
		'fields' => array(
			'functionid' => 'functionid',
			'itemid' => 'itemid',
			'triggerid' => 'triggerid',
			'lastvalue' => 'lastvalue',
			'function' => 'function',
			'parameter' => 'parameter',
		),
	),
	'graphs' => array(
		'key' => 'graphid',
		'fields' => array(
			'graphid' => 'graphid',
			'name' => 'name',
			'width' => 'width',
			'height' => 'height',
			'yaxismin' => 'yaxismin',
			'yaxismax' => 'yaxismax',
			'templateid' => 'templateid',
			'show_work_period' => 'show_work_period',
			'show_triggers' => 'show_triggers',
			'graphtype' => 'graphtype',
			'show_legend' => 'show_legend',
			'show_' => 'show_',
			'percent_left' => 'percent_left',
			'percent_right' => 'percent_right',
			'ymin_type' => 'ymin_type',
			'ymax_type' => 'ymax_type',
			'ymin_itemid' => 'ymin_itemid',
			'ymax_itemid' => 'ymax_itemid',
		),
	),
	'graphs_items' => array(
		'key' => 'gitemid',
		'fields' => array(
			'gitemid' => 'gitemid',
			'graphid' => 'graphid',
			'itemid' => 'itemid',
			'drawtype' => 'drawtype',
			'sortorder' => 'sortorder',
			'color' => 'color',
			'yaxisside' => 'yaxisside',
			'calc_fnc' => 'calc_fnc',
			'type' => 'type',
			'periods_cnt' => 'periods_cnt',
		),
	),
	'graph_theme' => array(
		'key' => 'graphthemeid',
		'fields' => array(
			'graphthemeid' => 'graphthemeid',
			'description' => 'description',
			'theme' => 'theme',
			'backgroundcolor' => 'backgroundcolor',
			'graphcolor' => 'graphcolor',
			'graphbordercolor' => 'graphbordercolor',
			'gridcolor' => 'gridcolor',
			'maingridcolor' => 'maingridcolor',
			'gridbordercolor' => 'gridbordercolor',
			'textcolor' => 'textcolor',
			'highlightcolor' => 'highlightcolor',
			'leftpercentilecolor' => 'leftpercentilecolor',
			'rightpercentilecolor' => 'rightpercentilecolor',
			'noneworktimecolor' => 'noneworktimecolor',
			'gridview' => 'gridview',
			'legendview' => 'legendview',
		),
	),
	'groups' => array(
		'key' => 'groupid',
		'fields' => array(
			'groupid' => 'groupid',
			'name' => 'name',
			'internal' => 'internal',
			'itemtype' => 'itemtype',
			'key_' => 'key_',
			'description' => 'description',
		),
	),
	'hosts' => array(
		'key' => 'hostid',
		'fields' => array(
			'hostid' => 'hostid',
			'proxy_hostid' => 'proxy_hostid',
			'host' => 'host',
			'dns' => 'dns',
			'useip' => 'useip',
			'ip' => 'ip',
			'port' => 'port',
			'status' => 'status',
			'disable_until' => 'disable_until',
			'error' => 'error',
			'available' => 'available',
			'errors_from' => 'errors_from',
			'lastaccess' => 'lastaccess',
			'inbytes' => 'inbytes',
			'outbytes' => 'outbytes',
			'useipmi' => 'useipmi',
			'ipmi_port' => 'ipmi_port',
			'ipmi_authtype' => 'ipmi_authtype',
			'ipmi_privilege' => 'ipmi_privilege',
			'ipmi_username' => 'ipmi_username',
			'ipmi_password' => 'ipmi_password',
			'ipmi_disable_until' => 'ipmi_disable_until',
			'ipmi_available' => 'ipmi_available',
			'snmp_disable_until' => 'snmp_disable_until',
			'snmp_available' => 'snmp_available',
			'maintenanceid' => 'maintenanceid',
			'maintenance_status' => 'maintenance_status',
			'maintenance_type' => 'maintenance_type',
			'maintenance_from' => 'maintenance_from',
			'ipmi_ip' => 'ipmi_ip',
			'ipmi_errors_from' => 'ipmi_errors_from',
			'snmp_errors_from' => 'snmp_errors_from',
			'ipmi_error' => 'ipmi_error',
			'snmp_error' => 'snmp_error',
		),
	),
	'globalmacro' => array(
		'key' => 'globalmacroid',
		'fields' => array(
			'globalmacroid' => 'globalmacroid',
			'macro' => 'macro',
			'value' => 'value',
		),
	),
	'hostmacro' => array(
		'key' => 'hostmacroid',
		'fields' => array(
			'hostmacroid' => 'hostmacroid',
			'hostid' => 'hostid',
			'macro' => 'macro',
			'value' => 'value',
		),
	),
	'hosts_groups' => array(
		'key' => 'hostgroupid',
		'fields' => array(
			'hostgroupid' => 'hostgroupid',
			'hostid' => 'hostid',
			'groupid' => 'groupid',
		),
	),
	'hosts_profiles' => array(
		'key' => 'hostid',
		'fields' => array(
			'hostid' => 'hostid',
			'devicetype' => 'devicetype',
			'name' => 'name',
			'os' => 'os',
			'serialno' => 'serialno',
			'tag' => 'tag',
			'macaddress' => 'macaddress',
			'hardware' => 'hardware',
			'software' => 'software',
			'contact' => 'contact',
			'location' => 'location',
			'notes' => 'notes',
		),
	),
	'hosts_profiles_ext' => array(
		'key' => 'hostid',
		'fields' => array(
			'hostid' => 'hostid',
			'device_alias' => 'device_alias',
			'device_type' => 'device_type',
			'device_chassis' => 'device_chassis',
			'device_os' => 'device_os',
			'device_os_short' => 'device_os_short',
			'device_hw_arch' => 'device_hw_arch',
			'device_serial' => 'device_serial',
			'device_model' => 'device_model',
			'device_tag' => 'device_tag',
			'device_vendor' => 'device_vendor',
			'device_contract' => 'device_contract',
			'device_who' => 'device_who',
			'device_status' => 'device_status',
			'device_app_' => 'device_app_',
			'device_app_' => 'device_app_',
			'device_app_' => 'device_app_',
			'device_app_' => 'device_app_',
			'device_app_' => 'device_app_',
			'device_url_' => 'device_url_',
			'device_url_' => 'device_url_',
			'device_url_' => 'device_url_',
			'device_networks' => 'device_networks',
			'device_notes' => 'device_notes',
			'device_hardware' => 'device_hardware',
			'device_software' => 'device_software',
			'ip_subnet_mask' => 'ip_subnet_mask',
			'ip_router' => 'ip_router',
			'ip_macaddress' => 'ip_macaddress',
			'oob_ip' => 'oob_ip',
			'oob_subnet_mask' => 'oob_subnet_mask',
			'oob_router' => 'oob_router',
			'date_hw_buy' => 'date_hw_buy',
			'date_hw_install' => 'date_hw_install',
			'date_hw_expiry' => 'date_hw_expiry',
			'date_hw_decomm' => 'date_hw_decomm',
			'site_street_' => 'site_street_',
			'site_street_' => 'site_street_',
			'site_street_' => 'site_street_',
			'site_city' => 'site_city',
			'site_state' => 'site_state',
			'site_country' => 'site_country',
			'site_zip' => 'site_zip',
			'site_rack' => 'site_rack',
			'site_notes' => 'site_notes',
			'poc_' => 'poc_',
			'poc_' => 'poc_',
			'poc_' => 'poc_',
			'poc_' => 'poc_',
			'poc_' => 'poc_',
			'poc_' => 'poc_',
			'poc_' => 'poc_',
			'poc_' => 'poc_',
			'poc_' => 'poc_',
			'poc_' => 'poc_',
			'poc_' => 'poc_',
			'poc_' => 'poc_',
			'poc_' => 'poc_',
			'poc_' => 'poc_',
		),
	),
	'hosts_templates' => array(
		'key' => 'hosttemplateid',
		'fields' => array(
			'hosttemplateid' => 'hosttemplateid',
			'hostid' => 'hostid',
			'templateid' => 'templateid',
		),
	),
	'housekeeper' => array(
		'key' => 'housekeeperid',
		'fields' => array(
			'housekeeperid' => 'housekeeperid',
			'tablename' => 'tablename',
			'field' => 'field',
			'value' => 'value',
		),
	),
	'images' => array(
		'key' => 'imageid',
		'fields' => array(
			'imageid' => 'imageid',
			'imagetype' => 'imagetype',
			'name' => 'name',
			'image' => 'image',
		),
	),
	'items' => array(
		'key' => 'itemid',
		'fields' => array(
			'itemid' => 'itemid',
			'type' => 'type',
			'snmp_community' => 'snmp_community',
			'snmp_oid' => 'snmp_oid',
			'snmp_port' => 'snmp_port',
			'hostid' => 'hostid',
			'description' => 'description',
			'key_' => 'key_',
			'delay' => 'delay',
			'history' => 'history',
			'trends' => 'trends',
			'lastvalue' => 'lastvalue',
			'lastclock' => 'lastclock',
			'prevvalue' => 'prevvalue',
			'status' => 'status',
			'value_type' => 'value_type',
			'trapper_hosts' => 'trapper_hosts',
			'units' => 'units',
			'multiplier' => 'multiplier',
			'delta' => 'delta',
			'prevorgvalue' => 'prevorgvalue',
			'snmpv' => 'snmpv',
			'snmpv' => 'snmpv',
			'snmpv' => 'snmpv',
			'snmpv' => 'snmpv',
			'formula' => 'formula',
			'error' => 'error',
			'lastlogsize' => 'lastlogsize',
			'logtimefmt' => 'logtimefmt',
			'templateid' => 'templateid',
			'valuemapid' => 'valuemapid',
			'delay_flex' => 'delay_flex',
			'params' => 'params',
			'ipmi_sensor' => 'ipmi_sensor',
			'data_type' => 'data_type',
			'authtype' => 'authtype',
			'username' => 'username',
			'password' => 'password',
			'publickey' => 'publickey',
			'privatekey' => 'privatekey',
			'mtime' => 'mtime',
		),
	),
	'items_applications' => array(
		'key' => 'itemappid',
		'fields' => array(
			'itemappid' => 'itemappid',
			'applicationid' => 'applicationid',
			'itemid' => 'itemid',
		),
	),
	'mappings' => array(
		'key' => 'mappingid',
		'fields' => array(
			'mappingid' => 'mappingid',
			'valuemapid' => 'valuemapid',
			'value' => 'value',
			'newvalue' => 'newvalue',
		),
	),
	'media' => array(
		'key' => 'mediaid',
		'fields' => array(
			'mediaid' => 'mediaid',
			'userid' => 'userid',
			'mediatypeid' => 'mediatypeid',
			'sendto' => 'sendto',
			'active' => 'active',
			'severity' => 'severity',
			'period' => 'period',
		),
	),
	'media_type' => array(
		'key' => 'mediatypeid',
		'fields' => array(
			'mediatypeid' => 'mediatypeid',
			'type' => 'type',
			'description' => 'description',
			'smtp_server' => 'smtp_server',
			'smtp_helo' => 'smtp_helo',
			'smtp_email' => 'smtp_email',
			'exec_path' => 'exec_path',
			'gsm_modem' => 'gsm_modem',
			'username' => 'username',
			'passwd' => 'passwd',
		),
	),
	'profiles' => array(
		'key' => 'profileid',
		'fields' => array(
			'profileid' => 'profileid',
			'userid' => 'userid',
			'idx' => 'idx',
			'idx' => 'idx',
			'value_id' => 'value_id',
			'value_int' => 'value_int',
			'value_str' => 'value_str',
			'source' => 'source',
			'type' => 'type',
		),
	),
	'rights' => array(
		'key' => 'rightid',
		'fields' => array(
			'rightid' => 'rightid',
			'groupid' => 'groupid',
			'permission' => 'permission',
			'id' => 'id',
		),
	),
	'scripts' => array(
		'key' => 'scriptid',
		'fields' => array(
			'scriptid' => 'scriptid',
			'name' => 'name',
			'command' => 'command',
			'host_access' => 'host_access',
			'usrgrpid' => 'usrgrpid',
			'groupid' => 'groupid',
		),
	),
	'screens' => array(
		'key' => 'screenid',
		'fields' => array(
			'screenid' => 'screenid',
			'name' => 'name',
			'hsize' => 'hsize',
			'vsize' => 'vsize',
		),
	),
	'screens_items' => array(
		'key' => 'screenitemid',
		'fields' => array(
			'screenitemid' => 'screenitemid',
			'screenid' => 'screenid',
			'resourcetype' => 'resourcetype',
			'resourceid' => 'resourceid',
			'width' => 'width',
			'height' => 'height',
			'x' => 'x',
			'y' => 'y',
			'colspan' => 'colspan',
			'rowspan' => 'rowspan',
			'elements' => 'elements',
			'valign' => 'valign',
			'halign' => 'halign',
			'style' => 'style',
			'url' => 'url',
			'dynamic' => 'dynamic',
		),
	),
	'services' => array(
		'key' => 'serviceid',
		'fields' => array(
			'serviceid' => 'serviceid',
			'name' => 'name',
			'status' => 'status',
			'algorithm' => 'algorithm',
			'triggerid' => 'triggerid',
			'showsla' => 'showsla',
			'goodsla' => 'goodsla',
			'sortorder' => 'sortorder',
		),
	),
	'services_links' => array(
		'key' => 'linkid',
		'fields' => array(
			'linkid' => 'linkid',
			'serviceupid' => 'serviceupid',
			'servicedownid' => 'servicedownid',
			'soft' => 'soft',
		),
	),
	'sessions' => array(
		'key' => 'sessionid',
		'fields' => array(
			'sessionid' => 'sessionid',
			'userid' => 'userid',
			'lastaccess' => 'lastaccess',
			'status' => 'status',
		),
	),
	'sysmaps_links' => array(
		'key' => 'linkid',
		'fields' => array(
			'linkid' => 'linkid',
			'sysmapid' => 'sysmapid',
			'selementid' => 'selementid',
			'selementid' => 'selementid',
			'drawtype' => 'drawtype',
			'color' => 'color',
			'label' => 'label',
		),
	),
	'sysmaps_link_triggers' => array(
		'key' => 'linktriggerid',
		'fields' => array(
			'linktriggerid' => 'linktriggerid',
			'linkid' => 'linkid',
			'triggerid' => 'triggerid',
			'drawtype' => 'drawtype',
			'color' => 'color',
		),
	),
	'sysmaps_elements' => array(
		'key' => 'selementid',
		'fields' => array(
			'selementid' => 'selementid',
			'sysmapid' => 'sysmapid',
			'elementid' => 'elementid',
			'elementtype' => 'elementtype',
			'iconid_off' => 'iconid_off',
			'iconid_on' => 'iconid_on',
			'iconid_unknown' => 'iconid_unknown',
			'label' => 'label',
			'label_location' => 'label_location',
			'x' => 'x',
			'y' => 'y',
			'url' => 'url',
			'iconid_disabled' => 'iconid_disabled',
			'iconid_maintenance' => 'iconid_maintenance',
		),
	),
	'sysmaps' => array(
		'key' => 'sysmapid',
		'fields' => array(
			'sysmapid' => 'sysmapid',
			'name' => 'name',
			'width' => 'width',
			'height' => 'height',
			'backgroundid' => 'backgroundid',
			'label_type' => 'label_type',
			'label_location' => 'label_location',
			'highlight' => 'highlight',
		),
	),
	'triggers' => array(
		'key' => 'triggerid',
		'fields' => array(
			'triggerid' => 'triggerid',
			'expression' => 'expression',
			'description' => 'description',
			'url' => 'url',
			'status' => 'status',
			'value' => 'value',
			'priority' => 'priority',
			'lastchange' => 'lastchange',
			'dep_level' => 'dep_level',
			'comments' => 'comments',
			'error' => 'error',
			'templateid' => 'templateid',
			'type' => 'type',
		),
	),
	'trigger_depends' => array(
		'key' => 'triggerdepid',
		'fields' => array(
			'triggerdepid' => 'triggerdepid',
			'triggerid_down' => 'triggerid_down',
			'triggerid_up' => 'triggerid_up',
		),
	),
	'users' => array(
		'key' => 'userid',
		'fields' => array(
			'userid' => 'userid',
			'alias' => 'alias',
			'name' => 'name',
			'surname' => 'surname',
			'passwd' => 'passwd',
			'url' => 'url',
			'autologin' => 'autologin',
			'autologout' => 'autologout',
			'lang' => 'lang',
			'refresh' => 'refresh',
			'type' => 'type',
			'theme' => 'theme',
			'attempt_failed' => 'attempt_failed',
			'attempt_ip' => 'attempt_ip',
			'attempt_clock' => 'attempt_clock',
			'rows_per_page' => 'rows_per_page',
		),
	),
	'usrgrp' => array(
		'key' => 'usrgrpid',
		'fields' => array(
			'usrgrpid' => 'usrgrpid',
			'name' => 'name',
			'gui_access' => 'gui_access',
			'users_status' => 'users_status',
			'api_access' => 'api_access',
			'debug_mode' => 'debug_mode',
		),
	),
	'users_groups' => array(
		'key' => 'id',
		'fields' => array(
			'id' => 'id',
			'usrgrpid' => 'usrgrpid',
			'userid' => 'userid',
		),
	),
	'valuemaps' => array(
		'key' => 'valuemapid',
		'fields' => array(
			'valuemapid' => 'valuemapid',
			'name' => 'name',
		),
	),
	'maintenances' => array(
		'key' => 'maintenanceid',
		'fields' => array(
			'maintenanceid' => 'maintenanceid',
			'name' => 'name',
			'maintenance_type' => 'maintenance_type',
			'description' => 'description',
			'active_since' => 'active_since',
			'active_till' => 'active_till',
		),
	),
	'maintenances_hosts' => array(
		'key' => 'maintenance_hostid',
		'fields' => array(
			'maintenance_hostid' => 'maintenance_hostid',
			'maintenanceid' => 'maintenanceid',
			'hostid' => 'hostid',
		),
	),
	'maintenances_groups' => array(
		'key' => 'maintenance_groupid',
		'fields' => array(
			'maintenance_groupid' => 'maintenance_groupid',
			'maintenanceid' => 'maintenanceid',
			'groupid' => 'groupid',
		),
	),
	'maintenances_windows' => array(
		'key' => 'maintenance_timeperiodid',
		'fields' => array(
			'maintenance_timeperiodid' => 'maintenance_timeperiodid',
			'maintenanceid' => 'maintenanceid',
			'timeperiodid' => 'timeperiodid',
		),
	),
	'timeperiods' => array(
		'key' => 'timeperiodid',
		'fields' => array(
			'timeperiodid' => 'timeperiodid',
			'timeperiod_type' => 'timeperiod_type',
			'every' => 'every',
			'month' => 'month',
			'dayofweek' => 'dayofweek',
			'day' => 'day',
			'start_time' => 'start_time',
			'period' => 'period',
			'start_date' => 'start_date',
		),
	),
	'regexps' => array(
		'key' => 'regexpid',
		'fields' => array(
			'regexpid' => 'regexpid',
			'name' => 'name',
			'test_string' => 'test_string',
		),
	),
	'user_history' => array(
		'key' => 'userhistoryid',
		'fields' => array(
			'userhistoryid' => 'userhistoryid',
			'userid' => 'userid',
			'title' => 'title',
			'url' => 'url',
			'title' => 'title',
			'url' => 'url',
			'title' => 'title',
			'url' => 'url',
			'title' => 'title',
			'url' => 'url',
			'title' => 'title',
			'url' => 'url',
		),
	),
	'expressions' => array(
		'key' => 'expressionid',
		'fields' => array(
			'expressionid' => 'expressionid',
			'regexpid' => 'regexpid',
			'expression' => 'expression',
			'expression_type' => 'expression_type',
			'exp_delimiter' => 'exp_delimiter',
			'case_sensitive' => 'case_sensitive',
		),
	),
	'autoreg_host' => array(
		'key' => 'autoreg_hostid',
		'fields' => array(
			'autoreg_hostid' => 'autoreg_hostid',
			'proxy_hostid' => 'proxy_hostid',
			'host' => 'host',
		),
	),
	'proxy_autoreg_host' => array(
		'key' => 'id',
		'fields' => array(
			'id' => 'id',
			'clock' => 'clock',
			'host' => 'host',
		),
	),
);
?>