ALTER TABLE history_text ALTER COLUMN id SET WITH DEFAULT NULL;
ALTER TABLE history_text ALTER COLUMN itemid SET WITH DEFAULT NULL;
ALTER TABLE history_text ADD ns integer SET WITH DEFAULT '0' NOT NULL;
