CREATE USER IF NOT EXISTS '${MYSQL_DB_USER}'@'%' IDENTIFIED BY '${MYSQL_DB_PASSWORD}';
GRANT REPLICATION CLIENT, PROCESS, SHOW DATABASES, SHOW VIEW ON *.* TO '${MYSQL_DB_USER}'@'%';
CHANGE REPLICATION SOURCE TO
	SOURCE_HOST='mysql-8.3-master',
	SOURCE_USER='${MYSQL_DB_USER}',
	SOURCE_PASSWORD='${MYSQL_DB_PASSWORD}',
	SOURCE_PORT=${MYSQL_MASTER_PORT};
