CREATE TABLE items (
	itemid		int(4) NOT NULL auto_increment,
	type		int(4) DEFAULT '0' NOT NULL,
	snmp_community	varchar(64) DEFAULT '' NOT NULL,
	snmp_oid	varchar(255) DEFAULT '' NOT NULL,
	snmp_port	int(4) DEFAULT '161' NOT NULL,
	hostid		int(4) NOT NULL,
	description	varchar(255) DEFAULT '' NOT NULL,
	key_		varchar(64) DEFAULT '' NOT NULL,
	delay		int(4) DEFAULT '0' NOT NULL,
	history		int(4) DEFAULT '90' NOT NULL,
	trends		int(4) DEFAULT '365' NOT NULL,
-- lastdelete is not longer required
--	lastdelete	int(4) DEFAULT '0' NOT NULL,
	nextcheck	int(4) DEFAULT '0' NOT NULL,
	lastvalue	varchar(255) DEFAULT NULL,
	lastclock	int(4) DEFAULT NULL,
	prevvalue	varchar(255) DEFAULT NULL,
	status		int(4) DEFAULT '0' NOT NULL,
	value_type	int(4) DEFAULT '0' NOT NULL,
	trapper_hosts	varchar(255) DEFAULT '' NOT NULL,
	units		varchar(10)	DEFAULT '' NOT NULL,
	multiplier	int(4)	DEFAULT '0' NOT NULL,
	delta		int(1)  DEFAULT '0' NOT NULL,
	prevorgvalue	double(16,4)  DEFAULT NULL,
	snmpv3_securityname	varchar(64) DEFAULT '' NOT NULL,
	snmpv3_securitylevel	int(1) DEFAULT '0' NOT NULL,
	snmpv3_authpassphrase	varchar(64) DEFAULT '' NOT NULL,
	snmpv3_privpassphrase	varchar(64) DEFAULT '' NOT NULL,

	formula		varchar(255) DEFAULT '0' NOT NULL,
	error		varchar(128) DEFAULT '' NOT NULL,

	lastlogsize	int(4) DEFAULT '0' NOT NULL,
	logtimefmt	varchar(64) DEFAULT '' NOT NULL,
	templateid	int(4) DEFAULT '0' NOT NULL,
	valuemapid	int(4) DEFAULT '0' NOT NULL,

	PRIMARY KEY	(itemid),
	UNIQUE		shortname (hostid,key_),
--	KEY		(hostid),
	KEY		(nextcheck),
	KEY		(status)
) type=InnoDB;
