<<<<<<< .working
<?php
/*
** ZABBIX
** Copyright (C) 2000-2010 SIA Zabbix
**
** This program is free software; you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation; either version 2 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program; if not, write to the Free Software
** Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
**/
?>
<?php
require_once 'PHPUnit/Framework.php';

require_once(dirname(__FILE__).'/../../../include/locales/en_gb.inc.php');
require_once(dirname(__FILE__).'/../../../include/locales.inc.php');
process_locales();
require_once(dirname(__FILE__).'/../../../include/defines.inc.php');
require_once(dirname(__FILE__).'/../../../include/validate.inc.php');
require_once(dirname(__FILE__).'/../../../include/func.inc.php');
require_once(dirname(__FILE__).'/../../../include/items.inc.php');
require_once(dirname(__FILE__).'/../../../include/triggers.inc.php');
require_once(dirname(__FILE__).'/../../../api/classes/class.ctriggerexpression.php');

class class_triggerexpressionTest extends PHPUnit_Framework_TestCase
{
	public static function provider()
	{
		return array(
	// Correct trigger expressions
			array('',false),
			array('+',false),
			array('1',false),
			array('1+1',false),
			array('abc',false),
			array('{TRIGGER.VALUE}',false),
			array('{$USERMACRO}',false),
			array('{TRIGGER.VALUE}=1',false),
			array('{$USERMACRO}=1',false),
			array('{host}',false),
			array('{host:key}',false),
			array('{host:key.str}',false),

			array('{host:key.str()} & {TRIGGER.VALUE}',true),
			array('{host:key.str()}& {TRIGGER.VALUE}',true),
			array('{host:key.str()}  &{TRIGGER.VALUE}',true),
			array('{host:key.str()}&{TRIGGER.VALUE}',true),
			array('{host:key.str()}&+{TRIGGER.VALUE}',false),
			array('{host:key.str()}&-{TRIGGER.VALUE}',true),
			array('{host:key.str()} & + {TRIGGER.VALUE}',false),
			array('{host:key.str()} & - {TRIGGER.VALUE}',true),

			array('{host:key.str()} & {$USERMACRO}',true),
			array('{host:key.str()}& {$USERMACRO}',true),
			array('{host:key.str()} &{$USERMACRO}',true),
			array('{host:key.str()}&{$USERMACRO}',true),
			array('{host:key.str()} & + {$USERMACRO}',false),
			array('{host:key.str()} & - {$USERMACRO}',true),

			array('{host:key.str()}=00',true),
			array('{host:key.str()}=0 0',false),
			array('{host:key.str()}=0 0={host:key.str()}',false),
			array('{host:key.str()} = 00 = {host:key.str()}',true),

			array('{host:key.str(ГУГЛ)}=0',true),
			array('{host:key.str("ГУГЛ")}=0',true),
			array('{host:key[ГУГЛ].str(ГУГЛ)}=0',true),
			array('{host:key["ГУГЛ"].str("ГУГЛ")}=0',true),
			array('{host:key.str("こんにちは、世界")}',true),
			array('{host:key.str(こんにちは、世界)}',true),
			array('{host:key["こんにちは、世界"].str("こんにちは、世界")}',true),
			array('{host:key[こんにちは、世界].str(こんにちは、世界)}',true),

			array('{host:key[a,,"b",,[c,d,,"e",],,[f]].str(a,,b,"c",d,)}',true),
			array('{host:key[a,,"b",,[[c,d,,"e"],[]],,[f]].str(a,,b,"c",d,)}',true),
			array('{host:key[a,,"b",,[c,d,,"e",,,[f]].str(a,,b,"c",d,)}',false),
			array('{host:key[a,,"b",,[c,d,,"e",],,f]].str(a,,b,"c",d,)}',false),

			array('{abcdefghijklmnopqrstuvwxyz. _-ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890:key.str()}',true),
			array('{host:abcdefghijklmnopqrstuvwxyz.,_-ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890.str()}',true),
			array('{host:.str()}',false),
			array('{:key.str()}',false),
			array('{host:key.()}',false),

			array(' {host:key.str()} ',true),
			array('({host:key.str()})',true),
			array('{(host:key.str()})',false),
			array('({host:key.str())}',false),
			array('{(host:key.str())}',false),
			array('{(host:key.str()})=0',false),
			array('({host:key.str())}=0',false),
			array('{(host:key.str())}=0',false),
			array('({host:key.str()}=)0',false),
			array('({host:key.str()})0',false),
			array('0(={host:key.str()})',false),
			array('0({host:key.str()})',false),
			array('( {host:key.str()} )',true),
			array(' ( {host:key.str()} ) ',true),
			array('(( {host:key.str()} ))',true),
			array(' ( ( {host:key.str()} ) ) ',true),
			array('((( {host:key.str()} )))',true),
			array(' ( ( ( {host:key.str()} ) ) ) ',true),
			array('()0={host:key.str()}',false),
			array('0()={host:key.str()}',false),
			array('0=()={host:key.str()}',false),
			array('0=(){host:key.str()}',false),
			array('0={()host:key.str()}',false),
			array('0={host:key.str()()}',false),
			array('0={host:key.str()}()',false),
			array('0={host:key.str()}+()()()()5',false),
			array('0={host:key.str()}+((((()))))5',false),
			array('(0)={host:key.str()}',true),
			array('(0+)={host:key.str()}',false),
			array('(0=){host:key.str()}',false),
			array('({host:key.str)()}',false),
			array('({host:key.)str()}',false),
			array('({host:key).str()}',false),
			array('(-5)={host:key.str()}',true),
			array('(15 - 5.25 - 1)={host:key.str()}',true),
			array('{host:key.str()} = -5',true),

			array('(({host:key.str()})=0)',true),
			array('( ( {host:key.str()} ) = 0 )',true),
			array('(({host:key.str()}) * 100) / 95',true),
			array('(({host:key.str()}) * 5.25K) / 95.0',true),
			array('(({host:key.str()}) * 1w) / 1d',true),
			array('(({host:key.str()}) * 1w) / 1Ks',false),
			array('(({host:key.str()}) * 1w) / (1d * ({host:key.str()})',false),
			array('(({host:key.str()}) * 1w) / (1d * host:key.str()}))',false),
			array('(({host:key.str()}) * 1w) / (1d * ({host:key.str()}))',true),

			array('{host:key.last(1)} * (-1)',true),
			array('{host:key.last(1)} / (-1)',true),
			array('{host:key.last(1)} + (-1)',true),
			array('{host:key.last(1)} - (-1)',true),
			array('{host:key.last(1)} = (-1)',true),
			array('{host:key.last(1)} # (-1)',true),
			array('{host:key.last(1)} < (-1)',true),
			array('{host:key.last(1)} > (-1)',true),
			array('{host:key.last(1)} & (-1)',true),
			array('{host:key.last(1)} | (-1)',true),

			array('{host:key.last(1)}* (-1)',true),
			array('{host:key.last(1)}/ (-1)',true),
			array('{host:key.last(1)}+ (-1)',true),
			array('{host:key.last(1)}- (-1)',true),
			array('{host:key.last(1)}= (-1)',true),
			array('{host:key.last(1)}# (-1)',true),
			array('{host:key.last(1)}< (-1)',true),
			array('{host:key.last(1)}> (-1)',true),
			array('{host:key.last(1)}& (-1)',true),
			array('{host:key.last(1)}| (-1)',true),

			array('{host:key.last(1)} *(-1)',true),
			array('{host:key.last(1)} /(-1)',true),
			array('{host:key.last(1)} +(-1)',true),
			array('{host:key.last(1)} -(-1)',true),
			array('{host:key.last(1)} =(-1)',true),
			array('{host:key.last(1)} #(-1)',true),
			array('{host:key.last(1)} <(-1)',true),
			array('{host:key.last(1)} >(-1)',true),
			array('{host:key.last(1)} &(-1)',true),
			array('{host:key.last(1)} |(-1)',true),

			array('{host:key.last(1)}*(-1)',true),
			array('{host:key.last(1)}/(-1)',true),
			array('{host:key.last(1)}+(-1)',true),
			array('{host:key.last(1)}-(-1)',true),
			array('{host:key.last(1)}=(-1)',true),
			array('{host:key.last(1)}#(-1)',true),
			array('{host:key.last(1)}<(-1)',true),
			array('{host:key.last(1)}>(-1)',true),
			array('{host:key.last(1)}&(-1)',true),
			array('{host:key.last(1)}|(-1)',true),

			array('{host:key.last(1)} * -1',true),
			array('{host:key.last(1)} / -1',true),
			array('{host:key.last(1)} + -1',true),
			array('{host:key.last(1)} - -1',true),
			array('{host:key.last(1)} = -1',true),
			array('{host:key.last(1)} # -1',true),
			array('{host:key.last(1)} < -1',true),
			array('{host:key.last(1)} > -1',true),
			array('{host:key.last(1)} & -1',true),
			array('{host:key.last(1)} | -1',true),

			array('{host:key.last(1)}* -1',true),
			array('{host:key.last(1)}/ -1',true),
			array('{host:key.last(1)}+ -1',true),
			array('{host:key.last(1)}- -1',true),
			array('{host:key.last(1)}= -1',true),
			array('{host:key.last(1)}# -1',true),
			array('{host:key.last(1)}< -1',true),
			array('{host:key.last(1)}> -1',true),
			array('{host:key.last(1)}& -1',true),
			array('{host:key.last(1)}| -1',true),

			array('{host:key.last(1)} *-1',true),
			array('{host:key.last(1)} /-1',true),
			array('{host:key.last(1)} +-1',true),
			array('{host:key.last(1)} --1',true),
			array('{host:key.last(1)} =-1',true),
			array('{host:key.last(1)} #-1',true),
			array('{host:key.last(1)} <-1',true),
			array('{host:key.last(1)} >-1',true),
			array('{host:key.last(1)} &-1',true),
			array('{host:key.last(1)} |-1',true),

			array('{host:key.last(1)}*-1',true),
			array('{host:key.last(1)}/-1',true),
			array('{host:key.last(1)}+-1',true),
			array('{host:key.last(1)}--1',true),
			array('{host:key.last(1)}=-1',true),
			array('{host:key.last(1)}#-1',true),
			array('{host:key.last(1)}<-1',true),
			array('{host:key.last(1)}>-1',true),
			array('{host:key.last(1)}&-1',true),
			array('{host:key.last(1)}|-1',true),

			array('{host:key.last(1)} * (- 1)',true),
			array('{host:key.last(1)} / (- 1)',true),
			array('{host:key.last(1)} + (- 1)',true),
			array('{host:key.last(1)} - (- 1)',true),
			array('{host:key.last(1)} = (- 1)',true),
			array('{host:key.last(1)} # (- 1)',true),
			array('{host:key.last(1)} < (- 1)',true),
			array('{host:key.last(1)} > (- 1)',true),
			array('{host:key.last(1)} & (- 1)',true),
			array('{host:key.last(1)} | (- 1)',true),

			array('{host:key.last(1)}* (- 1)',true),
			array('{host:key.last(1)}/ (- 1)',true),
			array('{host:key.last(1)}+ (- 1)',true),
			array('{host:key.last(1)}- (- 1)',true),
			array('{host:key.last(1)}= (- 1)',true),
			array('{host:key.last(1)}# (- 1)',true),
			array('{host:key.last(1)}< (- 1)',true),
			array('{host:key.last(1)}> (- 1)',true),
			array('{host:key.last(1)}& (- 1)',true),
			array('{host:key.last(1)}| (- 1)',true),

			array('{host:key.last(1)} *(- 1)',true),
			array('{host:key.last(1)} /(- 1)',true),
			array('{host:key.last(1)} +(- 1)',true),
			array('{host:key.last(1)} -(- 1)',true),
			array('{host:key.last(1)} =(- 1)',true),
			array('{host:key.last(1)} #(- 1)',true),
			array('{host:key.last(1)} <(- 1)',true),
			array('{host:key.last(1)} >(- 1)',true),
			array('{host:key.last(1)} &(- 1)',true),
			array('{host:key.last(1)} |(- 1)',true),

			array('{host:key.last(1)}*(- 1)',true),
			array('{host:key.last(1)}/(- 1)',true),
			array('{host:key.last(1)}+(- 1)',true),
			array('{host:key.last(1)}-(- 1)',true),
			array('{host:key.last(1)}=(- 1)',true),
			array('{host:key.last(1)}#(- 1)',true),
			array('{host:key.last(1)}<(- 1)',true),
			array('{host:key.last(1)}>(- 1)',true),
			array('{host:key.last(1)}&(- 1)',true),
			array('{host:key.last(1)}|(- 1)',true),

			array('{host:key.last(1)} * - 1',true),
			array('{host:key.last(1)} / - 1',true),
			array('{host:key.last(1)} + - 1',true),
			array('{host:key.last(1)} - - 1',true),
			array('{host:key.last(1)} = - 1',true),
			array('{host:key.last(1)} # - 1',true),
			array('{host:key.last(1)} < - 1',true),
			array('{host:key.last(1)} > - 1',true),
			array('{host:key.last(1)} & - 1',true),
			array('{host:key.last(1)} | - 1',true),

			array('{host:key.last(1)}* - 1',true),
			array('{host:key.last(1)}/ - 1',true),
			array('{host:key.last(1)}+ - 1',true),
			array('{host:key.last(1)}- - 1',true),
			array('{host:key.last(1)}= - 1',true),
			array('{host:key.last(1)}# - 1',true),
			array('{host:key.last(1)}< - 1',true),
			array('{host:key.last(1)}> - 1',true),
			array('{host:key.last(1)}& - 1',true),
			array('{host:key.last(1)}| - 1',true),

			array('{host:key.last(1)} *- 1',true),
			array('{host:key.last(1)} /- 1',true),
			array('{host:key.last(1)} +- 1',true),
			array('{host:key.last(1)} -- 1',true),
			array('{host:key.last(1)} =- 1',true),
			array('{host:key.last(1)} #- 1',true),
			array('{host:key.last(1)} <- 1',true),
			array('{host:key.last(1)} >- 1',true),
			array('{host:key.last(1)} &- 1',true),
			array('{host:key.last(1)} |- 1',true),

			array('{host:key.last(1)}*- 1',true),
			array('{host:key.last(1)}/- 1',true),
			array('{host:key.last(1)}+- 1',true),
			array('{host:key.last(1)}-- 1',true),
			array('{host:key.last(1)}=- 1',true),
			array('{host:key.last(1)}#- 1',true),
			array('{host:key.last(1)}<- 1',true),
			array('{host:key.last(1)}>- 1',true),
			array('{host:key.last(1)}&- 1',true),
			array('{host:key.last(1)}|- 1',true),

			array('{host:key.last(1)} * (+1)',false),
			array('{host:key.last(1)} / (+1)',false),
			array('{host:key.last(1)} + (+1)',false),
			array('{host:key.last(1)} - (+1)',false),
			array('{host:key.last(1)} = (+1)',false),
			array('{host:key.last(1)} # (+1)',false),
			array('{host:key.last(1)} < (+1)',false),
			array('{host:key.last(1)} > (+1)',false),
			array('{host:key.last(1)} & (+1)',false),
			array('{host:key.last(1)} | (+1)',false),

			array('{host:key.last(1)}* (+1)',false),
			array('{host:key.last(1)}/ (+1)',false),
			array('{host:key.last(1)}+ (+1)',false),
			array('{host:key.last(1)}- (+1)',false),
			array('{host:key.last(1)}= (+1)',false),
			array('{host:key.last(1)}# (+1)',false),
			array('{host:key.last(1)}< (+1)',false),
			array('{host:key.last(1)}> (+1)',false),
			array('{host:key.last(1)}& (+1)',false),
			array('{host:key.last(1)}| (+1)',false),

			array('{host:key.last(1)} *(+1)',false),
			array('{host:key.last(1)} /(+1)',false),
			array('{host:key.last(1)} +(+1)',false),
			array('{host:key.last(1)} -(+1)',false),
			array('{host:key.last(1)} =(+1)',false),
			array('{host:key.last(1)} #(+1)',false),
			array('{host:key.last(1)} <(+1)',false),
			array('{host:key.last(1)} >(+1)',false),
			array('{host:key.last(1)} &(+1)',false),
			array('{host:key.last(1)} |(+1)',false),

			array('{host:key.last(1)}*(+1)',false),
			array('{host:key.last(1)}/(+1)',false),
			array('{host:key.last(1)}+(+1)',false),
			array('{host:key.last(1)}-(+1)',false),
			array('{host:key.last(1)}=(+1)',false),
			array('{host:key.last(1)}#(+1)',false),
			array('{host:key.last(1)}<(+1)',false),
			array('{host:key.last(1)}>(+1)',false),
			array('{host:key.last(1)}&(+1)',false),
			array('{host:key.last(1)}|(+1)',false),

			array('{host:key.last(1)} * +1',false),
			array('{host:key.last(1)} / +1',false),
			array('{host:key.last(1)} + +1',false),
			array('{host:key.last(1)} - +1',false),
			array('{host:key.last(1)} = +1',false),
			array('{host:key.last(1)} # +1',false),
			array('{host:key.last(1)} < +1',false),
			array('{host:key.last(1)} > +1',false),
			array('{host:key.last(1)} & +1',false),
			array('{host:key.last(1)} | +1',false),

			array('{host:key.last(1)}* +1',false),
			array('{host:key.last(1)}/ +1',false),
			array('{host:key.last(1)}+ +1',false),
			array('{host:key.last(1)}- +1',false),
			array('{host:key.last(1)}= +1',false),
			array('{host:key.last(1)}# +1',false),
			array('{host:key.last(1)}< +1',false),
			array('{host:key.last(1)}> +1',false),
			array('{host:key.last(1)}& +1',false),
			array('{host:key.last(1)}| +1',false),

			array('{host:key.last(1)} *+1',false),
			array('{host:key.last(1)} /+1',false),
			array('{host:key.last(1)} ++1',false),
			array('{host:key.last(1)} -+1',false),
			array('{host:key.last(1)} =+1',false),
			array('{host:key.last(1)} #+1',false),
			array('{host:key.last(1)} <+1',false),
			array('{host:key.last(1)} >+1',false),
			array('{host:key.last(1)} &+1',false),
			array('{host:key.last(1)} |+1',false),

			array('{host:key.last(1)}*+1',false),
			array('{host:key.last(1)}/+1',false),
			array('{host:key.last(1)}++1',false),
			array('{host:key.last(1)}-+1',false),
			array('{host:key.last(1)}=+1',false),
			array('{host:key.last(1)}#+1',false),
			array('{host:key.last(1)}<+1',false),
			array('{host:key.last(1)}>+1',false),
			array('{host:key.last(1)}&+1',false),
			array('{host:key.last(1)}|+1',false),

			array('{host:key.last(1)} * (+ 1)',false),
			array('{host:key.last(1)} / (+ 1)',false),
			array('{host:key.last(1)} + (+ 1)',false),
			array('{host:key.last(1)} - (+ 1)',false),
			array('{host:key.last(1)} = (+ 1)',false),
			array('{host:key.last(1)} # (+ 1)',false),
			array('{host:key.last(1)} < (+ 1)',false),
			array('{host:key.last(1)} > (+ 1)',false),
			array('{host:key.last(1)} & (+ 1)',false),
			array('{host:key.last(1)} | (+ 1)',false),

			array('{host:key.last(1)}* (+ 1)',false),
			array('{host:key.last(1)}/ (+ 1)',false),
			array('{host:key.last(1)}+ (+ 1)',false),
			array('{host:key.last(1)}- (+ 1)',false),
			array('{host:key.last(1)}= (+ 1)',false),
			array('{host:key.last(1)}# (+ 1)',false),
			array('{host:key.last(1)}< (+ 1)',false),
			array('{host:key.last(1)}> (+ 1)',false),
			array('{host:key.last(1)}& (+ 1)',false),
			array('{host:key.last(1)}| (+ 1)',false),

			array('{host:key.last(1)} *(+ 1)',false),
			array('{host:key.last(1)} /(+ 1)',false),
			array('{host:key.last(1)} +(+ 1)',false),
			array('{host:key.last(1)} -(+ 1)',false),
			array('{host:key.last(1)} =(+ 1)',false),
			array('{host:key.last(1)} #(+ 1)',false),
			array('{host:key.last(1)} <(+ 1)',false),
			array('{host:key.last(1)} >(+ 1)',false),
			array('{host:key.last(1)} &(+ 1)',false),
			array('{host:key.last(1)} |(+ 1)',false),

			array('{host:key.last(1)}*(+ 1)',false),
			array('{host:key.last(1)}/(+ 1)',false),
			array('{host:key.last(1)}+(+ 1)',false),
			array('{host:key.last(1)}-(+ 1)',false),
			array('{host:key.last(1)}=(+ 1)',false),
			array('{host:key.last(1)}#(+ 1)',false),
			array('{host:key.last(1)}<(+ 1)',false),
			array('{host:key.last(1)}>(+ 1)',false),
			array('{host:key.last(1)}&(+ 1)',false),
			array('{host:key.last(1)}|(+ 1)',false),

			array('{host:key.last(1)} * + 1',false),
			array('{host:key.last(1)} / + 1',false),
			array('{host:key.last(1)} + + 1',false),
			array('{host:key.last(1)} - + 1',false),
			array('{host:key.last(1)} = + 1',false),
			array('{host:key.last(1)} # + 1',false),
			array('{host:key.last(1)} < + 1',false),
			array('{host:key.last(1)} > + 1',false),
			array('{host:key.last(1)} & + 1',false),
			array('{host:key.last(1)} | + 1',false),

			array('{host:key.last(1)}* + 1',false),
			array('{host:key.last(1)}/ + 1',false),
			array('{host:key.last(1)}+ + 1',false),
			array('{host:key.last(1)}- + 1',false),
			array('{host:key.last(1)}= + 1',false),
			array('{host:key.last(1)}# + 1',false),
			array('{host:key.last(1)}< + 1',false),
			array('{host:key.last(1)}> + 1',false),
			array('{host:key.last(1)}& + 1',false),
			array('{host:key.last(1)}| + 1',false),

			array('{host:key.last(1)} *+ 1',false),
			array('{host:key.last(1)} /+ 1',false),
			array('{host:key.last(1)} ++ 1',false),
			array('{host:key.last(1)} -+ 1',false),
			array('{host:key.last(1)} =+ 1',false),
			array('{host:key.last(1)} #+ 1',false),
			array('{host:key.last(1)} <+ 1',false),
			array('{host:key.last(1)} >+ 1',false),
			array('{host:key.last(1)} &+ 1',false),
			array('{host:key.last(1)} |+ 1',false),

			array('{host:key.last(1)}*+ 1',false),
			array('{host:key.last(1)}/+ 1',false),
			array('{host:key.last(1)}++ 1',false),
			array('{host:key.last(1)}-+ 1',false),
			array('{host:key.last(1)}=+ 1',false),
			array('{host:key.last(1)}#+ 1',false),
			array('{host:key.last(1)}<+ 1',false),
			array('{host:key.last(1)}>+ 1',false),
			array('{host:key.last(1)}&+ 1',false),
			array('{host:key.last(1)}|+ 1',false),

			array('{host:key.str()} + 1',true),
			array('{host:key.str()} - 1',true),
			array('{host:key.str()} / 1',true),
			array('{host:key.str()} * 1',true),
			array('{host:key.str()} = 1',true),
			array('{host:key.str()} # 1',true),
			array('{host:key.str()} & 1',true),
			array('{host:key.str()} | 1',true),

			array('{host:key.str()}+ 1',true),
			array('{host:key.str()}- 1',true),
			array('{host:key.str()}/ 1',true),
			array('{host:key.str()}* 1',true),
			array('{host:key.str()}= 1',true),
			array('{host:key.str()}# 1',true),
			array('{host:key.str()}& 1',true),
			array('{host:key.str()}| 1',true),

			array('{host:key.str()} +1',true),
			array('{host:key.str()} -1',true),
			array('{host:key.str()} /1',true),
			array('{host:key.str()} *1',true),
			array('{host:key.str()} =1',true),
			array('{host:key.str()} #1',true),
			array('{host:key.str()} &1',true),
			array('{host:key.str()} |1',true),

			array('{host:key.str()}+1',true),
			array('{host:key.str()}-1',true),
			array('{host:key.str()}/1',true),
			array('{host:key.str()}*1',true),
			array('{host:key.str()}=1',true),
			array('{host:key.str()}#1',true),
			array('{host:key.str()}&1',true),
			array('{host:key.str()}|1',true),

			array('{host:key.str()}=1K',true),
			array('{host:key.str()}=1M',true),
			array('{host:key.str()}=1G',true),
			array('{host:key.str()}=1T',true),
			array('{host:key.str()}=1s',true),
			array('{host:key.str()}=1m',true),
			array('{host:key.str()}=1h',true),
			array('{host:key.str()}=1d',true),
			array('{host:key.str()}=1w',true),

			array('{host:key.str()}=1.56K',true),
			array('{host:key.str()}=1.56M',true),
			array('{host:key.str()}=1.56G',true),
			array('{host:key.str()}=1.56T',true),
			array('{host:key.str()}=1.56s',true),
			array('{host:key.str()}=1.56m',true),
			array('{host:key.str()}=1.56h',true),
			array('{host:key.str()}=1.56d',true),
			array('{host:key.str()}=1.56w',true),

			array('{host:key.str()} + 1.173640',true),
			array('{host:key.str()} - 1.173640',true),
			array('{host:key.str()} / 1.173640',true),
			array('{host:key.str()} * 1.173640',true),
			array('{host:key.str()} = 1.173640',true),
			array('{host:key.str()} # 1.173640',true),
			array('{host:key.str()} & 1.173640',true),
			array('{host:key.str()} | 1.173640',true),

			array('{host:key.str()}+ 1.173640',true),
			array('{host:key.str()}- 1.173640',true),
			array('{host:key.str()}/ 1.173640',true),
			array('{host:key.str()}* 1.173640',true),
			array('{host:key.str()}= 1.173640',true),
			array('{host:key.str()}# 1.173640',true),
			array('{host:key.str()}& 1.173640',true),
			array('{host:key.str()}| 1.173640',true),

			array('{host:key.str()} +1.173640',true),
			array('{host:key.str()} -1.173640',true),
			array('{host:key.str()} /1.173640',true),
			array('{host:key.str()} *1.173640',true),
			array('{host:key.str()} =1.173640',true),
			array('{host:key.str()} #1.173640',true),
			array('{host:key.str()} &1.173640',true),
			array('{host:key.str()} |1.173640',true),

			array('{host:key.str()}+1.173640',true),
			array('{host:key.str()}-1.173640',true),
			array('{host:key.str()}/1.173640',true),
			array('{host:key.str()}*1.173640',true),
			array('{host:key.str()}=1.173640',true),
			array('{host:key.str()}#1.173640',true),
			array('{host:key.str()}&1.173640',true),
			array('{host:key.str()}|1.173640',true),

			array('{host:key.str()} + 1 | {host:key.str()}',true),
			array('{host:key.str()} - 1 & {host:key.str()}',true),
			array('{host:key.str()} / 1 # {host:key.str()}',true),
			array('{host:key.str()} * 1 = {host:key.str()}',true),
			array('{host:key.str()} = 1 * {host:key.str()}',true),
			array('{host:key.str()} # 1 / {host:key.str()}',true),
			array('{host:key.str()} & 1 - {host:key.str()}',true),
			array('{host:key.str()} | 1 + {host:key.str()}',true),

			array('{host:key.str()} -- 1',true),
			array('{host:key.str()} ++ 1',false),
			array('{host:key.str()} // 1',false),
			array('{host:key.str()} ** 1',false),
			array('{host:key.str()} == 1',false),
			array('{host:key.str()} ## 1',false),
			array('{host:key.str()} && 1',false),
			array('{host:key.str()} || 1',false),

			array('{host:key.str()} +',false),
			array('{host:key.str()} -',false),
			array('{host:key.str()} /',false),
			array('{host:key.str()} *',false),
			array('{host:key.str()} =',false),
			array('{host:key.str()} #',false),
			array('{host:key.str()} &',false),
			array('{host:key.str()} |',false),

			array('- {host:key.str()}',true),
			array('+ {host:key.str()}',false),
			array('/ {host:key.str()}',false),
			array('* {host:key.str()}',false),
			array('= {host:key.str()}',false),
			array('# {host:key.str()}',false),
			array('& {host:key.str()}',false),
			array('| {host:key.str()}',false),

			array('{host:key.str()}=0',true),
			array('{host:key.str(,)}=0',true),
			array('{host:key.str( ,)}=0',true),
			array('{host:key.str(  ,)}=0',true),
			array('{host:key.str(, )}=0',true),
			array('{host:key.str(,  )}=0',true),

			array('{host:key.str(")}=0',false),
			array('{host:key.str("")}=0',true),
			array('{host:key.str(""")}=0',false),
			array('{host:key.str("""")}=0',false),

			array('{host:key.str( ")}=0',false),
			array('{host:key.str( "")}=0',true),
			array('{host:key.str( """)}=0',false),
			array('{host:key.str( """")}=0',false),

			array('{host:key.str(  ")}=0',false),
			array('{host:key.str(  "")}=0',true),
			array('{host:key.str(  """)}=0',false),
			array('{host:key.str(  """")}=0',false),

			array('{host:key.str(,")}=0',false),
			array('{host:key.str(,"")}=0',true),
			array('{host:key.str(,""")}=0',false),
			array('{host:key.str(,"""")}=0',false),

			array('{host:key.str(, ")}=0',false),
			array('{host:key.str(, "")}=0',true),
			array('{host:key.str(, """)}=0',false),
			array('{host:key.str(, """")}=0',false),

			array('{host:key.str(,  ")}=0',false),
			array('{host:key.str(,  "")}=0',true),
			array('{host:key.str(,  """)}=0',false),
			array('{host:key.str(,  """")}=0',false),

			array('{host:key.str("",")}=0',false),
			array('{host:key.str("","")}=0',true),
			array('{host:key.str("",""")}=0',false),
			array('{host:key.str("","""")}=0',false),

			array('{host:key.str("", ")}=0',false),
			array('{host:key.str("", "")}=0',true),
			array('{host:key.str("", """)}=0',false),
			array('{host:key.str("", """")}=0',false),

			array('{host:key.str("",  ")}=0',false),
			array('{host:key.str("",  "")}=0',true),
			array('{host:key.str("",  """)}=0',false),
			array('{host:key.str("",  """")}=0',false),

			array('{host:key.str("\")}=0',false),
			array('{host:key.str("\"")}=0',true),
			array('{host:key.str("\\"")}=0',true),
			array('{host:key.str("\""")}=0',false),
			array('{host:key.str("\"""")}=0',false),

			array('{host:key.str(\")}=0',true),
			array('{host:key.str(param\")}=0',true),
			array('{host:key.str(param")}=0',true),

			array('{host:key.str( \")}=0',true),
			array('{host:key.str( param\")}=0',true),
			array('{host:key.str( param")}=0',true),

			array('{host:key.str(  \")}=0',true),
			array('{host:key.str(  param\")}=0',true),
			array('{host:key.str(  param")}=0',true),

			array('{host:key.str(()}=0',true),
			array('{host:key.str(param()}=0',true),

			array('{host:key.str( ()}=0',true),
			array('{host:key.str( param()}=0',true),

			array('{host:key.str(  ()}=0',true),
			array('{host:key.str(  param()}=0',true),

			array('{host:key.str())}=0',false),
			array('{host:key.str(param))}=0',false),

			array('{host:key.str( ))}=0',false),
			array('{host:key.str( param))}=0',false),

			array('{host:key.str(  ))}=0',false),
			array('{host:key.str(  param))}=0',false),

			array('{host:key.str("(")}=0',true),
			array('{host:key.str("param(")}=0',true),

			array('{host:key.str(")")}=0',true),
			array('{host:key.str("param)")}=0',true),

			array('{host:key.str()}=0',true),
			array('{host:key.str( )}=0',true),
			array('{host:key.str(" ")}=0',true),
			array('{host:key.str(abc)}=0',true),
			array('{host:key.str(\'abc\')}=0',true),
			array('{host:key.str("")}=0',true),
			array('{host:key.last(0)}=0',true),
			array('{host:key.str(aaa()}=0',true),

			array('{host:key.last(0)}=0',true),
			array('{host:key.str(aaa()}=0',true),
			array('({hostA:keyA.str("abc")}=0) | ({hostB:keyB.last(123)}=0)',true),
			array('{host:key[asd[].str(aaa()}=0',true),
			array('{host:key["param].str()"].str()}=0',true),
			array('{host:key[param].str()].str()}',false),
			array('{host:key[asd[,asd[,[]].str(aaa()}=0',true),
			array('{host:key[[],[],[]].str([],[],[])}=0',true),
			array('({hostA:keyA.str("abc")}) / ({hostB:keyB.last(123)})=(0)',true),
			array('({hostA:keyA.str("abc")}=0) | ({hostB:keyB.last(123)}=0)',true),
			array('({hostA:keyA.str("abc")}=0) & ({hostB:keyB.last(123)}=0)',true),
	// Incorrect trigger expressions
			array('{hostkey.last(0)}=0',false),
			array('{host:keylast(0)}=0',false),
			array('{host:key.last(0}=0',false),
			array('{host:key.last(0)}=',false),
			array('{host:key.str()=0',false),
			array('{host:key.last()}#0}',false),
			array('{host:key.incorrect()}=0',false),
			array('{host:key.str()}<>0',false),
			array('({host:key.str(aaa()}=0',false),
			array('(({host:key.str(aaa()}=0)',false),
			array('{host:key.str(aaa()}=0)',false),
			array('({hostA:keyA.str("abc")}=0) || ({hostB:keyB.last(123)}=0)',false),
			array('{host:key.last()}<>0',false),
			array('{hostA:keyA.str("abc")} / ({hostB:keyB.last(123)}=0',false),
			array('({hostA:keyA.str("abc")} / ({hostB:keyB.last(123)})=0',false),
	// by Aleksandrs
			array('{expression}', false),
			array('{expre ssion}', false),
			array('host:key.str()', false),
			array('{host:key.str()', false),
			array('host:key.str()}', false),
			array(' {host:key.str()}', true),
			array('{host:key.str()} ', true),
			array('{host :key.str()}', true),
			array('{host:key.str(-5)}', true),
			array('{host:key.str(+5)}', true),
			array('{host:key.str([-5)}', true),
			array('{host:key.str(-5])}', true),
			array('{host:key.str((-5)}', true),
			array('{host:key.str(-5))}', false),
			array('{host:key.str(-5)*1}', false),
			array('0={host:key["a"b].str()}', false),
			array('0={host:key[].str(a"b"c)}', true),
			array('0={host:key[].str("a\"b\"c")}', true),
			array('0={host:key[].str("a\\"b\\"c")}', true),
			array('0={host:key[].str("a"b)}', false),
			array('0={host:key[].str(,"a"b,)}', false),
			array('0={host:key[].str("","a"b,"")}', false),
			array('0={host:key.str)', false),
			array('1z={host:key.str()', false),
			array('1z={host:key.str()}', false),
			array('0={host:key[].str(")}', false),
			array('0={host:key[].str( ")}', false),
			array('0={host:key[].str(")}")}', true),
			array('0={host:key[].str( ")}")}', true),
			array('({host1:key1.last()}/{host2:key2.last(+5)})/10+2*{TRIGGER.VALUE}&{$USERMACRO1}+(-{$USERMACRO2})+-{$USERMACRO3}*-12K+12.5m', true),
			array('-12+{TRIGGER.VALUE}/(({host1:key1[].last(5)}+(5*(1-(-3*5&((7|9))#1)*{host2:key2[""].last(123)})/10/10/10)+{$USERMACRO1})-{$USERMACRO2})', true),
			array('{host:key[{$USERMACRO1},"{$USERMACRO2}"].str()}', true),
			array('{host:key[].str({$USERMACRO1},"{$USERMACRO2}")}', true),
			array('{host:key[{HOSTNAME1},"{HOSTNAME2}"].str()}', true),
			array('{host:key[].str({HOSTNAME1},"{HOSTNAME2}")}', true),
			array('{host:key[].str()}=-1=--2=---3=----4=-----5', false),
			array('{host:key[].str()}=-1=--2=---3=----4=-----5', false),
	// by Aleksandrs (January 6, 2011)
			array('{host:key[].str()}=-1', true),
			array('{host:key[].str()}+-1', true),
			array('{host:key[].str()}--1', true),
			array('{host:key[].str()}-(-1)', true),
			array('{host:key[].str()}-(-(-(-1)))', false),
			array('{host:key[{$$$},"{$$$}"].str()}', true),
			array('{host:key[{!!!},"{!!!}"].str()}', true),
			array('{host:key[{$USERMACRO1,"{$USERMACRO"].str()}', true),
			array('{host:key[].str({$USERMACRO1,"{$USERMACRO")}', true),
			array('{host:key[{$USERMACRO1}abc,"{$USERMACRO2}"].str()}', true),
			array('{host:key[{$USERMACRO1},"{$USERMACRO2}abc"].str()}', true),
			array('{host:key[].str({$USERMACRO1}abc,"{$USERMACRO2}")}', true),
			array('{host:key[].str({$USERMACRO1},"{$USERMACRO2}abc")}', true),
			array('{host:key[abc{HOSTNAME1},"{HOSTNAME2}"].str()}', true),
			array('{host:key[{HOSTNAME1},"abc{HOSTNAME2}"].str()}', true),
			array('{host:key[].str(abc{HOSTNAME1},"{HOSTNAME2}")}', true),
			array('{host:key[].str({HOSTNAME1},"abc{HOSTNAME2}")}', true),
			array('{host:key[{host:key.last(0)},"{host:key.last(0)}"].str()}', true),
			array('{host:key[].str({host:key.last(0)},"{host:key.last(0)}")}', false),
			array('{host:key[].str({host:key.last(0},"{host:key.last(0)}")}', true),
			array('{host:key[].str({host:key.last(0)}+{host:key.last(0)}', true),
			array('{host:key[].str({host:key.last(0)}', true),
			array('{host:key[{host:key[].last(0)},"{host:key[].last(0)}"].str()}', false),
			array('{host:key["{host:key[].last(0)}",{host:key[].last(0)}].str()}', false),
			array('{host:key["{host:key[].last(0)}",{host:key[].last(0)}', true),
			array('{host:key[{host:key[].last(0)}+{host:key[].last(0)}', true),
			array('{host:key[{host:key[].last(0)}', true),
	// by Alexei (January 7, 2011)
			array('(({host:key.last(0)}+1.)) + + (({host:key.last(0)}+1.))',false),
			array('(({host:key.last(0)}+1.)) + - (({host:key.last(0)}+1.))',false),
			array('(({host:key.last(0)}+1.)) + (({host:key.last(0)}+1.))',false),
			array('(({host:key.last(0)}+1.))',false),
			array('(--({host:key.last(0)}+1.))',false),
			array('(+({host:key.last(0)}+1.))',false),
			array('(/({host:key.last(0)}+1.))',false),
			array('({host:key.last(0)}+1.)/({host:key.last(0)}+1.)',false),
			array('({host:key.last(0)}+1.)-({host:key.last(0)}+1.)',false),
			array('({host:key.last(0)}+1.)+({host:key.last(0)}+1.)',false),
			array('({host:key.last(0)}+1.)|({host:key.last(0)}+1.)',false),
			array('({host:key.last(0)}+1.)&({host:key.last(0)}+1.)',false),
			array('({host:key.last(0)}+1.)&({host:key.last(0)}+1.)/({host:key.last(0)}+1.)',false),
			array('({host:key.last(0)}+1.)+({host:key.last(0)}+1.)/({host:key.last(0)}+1.)',false),
			array('1 - (1/({host:key.last(0)}+1.))+(({host:key.last(0)}+1.))/({host:key.last(0)}+1.)/({host:key.last(0)}+1.)',false),
			array('(({host:key.last(0)}+.1)) + + (({host:key.last(0)}+.1))',false),
			array('(({host:key.last(0)}+.1)) + - (({host:key.last(0)}+.1))',false),
			array('(({host:key.last(0)}+.1)) + (({host:key.last(0)}+.1))',false),
			array('(({host:key.last(0)}+.1))',false),
			array('(--({host:key.last(0)}+.1))',false),
			array('(+({host:key.last(0)}+.1))',false),
			array('(/({host:key.last(0)}+.1))',false),
			array('({host:key.last(0)}+.1)/({host:key.last(0)}+.1)',false),
			array('({host:key.last(0)}+.1)-({host:key.last(0)}+.1)',false),
			array('({host:key.last(0)}+.1)+({host:key.last(0)}+.1)',false),
			array('({host:key.last(0)}+.1)|({host:key.last(0)}+.1)',false),
			array('({host:key.last(0)}+.1)&({host:key.last(0)}+.1)',false),
			array('({host:key.last(0)}+.1)&({host:key.last(0)}+.1)/({host:key.last(0)}+.1)',false),
			array('({host:key.last(0)}+.1)+({host:key.last(0)}+.1)/({host:key.last(0)}+.1)',false),
			array('1 - (1/({host:key.last(0)}+.1))+(({host:key.last(0)}+.1))/({host:key.last(0)}+.1)/({host:key.last(0)}+.1)',false),
			array('(({host:key.last(0)}+0 .1)) + + (({host:key.last(0)}+0 .1))',false),
			array('(({host:key.last(0)}+0 .1)) + - (({host:key.last(0)}+0 .1))',false),
			array('(({host:key.last(0)}+0 .1)) + (({host:key.last(0)}+0 .1))',false),
			array('(({host:key.last(0)}+0 .1))',false),
			array('(--({host:key.last(0)}+0 .1))',false),
			array('(+({host:key.last(0)}+0 .1))',false),
			array('(/({host:key.last(0)}+0 .1))',false),
			array('({host:key.last(0)}+0 .1)/({host:key.last(0)}+0 .1)',false),
			array('({host:key.last(0)}+0 .1)-({host:key.last(0)}+0 .1)',false),
			array('({host:key.last(0)}+0 .1)+({host:key.last(0)}+0 .1)',false),
			array('({host:key.last(0)}+0 .1)|({host:key.last(0)}+0 .1)',false),
			array('({host:key.last(0)}+0 .1)&({host:key.last(0)}+0 .1)',false),
			array('({host:key.last(0)}+0 .1)&({host:key.last(0)}+0 .1)/({host:key.last(0)}+0 .1)',false),
			array('({host:key.last(0)}+0 .1)+({host:key.last(0)}+0 .1)/({host:key.last(0)}+0 .1)',false),
			array('1 - (1/({host:key.last(0)}+0 .1))+(({host:key.last(0)}+0 .1))/({host:key.last(0)}+0 .1)/({host:key.last(0)}+0 .1)',false),
			array('(({host:key.last(0)}+1 K)) + + (({host:key.last(0)}+1 K))',false),
			array('(({host:key.last(0)}+1 K)) + - (({host:key.last(0)}+1 K))',false),
			array('(({host:key.last(0)}+1 K)) + (({host:key.last(0)}+1 K))',false),
			array('(({host:key.last(0)}+1 K))',false),
			array('(--({host:key.last(0)}+1 K))',false),
			array('(+({host:key.last(0)}+1 K))',false),
			array('(/({host:key.last(0)}+1 K))',false),
			array('({host:key.last(0)}+1 K)/({host:key.last(0)}+1 K)',false),
			array('({host:key.last(0)}+1 K)-({host:key.last(0)}+1 K)',false),
			array('({host:key.last(0)}+1 K)+({host:key.last(0)}+1 K)',false),
			array('({host:key.last(0)}+1 K)|({host:key.last(0)}+1 K)',false),
			array('({host:key.last(0)}+1 K)&({host:key.last(0)}+1 K)',false),
			array('({host:key.last(0)}+1 K)&({host:key.last(0)}+1 K)/({host:key.last(0)}+1 K)',false),
			array('({host:key.last(0)}+1 K)+({host:key.last(0)}+1 K)/({host:key.last(0)}+1 K)',false),
			array('1 - (1/({host:key.last(0)}+1 K))+(({host:key.last(0)}+1 K))/({host:key.last(0)}+1 K)/({host:key.last(0)}+1 K)',false),
			array('(({host:key.last(0)}+.)) + + (({host:key.last(0)}+.))',false),
			array('(({host:key.last(0)}+.)) + - (({host:key.last(0)}+.))',false),
			array('(({host:key.last(0)}+.)) + (({host:key.last(0)}+.))',false),
			array('(({host:key.last(0)}+.))',false),
			array('(--({host:key.last(0)}+.))',false),
			array('(+({host:key.last(0)}+.))',false),
			array('(/({host:key.last(0)}+.))',false),
			array('({host:key.last(0)}+.)/({host:key.last(0)}+.)',false),
			array('({host:key.last(0)}+.)-({host:key.last(0)}+.)',false),
			array('({host:key.last(0)}+.)+({host:key.last(0)}+.)',false),
			array('({host:key.last(0)}+.)|({host:key.last(0)}+.)',false),
			array('({host:key.last(0)}+.)&({host:key.last(0)}+.)',false),
			array('({host:key.last(0)}+.)&({host:key.last(0)}+.)/({host:key.last(0)}+.)',false),
			array('({host:key.last(0)}+.)+({host:key.last(0)}+.)/({host:key.last(0)}+.)',false),
			array('1 - (1/({host:key.last(0)}+.))+(({host:key.last(0)}+.))/({host:key.last(0)}+.)/({host:key.last(0)}+.)',false),
			array('(({host:key.last(0)}+.K)) + + (({host:key.last(0)}+.K))',false),
			array('(({host:key.last(0)}+.K)) + - (({host:key.last(0)}+.K))',false),
			array('(({host:key.last(0)}+.K)) + (({host:key.last(0)}+.K))',false),
			array('(({host:key.last(0)}+.K))',false),
			array('(--({host:key.last(0)}+.K))',false),
			array('(+({host:key.last(0)}+.K))',false),
			array('(/({host:key.last(0)}+.K))',false),
			array('({host:key.last(0)}+.K)/({host:key.last(0)}+.K)',false),
			array('({host:key.last(0)}+.K)-({host:key.last(0)}+.K)',false),
			array('({host:key.last(0)}+.K)+({host:key.last(0)}+.K)',false),
			array('({host:key.last(0)}+.K)|({host:key.last(0)}+.K)',false),
			array('({host:key.last(0)}+.K)&({host:key.last(0)}+.K)',false),
			array('({host:key.last(0)}+.K)&({host:key.last(0)}+.K)/({host:key.last(0)}+.K)',false),
			array('({host:key.last(0)}+.K)+({host:key.last(0)}+.K)/({host:key.last(0)}+.K)',false),
			array('1 - (1/({host:key.last(0)}+.K))+(({host:key.last(0)}+.K))/({host:key.last(0)}+.K)/({host:key.last(0)}+.K)',false),
			array('(({host:key.last(0)}+K)) + + (({host:key.last(0)}+K))',false),
			array('(({host:key.last(0)}+K)) + - (({host:key.last(0)}+K))',false),
			array('(({host:key.last(0)}+K)) + (({host:key.last(0)}+K))',false),
			array('(({host:key.last(0)}+K))',false),
			array('(--({host:key.last(0)}+K))',false),
			array('(+({host:key.last(0)}+K))',false),
			array('(/({host:key.last(0)}+K))',false),
			array('({host:key.last(0)}+K)/({host:key.last(0)}+K)',false),
			array('({host:key.last(0)}+K)-({host:key.last(0)}+K)',false),
			array('({host:key.last(0)}+K)+({host:key.last(0)}+K)',false),
			array('({host:key.last(0)}+K)|({host:key.last(0)}+K)',false),
			array('({host:key.last(0)}+K)&({host:key.last(0)}+K)',false),
			array('({host:key.last(0)}+K)&({host:key.last(0)}+K)/({host:key.last(0)}+K)',false),
			array('({host:key.last(0)}+K)+({host:key.last(0)}+K)/({host:key.last(0)}+K)',false),
			array('1 - (1/({host:key.last(0)}+K))+(({host:key.last(0)}+K))/({host:key.last(0)}+K)/({host:key.last(0)}+K)',false),
			array('({host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}) + + ({host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")})',false),
			array('({host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}) + - ({host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")})',false),
			array('({host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}) + ({host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")})',true),
			array('({host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")})',true),
			array('(--{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")})',false),
			array('(+{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")})',false),
			array('(/{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")})',false),
			array('{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}/{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}',true),
			array('{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}-{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}',true),
			array('{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}+{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}',true),
			array('{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}|{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}',true),
			array('{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}&{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}',true),
			array('{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}&{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}/{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}',true),
			array('{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}+{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}/{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}',true),
			array('1 - (1/{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")})+({host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")})/{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}/{host:key.last(--1)}+(1/2+2*2-3|4)|23-34>{host:key.last(--1")}',true),
			array('({host:key.last(0)}+(1/2+2*2-3|4)|23-34) + + ({host:key.last(0)}+(1/2+2*2-3|4)|23-34)',false),
			array('({host:key.last(0)}+(1/2+2*2-3|4)|23-34) + - ({host:key.last(0)}+(1/2+2*2-3|4)|23-34)',false),
			array('({host:key.last(0)}+(1/2+2*2-3|4)|23-34) + ({host:key.last(0)}+(1/2+2*2-3|4)|23-34)',true),
			array('({host:key.last(0)}+(1/2+2*2-3|4)|23-34)',true),
			array('(--{host:key.last(0)}+(1/2+2*2-3|4)|23-34)',false),
			array('(+{host:key.last(0)}+(1/2+2*2-3|4)|23-34)',false),
			array('(/{host:key.last(0)}+(1/2+2*2-3|4)|23-34)',false),
			array('{host:key.last(0)}+(1/2+2*2-3|4)|23-34/{host:key.last(0)}+(1/2+2*2-3|4)|23-34',true),
			array('{host:key.last(0)}+(1/2+2*2-3|4)|23-34-{host:key.last(0)}+(1/2+2*2-3|4)|23-34',true),
			array('{host:key.last(0)}+(1/2+2*2-3|4)|23-34+{host:key.last(0)}+(1/2+2*2-3|4)|23-34',true),
			array('{host:key.last(0)}+(1/2+2*2-3|4)|23-34|{host:key.last(0)}+(1/2+2*2-3|4)|23-34',true),
			array('{host:key.last(0)}+(1/2+2*2-3|4)|23-34&{host:key.last(0)}+(1/2+2*2-3|4)|23-34',true),
			array('{host:key.last(0)}+(1/2+2*2-3|4)|23-34&{host:key.last(0)}+(1/2+2*2-3|4)|23-34/{host:key.last(0)}+(1/2+2*2-3|4)|23-34',true),
			array('{host:key.last(0)}+(1/2+2*2-3|4)|23-34+{host:key.last(0)}+(1/2+2*2-3|4)|23-34/{host:key.last(0)}+(1/2+2*2-3|4)|23-34',true),
			array('1 - (1/{host:key.last(0)}+(1/2+2*2-3|4)|23-34)+({host:key.last(0)}+(1/2+2*2-3|4)|23-34)/{host:key.last(0)}+(1/2+2*2-3|4)|23-34/{host:key.last(0)}+(1/2+2*2-3|4)|23-34',true),
			array('({host:key.{a}}) + + ({host:key.{a}})',false),
			array('({host:key.{a}}) + - ({host:key.{a}})',false),
			array('({host:key.{a}}) + ({host:key.{a}})',false),
			array('({host:key.{a}})',false),
			array('(--{host:key.{a}})',false),
			array('(+{host:key.{a}})',false),
			array('(/{host:key.{a}})',false),
			array('{host:key.{a}}/{host:key.{a}}',false),
			array('{host:key.{a}}-{host:key.{a}}',false),
			array('{host:key.{a}}+{host:key.{a}}',false),
			array('{host:key.{a}}|{host:key.{a}}',false),
			array('{host:key.{a}}&{host:key.{a}}',false),
			array('{host:key.{a}}&{host:key.{a}}/{host:key.{a}}',false),
			array('{host:key.{a}}+{host:key.{a}}/{host:key.{a}}',false),
			array('1 - (1/{host:key.{a}})+({host:key.{a}})/{host:key.{a}}/{host:key.{a}}',false),
			array('({host::key.last{a}}) + + ({host::key.last{a}})',false),
			array('({host::key.last{a}}) + - ({host::key.last{a}})',false),
			array('({host::key.last{a}}) + ({host::key.last{a}})',false),
			array('({host::key.last{a}})',false),
			array('(--{host::key.last{a}})',false),
			array('(+{host::key.last{a}})',false),
			array('(/{host::key.last{a}})',false),
			array('{host::key.last{a}}/{host::key.last{a}}',false),
			array('{host::key.last{a}}-{host::key.last{a}}',false),
			array('{host::key.last{a}}+{host::key.last{a}}',false),
			array('{host::key.last{a}}|{host::key.last{a}}',false),
			array('{host::key.last{a}}&{host::key.last{a}}',false),
			array('{host::key.last{a}}&{host::key.last{a}}/{host::key.last{a}}',false),
			array('{host::key.last{a}}+{host::key.last{a}}/{host::key.last{a}}',false),
			array('1 - (1/{host::key.last{a}})+({host::key.last{a}})/{host::key.last{a}}/{host::key.last{a}}',false),
			array('({host::key.(0)}) + + ({host::key.(0)})',false),
			array('({host::key.(0)}) + - ({host::key.(0)})',false),
			array('({host::key.(0)}) + ({host::key.(0)})',false),
			array('({host::key.(0)})',false),
			array('(--{host::key.(0)})',false),
			array('(+{host::key.(0)})',false),
			array('(/{host::key.(0)})',false),
			array('{host::key.(0)}/{host::key.(0)}',false),
			array('{host::key.(0)}-{host::key.(0)}',false),
			array('{host::key.(0)}+{host::key.(0)}',false),
			array('{host::key.(0)}|{host::key.(0)}',false),
			array('{host::key.(0)}&{host::key.(0)}',false),
			array('{host::key.(0)}&{host::key.(0)}/{host::key.(0)}',false),
			array('{host::key.(0)}+{host::key.(0)}/{host::key.(0)}',false),
			array('1 - (1/{host::key.(0)})+({host::key.(0)})/{host::key.(0)}/{host::key.(0)}',false),
			array('({:key.(0)}) + + ({:key.(0)})',false),
			array('({:key.(0)}) + - ({:key.(0)})',false),
			array('({:key.(0)}) + ({:key.(0)})',false),
			array('({:key.(0)})',false),
			array('(--{:key.(0)})',false),
			array('(+{:key.(0)})',false),
			array('(/{:key.(0)})',false),
			array('{:key.(0)}/{:key.(0)}',false),
			array('{:key.(0)}-{:key.(0)}',false),
			array('{:key.(0)}+{:key.(0)}',false),
			array('{:key.(0)}|{:key.(0)}',false),
			array('{:key.(0)}&{:key.(0)}',false),
			array('{:key.(0)}&{:key.(0)}/{:key.(0)}',false),
			array('{:key.(0)}+{:key.(0)}/{:key.(0)}',false),
			array('1 - (1/{:key.(0)})+({:key.(0)})/{:key.(0)}/{:key.(0)}',false),
			array('({:key.last(0)}) + + ({:key.last(0)})',false),
			array('({:key.last(0)}) + - ({:key.last(0)})',false),
			array('({:key.last(0)}) + ({:key.last(0)})',false),
			array('({:key.last(0)})',false),
			array('(--{:key.last(0)})',false),
			array('(+{:key.last(0)})',false),
			array('(/{:key.last(0)})',false),
			array('{:key.last(0)}/{:key.last(0)}',false),
			array('{:key.last(0)}-{:key.last(0)}',false),
			array('{:key.last(0)}+{:key.last(0)}',false),
			array('{:key.last(0)}|{:key.last(0)}',false),
			array('{:key.last(0)}&{:key.last(0)}',false),
			array('{:key.last(0)}&{:key.last(0)}/{:key.last(0)}',false),
			array('{:key.last(0)}+{:key.last(0)}/{:key.last(0)}',false),
			array('1 - (1/{:key.last(0)})+({:key.last(0)})/{:key.last(0)}/{:key.last(0)}',false),
			array('(({host:key.last(0)})) + + (({host:key.last(0)}))',false),
			array('(({host:key.last(0)})) + - (({host:key.last(0)}))',false),
			array('(({host:key.last(0)})) + (({host:key.last(0)}))',true),
			array('(({host:key.last(0)}))',true),
			array('(--({host:key.last(0)}))',false),
			array('(+({host:key.last(0)}))',false),
			array('(/({host:key.last(0)}))',false),
			array('({host:key.last(0)})/({host:key.last(0)})',true),
			array('({host:key.last(0)})-({host:key.last(0)})',true),
			array('({host:key.last(0)})+({host:key.last(0)})',true),
			array('({host:key.last(0)})|({host:key.last(0)})',true),
			array('({host:key.last(0)})&({host:key.last(0)})',true),
			array('({host:key.last(0)})&({host:key.last(0)})/({host:key.last(0)})',true),
			array('({host:key.last(0)})+({host:key.last(0)})/({host:key.last(0)})',true),
			array('1 - (1/({host:key.last(0)}))+(({host:key.last(0)}))/({host:key.last(0)})/({host:key.last(0)})',true),
			array('({host:.last(0)}) + + ({host:.last(0)})',false),
			array('({host:.last(0)}) + - ({host:.last(0)})',false),
			array('({host:.last(0)}) + ({host:.last(0)})',false),
			array('({host:.last(0)})',false),
			array('(--{host:.last(0)})',false),
			array('(+{host:.last(0)})',false),
			array('(/{host:.last(0)})',false),
			array('{host:.last(0)}/{host:.last(0)}',false),
			array('{host:.last(0)}-{host:.last(0)}',false),
			array('{host:.last(0)}+{host:.last(0)}',false),
			array('{host:.last(0)}|{host:.last(0)}',false),
			array('{host:.last(0)}&{host:.last(0)}',false),
			array('{host:.last(0)}&{host:.last(0)}/{host:.last(0)}',false),
			array('{host:.last(0)}+{host:.last(0)}/{host:.last(0)}',false),
			array('1 - (1/{host:.last(0)})+({host:.last(0)})/{host:.last(0)}/{host:.last(0)}',false),
			array('({$}+{host:key.last(0)}) + + ({$}+{host:key.last(0)})',false),
			array('({$}+{host:key.last(0)}) + - ({$}+{host:key.last(0)})',false),
			array('({$}+{host:key.last(0)}) + ({$}+{host:key.last(0)})',false),
			array('({$}+{host:key.last(0)})',false),
			array('(--{$}+{host:key.last(0)})',false),
			array('(+{$}+{host:key.last(0)})',false),
			array('(/{$}+{host:key.last(0)})',false),
			array('{$}+{host:key.last(0)}/{$}+{host:key.last(0)}',false),
			array('{$}+{host:key.last(0)}-{$}+{host:key.last(0)}',false),
			array('{$}+{host:key.last(0)}+{$}+{host:key.last(0)}',false),
			array('{$}+{host:key.last(0)}|{$}+{host:key.last(0)}',false),
			array('{$}+{host:key.last(0)}&{$}+{host:key.last(0)}',false),
			array('{$}+{host:key.last(0)}&{$}+{host:key.last(0)}/{$}+{host:key.last(0)}',false),
			array('{$}+{host:key.last(0)}+{$}+{host:key.last(0)}/{$}+{host:key.last(0)}',false),
			array('1 - (1/{$}+{host:key.last(0)})+({$}+{host:key.last(0)})/{$}+{host:key.last(0)}/{$}+{host:key.last(0)}',false),
			array('( - {$MACRO}+{host:key.last(0)}) + + ( - {$MACRO}+{host:key.last(0)})',false),
			array('( - {$MACRO}+{host:key.last(0)}) + - ( - {$MACRO}+{host:key.last(0)})',false),
			array('( - {$MACRO}+{host:key.last(0)}) + ( - {$MACRO}+{host:key.last(0)})',true),
			array('( - {$MACRO}+{host:key.last(0)})',true),
			array('(-- - {$MACRO}+{host:key.last(0)})',false),
			array('(+ - {$MACRO}+{host:key.last(0)})',false),
			array('(/ - {$MACRO}+{host:key.last(0)})',false),
			array(' - {$MACRO}+{host:key.last(0)}/ - {$MACRO}+{host:key.last(0)}',true),
			array(' - {$MACRO}+{host:key.last(0)}- - {$MACRO}+{host:key.last(0)}',true),
			array(' - {$MACRO}+{host:key.last(0)}+ - {$MACRO}+{host:key.last(0)}',true),
			array(' - {$MACRO}+{host:key.last(0)}| - {$MACRO}+{host:key.last(0)}',true),
			array(' - {$MACRO}+{host:key.last(0)}& - {$MACRO}+{host:key.last(0)}',true),
			array(' - {$MACRO}+{host:key.last(0)}& - {$MACRO}+{host:key.last(0)}/ - {$MACRO}+{host:key.last(0)}',true),
			array(' - {$MACRO}+{host:key.last(0)}+ - {$MACRO}+{host:key.last(0)}/ - {$MACRO}+{host:key.last(0)}',true),
			array('1 - (1/ - {$MACRO}+{host:key.last(0)})+( - {$MACRO}+{host:key.last(0)})/ - {$MACRO}+{host:key.last(0)}/ - {$MACRO}+{host:key.last(0)}',true),
			array('(100G+{host:key.last(0)}) + + (100G+{host:key.last(0)})',false),
			array('(100G+{host:key.last(0)}) + - (100G+{host:key.last(0)})',false),
			array('(100G+{host:key.last(0)}) + (100G+{host:key.last(0)})',true),
			array('(100G+{host:key.last(0)})',true),
			array('(--100G+{host:key.last(0)})',false),
			array('(+100G+{host:key.last(0)})',false),
			array('(/100G+{host:key.last(0)})',false),
			array('100G+{host:key.last(0)}/100G+{host:key.last(0)}',true),
			array('100G+{host:key.last(0)}-100G+{host:key.last(0)}',true),
			array('100G+{host:key.last(0)}+100G+{host:key.last(0)}',true),
			array('100G+{host:key.last(0)}|100G+{host:key.last(0)}',true),
			array('100G+{host:key.last(0)}&100G+{host:key.last(0)}',true),
			array('100G+{host:key.last(0)}&100G+{host:key.last(0)}/100G+{host:key.last(0)}',true),
			array('100G+{host:key.last(0)}+100G+{host:key.last(0)}/100G+{host:key.last(0)}',true),
			array('1 - (1/100G+{host:key.last(0)})+(100G+{host:key.last(0)})/100G+{host:key.last(0)}/100G+{host:key.last(0)}',true),
			array('({host:key.last(0)}) + + ({host:key.last(0)})',false),
			array('({host:key.last(0)}) + - ({host:key.last(0)})',false),
			array('({host:key.last(0)}) + ({host:key.last(0)})',true),
			array('({host:key.last(0)})',true),
			array('(--{host:key.last(0)})',false),
			array('(+{host:key.last(0)})',false),
			array('(/{host:key.last(0)})',false),
			array('{host:key.last(0)}/{host:key.last(0)}',true),
			array('{host:key.last(0)}-{host:key.last(0)}',true),
			array('{host:key.last(0)}+{host:key.last(0)}',true),
			array('{host:key.last(0)}|{host:key.last(0)}',true),
			array('{host:key.last(0)}&{host:key.last(0)}',true),
			array('{host:key.last(0)}&{host:key.last(0)}/{host:key.last(0)}',true),
			array('{host:key.last(0)}+{host:key.last(0)}/{host:key.last(0)}',true),
			array('1 - (1/{host:key.last(0)})+({host:key.last(0)})/{host:key.last(0)}/{host:key.last(0)}',true),
			array('({host:key.last(0 - 1 / 2 |-4*-56.34K)}) + + ({host:key.last(0 - 1 / 2 |-4*-56.34K)})',false),
			array('({host:key.last(0 - 1 / 2 |-4*-56.34K)}) + - ({host:key.last(0 - 1 / 2 |-4*-56.34K)})',false),
			array('({host:key.last(0 - 1 / 2 |-4*-56.34K)}) + ({host:key.last(0 - 1 / 2 |-4*-56.34K)})',true),
			array('({host:key.last(0 - 1 / 2 |-4*-56.34K)})',true),
			array('(--{host:key.last(0 - 1 / 2 |-4*-56.34K)})',false),
			array('(+{host:key.last(0 - 1 / 2 |-4*-56.34K)})',false),
			array('(/{host:key.last(0 - 1 / 2 |-4*-56.34K)})',false),
			array('{host:key.last(0 - 1 / 2 |-4*-56.34K)}/{host:key.last(0 - 1 / 2 |-4*-56.34K)}',true),
			array('{host:key.last(0 - 1 / 2 |-4*-56.34K)}-{host:key.last(0 - 1 / 2 |-4*-56.34K)}',true),
			array('{host:key.last(0 - 1 / 2 |-4*-56.34K)}+{host:key.last(0 - 1 / 2 |-4*-56.34K)}',true),
			array('{host:key.last(0 - 1 / 2 |-4*-56.34K)}|{host:key.last(0 - 1 / 2 |-4*-56.34K)}',true),
			array('{host:key.last(0 - 1 / 2 |-4*-56.34K)}&{host:key.last(0 - 1 / 2 |-4*-56.34K)}',true),
			array('{host:key.last(0 - 1 / 2 |-4*-56.34K)}&{host:key.last(0 - 1 / 2 |-4*-56.34K)}/{host:key.last(0 - 1 / 2 |-4*-56.34K)}',true),
			array('{host:key.last(0 - 1 / 2 |-4*-56.34K)}+{host:key.last(0 - 1 / 2 |-4*-56.34K)}/{host:key.last(0 - 1 / 2 |-4*-56.34K)}',true),
			array('1 - (1/{host:key.last(0 - 1 / 2 |-4*-56.34K)})+({host:key.last(0 - 1 / 2 |-4*-56.34K)})/{host:key.last(0 - 1 / 2 |-4*-56.34K)}/{host:key.last(0 - 1 / 2 |-4*-56.34K)}',true),
			array('({host:key.last(^$$$^%)}) + + ({host:key.last(^$$$^%)})',false),
			array('({host:key.last(^$$$^%)}) + - ({host:key.last(^$$$^%)})',false),
			array('({host:key.last(^$$$^%)}) + ({host:key.last(^$$$^%)})',true),
			array('({host:key.last(^$$$^%)})',true),
			array('(--{host:key.last(^$$$^%)})',false),
			array('(+{host:key.last(^$$$^%)})',false),
			array('(/{host:key.last(^$$$^%)})',false),
			array('{host:key.last(^$$$^%)}/{host:key.last(^$$$^%)}',true),
			array('{host:key.last(^$$$^%)}-{host:key.last(^$$$^%)}',true),
			array('{host:key.last(^$$$^%)}+{host:key.last(^$$$^%)}',true),
			array('{host:key.last(^$$$^%)}|{host:key.last(^$$$^%)}',true),
			array('{host:key.last(^$$$^%)}&{host:key.last(^$$$^%)}',true),
			array('{host:key.last(^$$$^%)}&{host:key.last(^$$$^%)}/{host:key.last(^$$$^%)}',true),
			array('{host:key.last(^$$$^%)}+{host:key.last(^$$$^%)}/{host:key.last(^$$$^%)}',true),
			array('1 - (1/{host:key.last(^$$$^%)})+({host:key.last(^$$$^%)})/{host:key.last(^$$$^%)}/{host:key.last(^$$$^%)}',true),
			array('({host:key.last("*(^*&%#$%")}) + + ({host:key.last("*(^*&%#$%")})',false),
			array('({host:key.last("*(^*&%#$%")}) + - ({host:key.last("*(^*&%#$%")})',false),
			array('({host:key.last("*(^*&%#$%")}) + ({host:key.last("*(^*&%#$%")})',true),
			array('({host:key.last("*(^*&%#$%")})',true),
			array('(--{host:key.last("*(^*&%#$%")})',false),
			array('(+{host:key.last("*(^*&%#$%")})',false),
			array('(/{host:key.last("*(^*&%#$%")})',false),
			array('{host:key.last("*(^*&%#$%")}/{host:key.last("*(^*&%#$%")}',true),
			array('{host:key.last("*(^*&%#$%")}-{host:key.last("*(^*&%#$%")}',true),
			array('{host:key.last("*(^*&%#$%")}+{host:key.last("*(^*&%#$%")}',true),
			array('{host:key.last("*(^*&%#$%")}|{host:key.last("*(^*&%#$%")}',true),
			array('{host:key.last("*(^*&%#$%")}&{host:key.last("*(^*&%#$%")}',true),
			array('{host:key.last("*(^*&%#$%")}&{host:key.last("*(^*&%#$%")}/{host:key.last("*(^*&%#$%")}',true),
			array('{host:key.last("*(^*&%#$%")}+{host:key.last("*(^*&%#$%")}/{host:key.last("*(^*&%#$%")}',true),
			array('1 - (1/{host:key.last("*(^*&%#$%")})+({host:key.last("*(^*&%#$%")})/{host:key.last("*(^*&%#$%")}/{host:key.last("*(^*&%#$%")}',true),
			array('(((((((({host:key.last("")})))))))) + + (((((((({host:key.last("")}))))))))',false),
			array('(((((((({host:key.last("")})))))))) + - (((((((({host:key.last("")}))))))))',false),
			array('(((((((({host:key.last("")})))))))) + (((((((({host:key.last("")}))))))))',true),
			array('(((((((({host:key.last("")}))))))))',true),
			array('(--((((((({host:key.last("")}))))))))',false),
			array('(+((((((({host:key.last("")}))))))))',false),
			array('(/((((((({host:key.last("")}))))))))',false),
			array('((((((({host:key.last("")})))))))/((((((({host:key.last("")})))))))',true),
			array('((((((({host:key.last("")})))))))-((((((({host:key.last("")})))))))',true),
			array('((((((({host:key.last("")})))))))+((((((({host:key.last("")})))))))',true),
			array('((((((({host:key.last("")})))))))|((((((({host:key.last("")})))))))',true),
			array('((((((({host:key.last("")})))))))&((((((({host:key.last("")})))))))',true),
			array('((((((({host:key.last("")})))))))&((((((({host:key.last("")})))))))/((((((({host:key.last("")})))))))',true),
			array('((((((({host:key.last("")})))))))+((((((({host:key.last("")})))))))/((((((({host:key.last("")})))))))',true),
			array('1 - (1/((((((({host:key.last("")}))))))))+(((((((({host:key.last("")}))))))))/((((((({host:key.last("")})))))))/((((((({host:key.last("")})))))))',true),
			array('((1 - 1-2-((((((({host:key.last("0")}))))))))) + + ((1 - 1-2-((((((({host:key.last("0")})))))))))',false),
			array('((1 - 1-2-((((((({host:key.last("0")}))))))))) + - ((1 - 1-2-((((((({host:key.last("0")})))))))))',false),
			array('((1 - 1-2-((((((({host:key.last("0")}))))))))) + ((1 - 1-2-((((((({host:key.last("0")})))))))))',true),
			array('((1 - 1-2-((((((({host:key.last("0")})))))))))',true),
			array('(--(1 - 1-2-((((((({host:key.last("0")})))))))))',false),
			array('(+(1 - 1-2-((((((({host:key.last("0")})))))))))',false),
			array('(/(1 - 1-2-((((((({host:key.last("0")})))))))))',false),
			array('(1 - 1-2-((((((({host:key.last("0")}))))))))/(1 - 1-2-((((((({host:key.last("0")}))))))))',true),
			array('(1 - 1-2-((((((({host:key.last("0")}))))))))-(1 - 1-2-((((((({host:key.last("0")}))))))))',true),
			array('(1 - 1-2-((((((({host:key.last("0")}))))))))+(1 - 1-2-((((((({host:key.last("0")}))))))))',true),
			array('(1 - 1-2-((((((({host:key.last("0")}))))))))|(1 - 1-2-((((((({host:key.last("0")}))))))))',true),
			array('(1 - 1-2-((((((({host:key.last("0")}))))))))&(1 - 1-2-((((((({host:key.last("0")}))))))))',true),
			array('(1 - 1-2-((((((({host:key.last("0")}))))))))&(1 - 1-2-((((((({host:key.last("0")}))))))))/(1 - 1-2-((((((({host:key.last("0")}))))))))',true),
			array('(1 - 1-2-((((((({host:key.last("0")}))))))))+(1 - 1-2-((((((({host:key.last("0")}))))))))/(1 - 1-2-((((((({host:key.last("0")}))))))))',true),
			array('1 - (1/(1 - 1-2-((((((({host:key.last("0")})))))))))+((1 - 1-2-((((((({host:key.last("0")})))))))))/(1 - 1-2-((((((({host:key.last("0")}))))))))/(1 - 1-2-((((((({host:key.last("0")}))))))))',true),
		);
	}

	/**
	* @dataProvider provider
	*/
	public function test_parse($a, $b)
	{
		$trigger = new CTriggerExpression(array('expression'=>$a));
		if(empty($trigger->errors)) {
			$this->assertEquals($b,true);
		} else {
//			print_r($trigger->errors);
			$this->assertEquals($b,false,$trigger->errors[0]);
		}
	}

}
?>
