alter table config add event_ack_enable      number(10)    DEFAULT '1'     NOT NULL;
alter table config add event_expire          number(10)    DEFAULT '7'     NOT NULL;
alter table config add event_show_max        number(10)    DEFAULT '100'   NOT NULL;
alter table config add default_theme         varchar2(128) DEFAULT 'default.css';
alter table config add authentication_type   number(10)    DEFAULT 0       NOT NULL;
alter table config add ldap_host             varchar2(255) DEFAULT '';
alter table config add ldap_port             number(10)    DEFAULT 389     NOT NULL;
alter table config add ldap_base_dn          varchar2(255) DEFAULT '';
alter table config add ldap_bind_dn          varchar2(255) DEFAULT '';
alter table config add ldap_bind_password    varchar2(128) DEFAULT '';
alter table config add ldap_search_attribute varchar2(128) DEFAULT '';
