.TH ZABBIX_GET 8 "5 July 2011"
.SH NAME
zabbix_get \- Zabbix get utility.
.SH SYNOPSIS
.B zabbix_get [-hV] [-s \fI<host name or IP>\fB] [-p \fI<port number>\fB] [-I \fI<IP address>\fB] [-k \fI<item key>\fB]
.SH DESCRIPTION
.B zabbix_get
is a command line utility for getting data from a remote Zabbix agent.
.SS Options
.IP "-s, --host \fI<host name or IP>\fR"
Specify host name or IP address of a host.
.IP "-p, --port \fI<port number>\fR"
Specify port number of agent running on the host. Default is 10050.
.IP "-t, --timeout \fI<seconds>\fR"
Specify connection timeout in seconds within the range of 1-600. Default is 60.
.IP "-I, --source-address \fI<IP address>\fR"
Specify source IP address.
.IP "-k, --key \fI<item key>\fR"
Specify key of item to retrieve value for.
.IP "-h, --help"
Display this help and exit.
.IP "-V, --version"
Output version information and exit.
.SH "EXAMPLES"
.B zabbix_get -s 127.0.0.1 -p 10050 -k """system.cpu.load[all,avg1]"""
.SH "SEE ALSO"
.BR zabbix_agentd (8),
.BR zabbix_proxy (8),
.BR zabbix_sender (8),
.BR zabbix_server (8)
.SH AUTHOR
Alexei Vladishev <alex@zabbix.com>
