<?php declare(strict_types=1);
/*
** Zabbix
** Copyright (C) 2001-2021 Zabbix SIA
**
** This program is free software; you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation; either version 2 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program; if not, write to the Free Software
** Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
**/


use PHPUnit\Framework\TestCase;

class CHistFunctionValidatorTest extends TestCase {

	/**
	 * An array of e-mails, results and error messages.
	 */
	public function dataProvider() {
		return [
			['foo(/host/key)', [], ['rc' => false, 'error' => 'unknown function "foo"']],
			['avg_foreach(/host/key)', [], ['rc' => false, 'error' => 'unknown function "avg_foreach"']],
			['count_foreach(/host/key)', [], ['rc' => false, 'error' => 'unknown function "count_foreach"']],
			['last_foreach(/host/key)', [], ['rc' => false, 'error' => 'unknown function "last_foreach"']],
			['max_foreach(/host/key)', [], ['rc' => false, 'error' => 'unknown function "max_foreach"']],
			['min_foreach(/host/key)', [], ['rc' => false, 'error' => 'unknown function "min_foreach"']],
			['sum_foreach(/host/key)', [], ['rc' => false, 'error' => 'unknown function "sum_foreach"']],

			['avg(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "avg"']],
			['avg(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "avg"']],
			['avg(/host/key,0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "avg"']],
			['avg(/host/key,#0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "avg"']],
			['avg(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, 1M)', [], ['rc' => false, 'error' => 'invalid second parameter in function "avg"']],
			['avg(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, #2147483648)', [], ['rc' => false, 'error' => 'invalid second parameter in function "avg"']],
			['avg(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, 35791394m)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, 596523h)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, 24855d)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, 3550w)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, 2147483648)', [], ['rc' => false, 'error' => 'invalid second parameter in function "avg"']],
			['avg(/host/key, 35791395m)', [], ['rc' => false, 'error' => 'invalid second parameter in function "avg"']],
			['avg(/host/key, 596524h)', [], ['rc' => false, 'error' => 'invalid second parameter in function "avg"']],
			['avg(/host/key, 24856d)', [], ['rc' => false, 'error' => 'invalid second parameter in function "avg"']],
			['avg(/host/key, 3551w)', [], ['rc' => false, 'error' => 'invalid second parameter in function "avg"']],

			['avg(/host/key, #256,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "avg"']],

			['min(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "min"']],
			['min(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "min"']],
			['min(/host/key,0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "min"']],
			['min(/host/key,#0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "min"']],
			['min(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['min(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['min(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, 1M)', [], ['rc' => false, 'error' => 'invalid second parameter in function "min"']],
			['min(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, #256,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "min"']],

			['max(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "max"']],
			['max(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "max"']],
			['max(/host/key,0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "max"']],
			['max(/host/key,#0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "max"']],
			['max(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['max(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['max(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, 1M)', [], ['rc' => false, 'error' => 'invalid second parameter in function "max"']],
			['max(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, #256,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "max"']],

			['sum(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "sum"']],
			['sum(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "sum"']],
			['sum(/host/key,0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "sum"']],
			['sum(/host/key,#0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "sum"']],
			['sum(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, 1M)', [], ['rc' => false, 'error' => 'invalid second parameter in function "sum"']],
			['sum(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, #256,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "sum"']],

			['change(/host/key)', [], ['rc' => true, 'error' => null]],
			['change(/host/key,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "change"']],

			['last(/host/key)', [], ['rc' => true, 'error' => null]],
			['last(/host/key,)', [], ['rc' => true, 'error' => null]],
			['last(/host/key,0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "last"']],
			['last(/host/key,#0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "last"']],
			['last(/host/key,1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "last"']],
			['last(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['last(/host/key,1s)', [], ['rc' => false, 'error' => 'invalid second parameter in function "last"']],
			['last(/host/key, 1m)', [], ['rc' => false, 'error' => 'invalid second parameter in function "last"']],
			['last(/host/key, 1M)', [], ['rc' => false, 'error' => 'invalid second parameter in function "last"']],
			['last(/host/key, 1m:now/h-1h)', [], ['rc' => false, 'error' => 'invalid second parameter in function "last"']],
			['last(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['last(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['last(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['last(/host/key, #2147483648)', [], ['rc' => false, 'error' => 'invalid second parameter in function "last"']],
			['last(/host/key, 2147483647)', [], ['rc' => false, 'error' => 'invalid second parameter in function "last"']],
			['last(/host/key, #256,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "last"']],

			['logseverity(/host/key)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key,)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key,0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logseverity"']],
			['logseverity(/host/key,#0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logseverity"']],
			['logseverity(/host/key,1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logseverity"']],
			['logseverity(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key,1s)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logseverity"']],
			['logseverity(/host/key, 1m)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logseverity"']],
			['logseverity(/host/key, 1M)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logseverity"']],
			['logseverity(/host/key, 1m:now/h-1h)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logseverity"']],
			['logseverity(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key, #2147483648)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logseverity"']],
			['logseverity(/host/key, 2147483647)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logseverity"']],
			['logseverity(/host/key, #256,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "logseverity"']],

			['logeventid(/host/key)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key,)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key,0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logeventid"']],
			['logeventid(/host/key,#0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logeventid"']],
			['logeventid(/host/key,1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logeventid"']],
			['logeventid(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key,1s)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logeventid"']],
			['logeventid(/host/key, 1m)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logeventid"']],
			['logeventid(/host/key, 1M)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logeventid"']],
			['logeventid(/host/key, 1m:now/h-1h)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logeventid"']],
			['logeventid(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #2147483648)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logeventid"']],
			['logeventid(/host/key, 2147483647)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logeventid"']],
			['logeventid(/host/key, #256,)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #256, "str")', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #256, 10)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #256, 10K)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #256, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #256, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #256, "str",)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "logeventid"']],

			['logsource(/host/key)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key,)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key,0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logsource"']],
			['logsource(/host/key,#0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logsource"']],
			['logsource(/host/key,1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logsource"']],
			['logsource(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key,1s)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logsource"']],
			['logsource(/host/key, 1m)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logsource"']],
			['logsource(/host/key, 1M)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logsource"']],
			['logsource(/host/key, 1m:now/h-1h)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logsource"']],
			['logsource(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #2147483648)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logsource"']],
			['logsource(/host/key, 2147483647)', [], ['rc' => false, 'error' => 'invalid second parameter in function "logsource"']],
			['logsource(/host/key, #256,)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #256, "str")', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #256, 10)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #256, 10K)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #256, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #256, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #256, "str",)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "logsource"']],

			['count(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "count"']],
			['count(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "count"']],
			['count(/host/key,0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "count"']],
			['count(/host/key,#0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "count"']],
			['count(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['count(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['count(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, 1M)', [], ['rc' => false, 'error' => 'invalid second parameter in function "count"']],
			['count(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256,)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "str")', [], ['rc' => false, 'error' => 'invalid third parameter in function "count"']],
			['count(/host/key, #256, 10)', [], ['rc' => false, 'error' => 'invalid third parameter in function "count"']],
			['count(/host/key, #256, 10K)', [], ['rc' => false, 'error' => 'invalid third parameter in function "count"']],
			['count(/host/key, #256, "eq")', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "ne")', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "like")', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "bitand")', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "{$MACRO}{$LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "regexp",)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "regexp", 100)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "regexp", 1s)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "regexp", {$MACRO})', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "regexp", {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "regexp",,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "count"']],

			['find(/host/key)', [], ['rc' => true, 'error' => null]],
			['find(/host/key,)', [], ['rc' => true, 'error' => null]],
			['find(/host/key,0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "find"']],
			['find(/host/key,#0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "find"']],
			['find(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['find(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['find(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, 1M)', [], ['rc' => false, 'error' => 'invalid second parameter in function "find"']],
			['find(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256,)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "str")', [], ['rc' => false, 'error' => 'invalid third parameter in function "find"']],
			['find(/host/key, #256, 10)', [], ['rc' => false, 'error' => 'invalid third parameter in function "find"']],
			['find(/host/key, #256, 10K)', [], ['rc' => false, 'error' => 'invalid third parameter in function "find"']],
			['find(/host/key, #256, "eq")', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "ne")', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "like")', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "bitand")', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "{$MACRO}{$LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "regexp",)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "regexp", 100)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "regexp", 1s)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "regexp", {$MACRO})', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "regexp", {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "regexp",,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "find"']],

			['forecast(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "forecast"']],
			['forecast(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "forecast"']],
			['forecast(/host/key,,10h)', [], ['rc' => false, 'error' => 'invalid second parameter in function "forecast"']],
			['forecast(/host/key,#1)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "forecast"']],
			['forecast(/host/key,0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "forecast"']],
			['forecast(/host/key,#0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "forecast"']],
			['forecast(/host/key,1,5s)', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key,#1,10h)', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key,1s,-7d)', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key,1s, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key,1s, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key,1s, "{$MACRO}{$LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, 1m,)', [], ['rc' => false, 'error' => 'invalid third parameter in function "forecast"']],
			['forecast(/host/key, 1M,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "forecast"']],
			['forecast(/host/key, 1m:now/h-1h, 1d)', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #3:now/h-1h, 1m)', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #5:now/M, 1w)', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "linear")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "polynomial3")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "{$M}")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, {$M})', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "foo")', [], ['rc' => false, 'error' => 'invalid fourth parameter in function "forecast"']],
			['forecast(/host/key, #256, 30d, 25d)', [], ['rc' => false, 'error' => 'invalid fourth parameter in function "forecast"']],
			['forecast(/host/key, #256, 30d, "exponential", "delta")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "exponential", "avg")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "exponential", "bar")', [], ['rc' => false, 'error' => 'invalid fifth parameter in function "forecast"']],
			['forecast(/host/key, #256, 30d, "exponential", "{#M}")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "exponential", {#M})', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "exponential", "min",)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "forecast"']],

			['timeleft(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "timeleft"']],
			['timeleft(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "timeleft"']],
			['timeleft(/host/key,#1)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "timeleft"']],
			['timeleft(/host/key,#1,)', [], ['rc' => false, 'error' => 'invalid third parameter in function "timeleft"']],
			['timeleft(/host/key,0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "timeleft"']],
			['timeleft(/host/key,#0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "timeleft"']],
			['timeleft(/host/key,1,5s)', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key,#1,10h)', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key,1s,-7d)', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key,1s, "abc")', [], ['rc' => false, 'error' => 'invalid third parameter in function "timeleft"']],
			['timeleft(/host/key,1s, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key,1s, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key,1s, "{$MACRO}{$LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, 1m:now/h-1h, 1d)', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #3:now/h-1h, 1m)', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #5:now/M, 1w)', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #256, 30d, "linear")', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #256, 30d, "polynomial3")', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #256, 30d, "{$M}")', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #256, 30d, {$M})', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #256, 30d, "foo")', [], ['rc' => false, 'error' => 'invalid fourth parameter in function "timeleft"']],
			['timeleft(/host/key, #256, 30d, 25d)', [], ['rc' => false, 'error' => 'invalid fourth parameter in function "timeleft"']],
			['timeleft(/host/key, #256, 30d, "exponential",)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "timeleft"']],

			['percentile(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "percentile"']],
			['percentile(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "percentile"']],
			['percentile(/host/key, #1)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "percentile"']],
			['percentile(/host/key, #1,)', [], ['rc' => false, 'error' => 'invalid third parameter in function "percentile"']],
			['percentile(/host/key, 0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "percentile"']],
			['percentile(/host/key, #0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "percentile"']],
			['percentile(/host/key, 1h:now/h-1h, "abc")', [], ['rc' => false, 'error' => 'invalid third parameter in function "percentile"']],
			['percentile(/host/key, 1h:now/h-1h, 5s)', [], ['rc' => false, 'error' => 'invalid third parameter in function "percentile"']],
			['percentile(/host/key, 1h:now/h-1h, 1m)', [], ['rc' => false, 'error' => 'invalid third parameter in function "percentile"']],
			['percentile(/host/key, 1h:now/h-1h, -1)', [], ['rc' => false, 'error' => 'invalid third parameter in function "percentile"']],
			['percentile(/host/key, 1h:now/h-1h, 101)', [], ['rc' => false, 'error' => 'invalid third parameter in function "percentile"']],
			['percentile(/host/key, 1h, 0.12345)', [], ['rc' => false, 'error' => 'invalid third parameter in function "percentile"']],
			['percentile(/host/key, 1, 0)', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, 1h, 0.1234)', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, 1h, 99.9999)', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, #1, 100)', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, 1s, "abc")', [], ['rc' => false, 'error' => 'invalid third parameter in function "percentile"']],
			['percentile(/host/key, 1s, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, 1s, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, 1s, "{$MACRO}{$LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, #256, 5,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "percentile"']],

			['fuzzytime(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "fuzzytime"']],
			['fuzzytime(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "fuzzytime"']],
			['fuzzytime(/host/key, 0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "fuzzytime"']],
			['fuzzytime(/host/key, #0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "fuzzytime"']],
			['fuzzytime(/host/key, #1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "fuzzytime"']],
			['fuzzytime(/host/key, 1)', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, 1h)', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, "{$MACRO}{#LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, "1h")', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, 35791394m)', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, 596523h)', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, 24855d)', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, 3550w)', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, 2147483648)', [], ['rc' => false, 'error' => 'invalid second parameter in function "fuzzytime"']],
			['fuzzytime(/host/key, 35791395m)', [], ['rc' => false, 'error' => 'invalid second parameter in function "fuzzytime"']],
			['fuzzytime(/host/key, 596524h)', [], ['rc' => false, 'error' => 'invalid second parameter in function "fuzzytime"']],
			['fuzzytime(/host/key, 24856d)', [], ['rc' => false, 'error' => 'invalid second parameter in function "fuzzytime"']],
			['fuzzytime(/host/key, 3551w)', [], ['rc' => false, 'error' => 'invalid second parameter in function "fuzzytime"']],
			['fuzzytime(/host/key, 1h,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "fuzzytime"']],

			['nodata(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "nodata"']],
			['nodata(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "nodata"']],
			['nodata(/host/key, 0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "nodata"']],
			['nodata(/host/key, #0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "nodata"']],
			['nodata(/host/key, #1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "nodata"']],
			['nodata(/host/key, 1)', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h)', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, "{$MACRO}{#LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, "1h")', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h,)', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h,)', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h, "strict")', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h, "{$MACRO}{#LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h, "foor")', [], ['rc' => false, 'error' => 'invalid third parameter in function "nodata"']],
			['nodata(/host/key, 1h, "strict",)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "nodata"']],

			['trendavg(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "trendavg"']],
			['trendavg(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendavg"']],
			['trendavg(/host/key, 0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendavg"']],
			['trendavg(/host/key, #0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendavg"']],
			['trendavg(/host/key, #1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendavg"']],
			['trendavg(/host/key, 1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendavg"']],
			['trendavg(/host/key, 1h)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendavg"']],
			['trendavg(/host/key, 1h:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, 1d:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, 1y:now/M-1h)', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, {$PERIOD}:{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, {$PERIOD}:now-{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, 1y:now/y,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "trendavg"']],

			['trendcount(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "trendcount"']],
			['trendcount(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendcount"']],
			['trendcount(/host/key, 0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendcount"']],
			['trendcount(/host/key, #0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendcount"']],
			['trendcount(/host/key, #1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendcount"']],
			['trendcount(/host/key, 1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendcount"']],
			['trendcount(/host/key, 1h)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendcount"']],
			['trendcount(/host/key, 1h:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, 1d:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, 1y:now/M-1h)', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, {$PERIOD}:{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, {$PERIOD}:now-{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, 1y:now/y,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "trendcount"']],

			['trendmax(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "trendmax"']],
			['trendmax(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendmax"']],
			['trendmax(/host/key, 0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendmax"']],
			['trendmax(/host/key, #0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendmax"']],
			['trendmax(/host/key, #1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendmax"']],
			['trendmax(/host/key, 1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendmax"']],
			['trendmax(/host/key, 1h)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendmax"']],
			['trendmax(/host/key, 1h:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, 1d:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, 1y:now/M-1h)', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, {$PERIOD}:{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, {$PERIOD}:now-{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, 1y:now/y,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "trendmax"']],

			['trendmin(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "trendmin"']],
			['trendmin(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendmin"']],
			['trendmin(/host/key, 0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendmin"']],
			['trendmin(/host/key, #0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendmin"']],
			['trendmin(/host/key, #1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendmin"']],
			['trendmin(/host/key, 1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendmin"']],
			['trendmin(/host/key, 1h)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendmin"']],
			['trendmin(/host/key, 1h:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, 1d:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, 1y:now/M-1h)', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, {$PERIOD}:{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, {$PERIOD}:now-{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, 1y:now/y,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "trendmin"']],

			['trendsum(/host/key)', [], ['rc' => false, 'error' => 'mandatory parameter is missing in function "trendsum"']],
			['trendsum(/host/key,)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendsum"']],
			['trendsum(/host/key, 0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendsum"']],
			['trendsum(/host/key, #0)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendsum"']],
			['trendsum(/host/key, #1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendsum"']],
			['trendsum(/host/key, 1)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendsum"']],
			['trendsum(/host/key, 1h)', [], ['rc' => false, 'error' => 'invalid second parameter in function "trendsum"']],
			['trendsum(/host/key, 1h:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, 1d:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, 1y:now/M-1h)', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, {$PERIOD}:{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, {$PERIOD}:now-{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, 1y:now/y,)', [], ['rc' => false, 'error' => 'invalid number of parameters in function "trendsum"']],

			['avg_foreach(/host/key)', ['calculated' => true], ['rc' => false, 'error' => 'mandatory parameter is missing in function "avg_foreach"']],
			['avg_foreach(/host/key,)', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "avg_foreach"']],
			['avg_foreach(/host/key, 0)', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "avg_foreach"']],
			['avg_foreach(/host/key, #0)', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "avg_foreach"']],
			['avg_foreach(/host/key, #1)', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "avg_foreach"']],
			['avg_foreach(/host/key, 1)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['avg_foreach(/host/key, 1h)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['avg_foreach(/host/key, 1d)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['avg_foreach(/host/key, 1d:now/d)', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "avg_foreach"']],
			['avg_foreach(/host/key, {$PERIOD}:{$TIMESHIFT})', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "avg_foreach"']],
			['avg_foreach(/host/key, {$PERIOD}:now-{$TIMESHIFT})', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "avg_foreach"']],
			['avg_foreach(/host/key, {$MACRO})', ['calculated' => true], ['rc' => true, 'error' => null]],
			['avg_foreach(/host/key, {#LLDMACRO})', ['calculated' => true], ['rc' => true, 'error' => null]],
			['avg_foreach(/host/key, 1d,)', ['calculated' => true], ['rc' => false, 'error' => 'invalid number of parameters in function "avg_foreach"']],

			['last_foreach(/host/key)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key,)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key, 0)', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "last_foreach"']],
			['last_foreach(/host/key, #0)', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "last_foreach"']],
			['last_foreach(/host/key, #1)', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "last_foreach"']],
			['last_foreach(/host/key, 1)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key, 1h)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key, 1d)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key, 1d:now/d)', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "last_foreach"']],
			['last_foreach(/host/key, {$PERIOD}:{$TIMESHIFT})', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "last_foreach"']],
			['last_foreach(/host/key, {$PERIOD}:now-1d)', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "last_foreach"']],
			['last_foreach(/host/key, {$PERIOD}:now-{$TIMESHIFT})', ['calculated' => true], ['rc' => false, 'error' => 'invalid second parameter in function "last_foreach"']],
			['last_foreach(/host/key, {$MACRO})', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key, {#LLDMACRO})', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key, 1d,)', ['calculated' => true], ['rc' => false, 'error' => 'invalid number of parameters in function "last_foreach"']]
		];
	}

	/**
	 * @dataProvider dataProvider
	 */
	public function testHistFunctionValidator(string $source, array $options, array $expected) {
		$expression_parser = new CExpressionParser([
			'lldmacros' => true
		] + $options);
		$hist_function_validator = new CHistFunctionValidator([
			'parameters' => (new CHistFunctionData($options))->getParameters()
		]);
		$expression_parser->parse($source);
		$tokens = $expression_parser->getResult()->getTokens();

		$this->assertSame(CExpressionParserResult::TOKEN_TYPE_HIST_FUNCTION, $tokens[0]['type']);
		$this->assertSame($expected, [
			'rc' => $hist_function_validator->validate($tokens[0]),
			'error' => $hist_function_validator->getError()
		]);
	}
}
