<?php declare(strict_types=1);
/*
** Zabbix
** Copyright (C) 2001-2021 Zabbix SIA
**
** This program is free software; you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation; either version 2 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program; if not, write to the Free Software
** Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
**/


use PHPUnit\Framework\TestCase;

class CHistFunctionValidatorTest extends TestCase {

	/**
	 * An array of e-mails, results and error messages.
	 */
	public function dataProvider() {
		return [
			['foo(/host/key)', [], ['rc' => false, 'error' => 'Unknown function "foo".']],
			['avg_foreach(/host/key)', [], ['rc' => false, 'error' => 'Unknown function "avg_foreach".']],
			['count_foreach(/host/key)', [], ['rc' => false, 'error' => 'Unknown function "count_foreach".']],
			['last_foreach(/host/key)', [], ['rc' => false, 'error' => 'Unknown function "last_foreach".']],
			['max_foreach(/host/key)', [], ['rc' => false, 'error' => 'Unknown function "max_foreach".']],
			['min_foreach(/host/key)', [], ['rc' => false, 'error' => 'Unknown function "min_foreach".']],
			['sum_foreach(/host/key)', [], ['rc' => false, 'error' => 'Unknown function "sum_foreach".']],

			['avg(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "avg". Mandatory parameter is missing.']],
			['avg(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "avg". Mandatory parameter is missing.']],	// invalid second parameter
			['avg(/host/key,0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "avg". Invalid second parameter.']],
			['avg(/host/key,#0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "avg". Invalid second parameter.']],
			['avg(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, 1M)', [], ['rc' => false, 'error' => 'Incorrect usage of function "avg". Invalid second parameter.']],
			['avg(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['avg(/host/key, #256,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "avg". Invalid number of parameters.']],

			['min(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "min". Mandatory parameter is missing.']],
			['min(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "min". Mandatory parameter is missing.']],	// invalid second parameter
			['min(/host/key,0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "min". Invalid second parameter.']],
			['min(/host/key,#0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "min". Invalid second parameter.']],
			['min(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['min(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['min(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, 1M)', [], ['rc' => false, 'error' => 'Incorrect usage of function "min". Invalid second parameter.']],
			['min(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['min(/host/key, #256,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "min". Invalid number of parameters.']],

			['max(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "max". Mandatory parameter is missing.']],
			['max(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "max". Mandatory parameter is missing.']],	// invalid second parameter
			['max(/host/key,0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "max". Invalid second parameter.']],
			['max(/host/key,#0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "max". Invalid second parameter.']],
			['max(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['max(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['max(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, 1M)', [], ['rc' => false, 'error' => 'Incorrect usage of function "max". Invalid second parameter.']],
			['max(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['max(/host/key, #256,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "max". Invalid number of parameters.']],

			['sum(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "sum". Mandatory parameter is missing.']],
			['sum(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "sum". Mandatory parameter is missing.']],	// invalid second parameter
			['sum(/host/key,0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "sum". Invalid second parameter.']],
			['sum(/host/key,#0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "sum". Invalid second parameter.']],
			['sum(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, 1M)', [], ['rc' => false, 'error' => 'Incorrect usage of function "sum". Invalid second parameter.']],
			['sum(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['sum(/host/key, #256,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "sum". Invalid number of parameters.']],

			['change(/host/key)', [], ['rc' => true, 'error' => null]],
			['change(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "change". Invalid number of parameters.']],

			['last(/host/key)', [], ['rc' => true, 'error' => null]],
			['last(/host/key,)', [], ['rc' => true, 'error' => null]],
			['last(/host/key,0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "last". Invalid second parameter.']],
			['last(/host/key,#0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "last". Invalid second parameter.']],
			['last(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['last(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['last(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['last(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['last(/host/key, 1M)', [], ['rc' => false, 'error' => 'Incorrect usage of function "last". Invalid second parameter.']],
			['last(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['last(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['last(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['last(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['last(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['last(/host/key, #256,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "last". Invalid number of parameters.']],

			['logseverity(/host/key)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key,)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key,0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "logseverity". Invalid second parameter.']],
			['logseverity(/host/key,#0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "logseverity". Invalid second parameter.']],
			['logseverity(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key, 1M)', [], ['rc' => false, 'error' => 'Incorrect usage of function "logseverity". Invalid second parameter.']],
			['logseverity(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['logseverity(/host/key, #256,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "logseverity". Invalid number of parameters.']],

			['logeventid(/host/key)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key,)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key,0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "logeventid". Invalid second parameter.']],
			['logeventid(/host/key,#0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "logeventid". Invalid second parameter.']],
			['logeventid(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, 1M)', [], ['rc' => false, 'error' => 'Incorrect usage of function "logeventid". Invalid second parameter.']],
			['logeventid(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #256,)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #256, "str")', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #256, 10)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #256, 10K)', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #256, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #256, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['logeventid(/host/key, #256, "str",)', [], ['rc' => false, 'error' => 'Incorrect usage of function "logeventid". Invalid number of parameters.']],

			['logsource(/host/key)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key,)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key,0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "logsource". Invalid second parameter.']],
			['logsource(/host/key,#0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "logsource". Invalid second parameter.']],
			['logsource(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, 1M)', [], ['rc' => false, 'error' => 'Incorrect usage of function "logsource". Invalid second parameter.']],
			['logsource(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #256,)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #256, "str")', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #256, 10)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #256, 10K)', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #256, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #256, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['logsource(/host/key, #256, "str",)', [], ['rc' => false, 'error' => 'Incorrect usage of function "logsource". Invalid number of parameters.']],

			['count(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "count". Mandatory parameter is missing.']],
			['count(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "count". Mandatory parameter is missing.']],	// invalid second parameter
			['count(/host/key,0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "count". Invalid second parameter.']],
			['count(/host/key,#0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "count". Invalid second parameter.']],
			['count(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['count(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['count(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, 1M)', [], ['rc' => false, 'error' => 'Incorrect usage of function "count". Invalid second parameter.']],
			['count(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256,)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "str")', [], ['rc' => false, 'error' => 'Incorrect usage of function "count". Invalid third parameter.']],
			['count(/host/key, #256, 10)', [], ['rc' => false, 'error' => 'Incorrect usage of function "count". Invalid third parameter.']],
			['count(/host/key, #256, 10K)', [], ['rc' => false, 'error' => 'Incorrect usage of function "count". Invalid third parameter.']],
			['count(/host/key, #256, "eq")', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "ne")', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "like")', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "bitand")', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "{$MACRO}{$LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "regexp",)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "regexp", 100)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "regexp", 1s)', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "regexp", {$MACRO})', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "regexp", {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['count(/host/key, #256, "regexp",,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "count". Invalid number of parameters.']],

			['find(/host/key)', [], ['rc' => true, 'error' => null]],
			['find(/host/key,)', [], ['rc' => true, 'error' => null]],
			['find(/host/key,0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "find". Invalid second parameter.']],
			['find(/host/key,#0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "find". Invalid second parameter.']],
			['find(/host/key,1)', [], ['rc' => true, 'error' => null]],
			['find(/host/key,#1)', [], ['rc' => true, 'error' => null]],
			['find(/host/key,1s)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, 1m)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, 1M)', [], ['rc' => false, 'error' => 'Incorrect usage of function "find". Invalid second parameter.']],
			['find(/host/key, 1m:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #3:now/h-1h)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #5:now/M)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #2147483647)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, 2147483647)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256,)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "str")', [], ['rc' => false, 'error' => 'Incorrect usage of function "find". Invalid third parameter.']],
			['find(/host/key, #256, 10)', [], ['rc' => false, 'error' => 'Incorrect usage of function "find". Invalid third parameter.']],
			['find(/host/key, #256, 10K)', [], ['rc' => false, 'error' => 'Incorrect usage of function "find". Invalid third parameter.']],
			['find(/host/key, #256, "eq")', [], ['rc' => false, 'error' => 'Incorrect usage of function "find". Invalid third parameter.']],
			['find(/host/key, #256, "ne")', [], ['rc' => false, 'error' => 'Incorrect usage of function "find". Invalid third parameter.']],
			['find(/host/key, #256, "like")', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "bitand")', [], ['rc' => false, 'error' => 'Incorrect usage of function "find". Invalid third parameter.']],
			['find(/host/key, #256, "{$MACRO}{$LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "regexp",)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "regexp", 100)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "regexp", 1s)', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "regexp", {$MACRO})', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "regexp", {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['find(/host/key, #256, "regexp",,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "find". Invalid number of parameters.']],

			['forecast(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "forecast". Mandatory parameter is missing.']],
			['forecast(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "forecast". Mandatory parameter is missing.']],
			['forecast(/host/key,#1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "forecast". Mandatory parameter is missing.']],
			['forecast(/host/key,0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "forecast". Invalid second parameter.']],
			['forecast(/host/key,#0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "forecast". Invalid second parameter.']],
			['forecast(/host/key,1,5s)', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key,#1,10h)', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key,1s,-7d)', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key,1s, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key,1s, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key,1s, "{$MACRO}{$LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, 1m,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "forecast". Mandatory parameter is missing.']],	// invalid third parameter
			['forecast(/host/key, 1M,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "forecast". Invalid second parameter.']],
			['forecast(/host/key, 1m:now/h-1h, 1d)', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #3:now/h-1h, 1m)', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #5:now/M, 1w)', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "linear")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "polynomial3")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "{$M}")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, {$M})', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "foo")', [], ['rc' => false, 'error' => 'Incorrect usage of function "forecast". Invalid fourth parameter.']],
			['forecast(/host/key, #256, 30d, 25d)', [], ['rc' => false, 'error' => 'Incorrect usage of function "forecast". Invalid fourth parameter.']],
			['forecast(/host/key, #256, 30d, "exponential", "delta")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "exponential", "avg")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "exponential", "bar")', [], ['rc' => false, 'error' => 'Incorrect usage of function "forecast". Invalid fifth parameter.']],
			['forecast(/host/key, #256, 30d, "exponential", "{#M}")', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "exponential", {#M})', [], ['rc' => true, 'error' => null]],
			['forecast(/host/key, #256, 30d, "exponential", "min",)', [], ['rc' => false, 'error' => 'Incorrect usage of function "forecast". Invalid number of parameters.']],

			['timeleft(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "timeleft". Mandatory parameter is missing.']],
			['timeleft(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "timeleft". Mandatory parameter is missing.']],	// invalid second parameter
			['timeleft(/host/key,#1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "timeleft". Mandatory parameter is missing.']],
			['timeleft(/host/key,#1,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "timeleft". Mandatory parameter is missing.']],	// invalid third parameter
			['timeleft(/host/key,0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "timeleft". Invalid second parameter.']],
			['timeleft(/host/key,#0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "timeleft". Invalid second parameter.']],
			['timeleft(/host/key,1,5s)', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key,#1,10h)', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key,1s,-7d)', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key,1s, "abc")', [], ['rc' => false, 'error' => 'Incorrect usage of function "timeleft". Invalid third parameter.']],
			['timeleft(/host/key,1s, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key,1s, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key,1s, "{$MACRO}{$LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, 1m:now/h-1h, 1d)', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #3:now/h-1h, 1m)', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #5:now/M, 1w)', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #256, 30d, "linear")', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #256, 30d, "polynomial3")', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #256, 30d, "{$M}")', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #256, 30d, {$M})', [], ['rc' => true, 'error' => null]],
			['timeleft(/host/key, #256, 30d, "foo")', [], ['rc' => false, 'error' => 'Incorrect usage of function "timeleft". Invalid fourth parameter.']],
			['timeleft(/host/key, #256, 30d, 25d)', [], ['rc' => false, 'error' => 'Incorrect usage of function "timeleft". Invalid fourth parameter.']],
			['timeleft(/host/key, #256, 30d, "exponential",)', [], ['rc' => false, 'error' => 'Incorrect usage of function "timeleft". Invalid number of parameters.']],

			['percentile(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Mandatory parameter is missing.']],
			['percentile(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Mandatory parameter is missing.']],	// invalid second parameter
			['percentile(/host/key, #1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Mandatory parameter is missing.']],
			['percentile(/host/key, #1,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Mandatory parameter is missing.']],	// invalid third parameter
			['percentile(/host/key, 0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Invalid second parameter.']],
			['percentile(/host/key, #0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Invalid second parameter.']],
			['percentile(/host/key, 1h:now/h-1h, "abc")', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Invalid third parameter.']],
			['percentile(/host/key, 1h:now/h-1h, 5s)', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Invalid third parameter.']],
			['percentile(/host/key, 1h:now/h-1h, 1m)', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Invalid third parameter.']],
			['percentile(/host/key, 1h:now/h-1h, -1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Invalid third parameter.']],
			['percentile(/host/key, 1h:now/h-1h, 101)', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Invalid third parameter.']],
			['percentile(/host/key, 1h, 0.12345)', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Invalid third parameter.']],
			['percentile(/host/key, 1, 0)', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, 1h, 0.1234)', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, 1h, 99.9999)', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, #1, 100)', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, 1s, "abc")', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Invalid third parameter.']],
			['percentile(/host/key, 1s, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, 1s, {$LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, 1s, "{$MACRO}{$LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['percentile(/host/key, #256, 5,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "percentile". Invalid number of parameters.']],

			['fuzzytime(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "fuzzytime". Mandatory parameter is missing.']],
			['fuzzytime(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "fuzzytime". Mandatory parameter is missing.']],	// invalid second parameter
			['fuzzytime(/host/key, 0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "fuzzytime". Invalid second parameter.']],
			['fuzzytime(/host/key, #0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "fuzzytime". Invalid second parameter.']],
			['fuzzytime(/host/key, #1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "fuzzytime". Invalid second parameter.']],
			['fuzzytime(/host/key, 1)', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, 1h)', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, "{$MACRO}{#LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, "1h")', [], ['rc' => true, 'error' => null]],
			['fuzzytime(/host/key, 1h,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "fuzzytime". Invalid number of parameters.']],

			['nodata(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "nodata". Mandatory parameter is missing.']],
			['nodata(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "nodata". Mandatory parameter is missing.']],	// invalid second parameter
			['nodata(/host/key, 0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "nodata". Invalid second parameter.']],
			['nodata(/host/key, #0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "nodata". Invalid second parameter.']],
			['nodata(/host/key, #1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "nodata". Invalid second parameter.']],
			['nodata(/host/key, 1)', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h)', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, "{$MACRO}{#LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, "1h")', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h,)', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h,)', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h, "strict")', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h, "{$MACRO}{#LLDMACRO}")', [], ['rc' => true, 'error' => null]],
			['nodata(/host/key, 1h, "foor")', [], ['rc' => false, 'error' => 'Incorrect usage of function "nodata". Invalid third parameter.']],
			['nodata(/host/key, 1h, "strict",)', [], ['rc' => false, 'error' => 'Incorrect usage of function "nodata". Invalid number of parameters.']],

			['trendavg(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendavg". Mandatory parameter is missing.']],
			['trendavg(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendavg". Mandatory parameter is missing.']],	// invalid second parameter
			['trendavg(/host/key, 0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendavg". Invalid second parameter.']],
			['trendavg(/host/key, #0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendavg". Invalid second parameter.']],
			['trendavg(/host/key, #1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendavg". Invalid second parameter.']],
			['trendavg(/host/key, 1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendavg". Invalid second parameter.']],
			['trendavg(/host/key, 1h)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendavg". Invalid second parameter.']],
			['trendavg(/host/key, 1h:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, 1d:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, 1y:now/M-1h)', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, {$PERIOD}:{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, {$PERIOD}:now-{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['trendavg(/host/key, 1y:now/y,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendavg". Invalid number of parameters.']],

			['trendcount(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendcount". Mandatory parameter is missing.']],
			['trendcount(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendcount". Mandatory parameter is missing.']],	// invalid second parameter
			['trendcount(/host/key, 0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendcount". Invalid second parameter.']],
			['trendcount(/host/key, #0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendcount". Invalid second parameter.']],
			['trendcount(/host/key, #1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendcount". Invalid second parameter.']],
			['trendcount(/host/key, 1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendcount". Invalid second parameter.']],
			['trendcount(/host/key, 1h)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendcount". Invalid second parameter.']],
			['trendcount(/host/key, 1h:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, 1d:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, 1y:now/M-1h)', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, {$PERIOD}:{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, {$PERIOD}:now-{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['trendcount(/host/key, 1y:now/y,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendcount". Invalid number of parameters.']],

			['trendmax(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmax". Mandatory parameter is missing.']],
			['trendmax(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmax". Mandatory parameter is missing.']],	// invalid second parameter
			['trendmax(/host/key, 0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmax". Invalid second parameter.']],
			['trendmax(/host/key, #0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmax". Invalid second parameter.']],
			['trendmax(/host/key, #1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmax". Invalid second parameter.']],
			['trendmax(/host/key, 1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmax". Invalid second parameter.']],
			['trendmax(/host/key, 1h)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmax". Invalid second parameter.']],
			['trendmax(/host/key, 1h:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, 1d:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, 1y:now/M-1h)', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, {$PERIOD}:{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, {$PERIOD}:now-{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['trendmax(/host/key, 1y:now/y,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmax". Invalid number of parameters.']],

			['trendmin(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmin". Mandatory parameter is missing.']],
			['trendmin(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmin". Mandatory parameter is missing.']],	// invalid second parameter
			['trendmin(/host/key, 0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmin". Invalid second parameter.']],
			['trendmin(/host/key, #0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmin". Invalid second parameter.']],
			['trendmin(/host/key, #1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmin". Invalid second parameter.']],
			['trendmin(/host/key, 1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmin". Invalid second parameter.']],
			['trendmin(/host/key, 1h)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmin". Invalid second parameter.']],
			['trendmin(/host/key, 1h:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, 1d:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, 1y:now/M-1h)', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, {$PERIOD}:{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, {$PERIOD}:now-{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['trendmin(/host/key, 1y:now/y,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendmin". Invalid number of parameters.']],

			['trendsum(/host/key)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendsum". Mandatory parameter is missing.']],
			['trendsum(/host/key,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendsum". Mandatory parameter is missing.']],	// invalid second parameter
			['trendsum(/host/key, 0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendsum". Invalid second parameter.']],
			['trendsum(/host/key, #0)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendsum". Invalid second parameter.']],
			['trendsum(/host/key, #1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendsum". Invalid second parameter.']],
			['trendsum(/host/key, 1)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendsum". Invalid second parameter.']],
			['trendsum(/host/key, 1h)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendsum". Invalid second parameter.']],
			['trendsum(/host/key, 1h:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, 1d:now-1h)', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, 1y:now/M-1h)', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, {$PERIOD}:{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, {$PERIOD}:now-{$TIMESHIFT})', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, {$MACRO})', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, {#LLDMACRO})', [], ['rc' => true, 'error' => null]],
			['trendsum(/host/key, 1y:now/y,)', [], ['rc' => false, 'error' => 'Incorrect usage of function "trendsum". Invalid number of parameters.']],

			['avg_foreach(/host/key)', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "avg_foreach". Mandatory parameter is missing.']],
			['avg_foreach(/host/key,)', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "avg_foreach". Mandatory parameter is missing.']],	// invalid second parameter
			['avg_foreach(/host/key, 0)', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "avg_foreach". Invalid second parameter.']],
			['avg_foreach(/host/key, #0)', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "avg_foreach". Invalid second parameter.']],
			['avg_foreach(/host/key, #1)', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "avg_foreach". Invalid second parameter.']],
			['avg_foreach(/host/key, 1)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['avg_foreach(/host/key, 1h)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['avg_foreach(/host/key, 1d)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['avg_foreach(/host/key, 1d:now/d)', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "avg_foreach". Invalid second parameter.']],
			['avg_foreach(/host/key, {$PERIOD}:{$TIMESHIFT})', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "avg_foreach". Invalid second parameter.']],
			['avg_foreach(/host/key, {$PERIOD}:now-{$TIMESHIFT})', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "avg_foreach". Invalid second parameter.']],
			['avg_foreach(/host/key, {$MACRO})', ['calculated' => true], ['rc' => true, 'error' => null]],
			['avg_foreach(/host/key, {#LLDMACRO})', ['calculated' => true], ['rc' => true, 'error' => null]],
			['avg_foreach(/host/key, 1d,)', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "avg_foreach". Invalid number of parameters.']],

			['last_foreach(/host/key)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key,)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key, 0)', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "last_foreach". Invalid second parameter.']],
			['last_foreach(/host/key, #0)', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "last_foreach". Invalid second parameter.']],
			['last_foreach(/host/key, #1)', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "last_foreach". Invalid second parameter.']],
			['last_foreach(/host/key, 1)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key, 1h)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key, 1d)', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key, 1d:now/d)', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "last_foreach". Invalid second parameter.']],
			['last_foreach(/host/key, {$PERIOD}:{$TIMESHIFT})', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "avg_foreach". Invalid second parameter.']],
			['last_foreach(/host/key, {$PERIOD}:now-{$TIMESHIFT})', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "avg_foreach". Invalid second parameter.']],
			['last_foreach(/host/key, {$MACRO})', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key, {#LLDMACRO})', ['calculated' => true], ['rc' => true, 'error' => null]],
			['last_foreach(/host/key, 1d,)', ['calculated' => true], ['rc' => false, 'error' => 'Incorrect usage of function "last_foreach". Invalid number of parameters.']]
		];
	}

	/**
	 * @dataProvider dataProvider
	 */
	public function testHistFunctionValidator(string $source, array $options, array $expected) {
		$expression_parser = new CExpressionParser([
			'lldmacros' => true
		] + $options);
		$hist_function_validator = new CHistFunctionValidator([
			'parameters' => (new CHistFunctionData($options))->getParameters()
		]);
		$expression_parser->parse($source);
		$tokens = $expression_parser->getResult()->getTokens();

		$this->assertSame(CExpressionParserResult::TOKEN_TYPE_HIST_FUNCTION, $tokens[0]['type']);
		$this->assertSame($expected, [
			'rc' => $hist_function_validator->validate($tokens[0]),
			'error' => $hist_function_validator->getError()
		]);
	}
}
