ALTER TABLE ONLY escalations ALTER actionid DROP DEFAULT;
ALTER TABLE ONLY escalations ALTER triggerid DROP DEFAULT;
ALTER TABLE ONLY escalations ALTER eventid DROP DEFAULT;
ALTER TABLE ONLY escalations ALTER r_eventid DROP DEFAULT;
ALTER TABLE ONLY escalations ALTER r_eventid DROP NOT NULL;
