CREATE USER IF NOT EXISTS '${MYSQL_DB_USER}'@'%' IDENTIFIED BY '${MYSQL_DB_PASSWORD}';
GRANT REPLICATION CLIENT, PROCESS, SHOW DATABASES, SHOW VIEW ON *.* TO '${MYSQL_DB_USER}'@'%';
CHANGE MASTER TO
	MASTER_HOST='mysql-8.3-master',
	MASTER_USER='${MYSQL_DB_USER}',
	MASTER_PASSWORD='${MYSQL_DB_PASSWORD}',
	MASTER_PORT=${MYSQL_MASTER_PORT};
