ALTER TABLE triggers ALTER COLUMN triggerid SET WITH DEFAULT NULL;
REORG TABLE triggers;
ALTER TABLE triggers ALTER COLUMN templateid SET WITH DEFAULT NULL;
REORG TABLE triggers;
ALTER TABLE triggers ALTER COLUMN templateid DROP NOT NULL;
REORG TABLE triggers;
UPDATE triggers SET templateid=NULL WHERE templateid=0;
UPDATE triggers SET templateid=NULL WHERE NOT templateid IS NULL AND NOT templateid IN (SELECT triggerid FROM triggers);
ALTER TABLE triggers ADD CONSTRAINT c_triggers_1 FOREIGN KEY (templateid) REFERENCES triggers (triggerid) ON DELETE CASCADE;
REORG TABLE triggers;
