ALTER TABLE graphs
	MODIFY yaxismin DOUBLE PRECISION DEFAULT '0' NOT NULL,
	MODIFY yaxismax DOUBLE PRECISION DEFAULT '100' NOT NULL,
	MODIFY percent_left DOUBLE PRECISION DEFAULT '0' NOT NULL,
	MODIFY percent_right DOUBLE PRECISION DEFAULT '0' NOT NULL;
ALTER TABLE trends
	MODIFY value_min DOUBLE PRECISION DEFAULT '0.0000' NOT NULL,
	MODIFY value_avg DOUBLE PRECISION DEFAULT '0.0000' NOT NULL,
	MODIFY value_max DOUBLE PRECISION DEFAULT '0.0000' NOT NULL;
ALTER TABLE services MODIFY goodsla DOUBLE PRECISION DEFAULT '99.9' NOT NULL;
ALTER TABLE history MODIFY value DOUBLE PRECISION DEFAULT '0.0000' NOT NULL;
