UserParameter=percona.ping[*], mysqladmin -h"$1" -P"$2" ping
UserParameter=percona.get_status_variables[*], mysql -h"$1" -P"$2" -sNX -e "show global status"
UserParameter=percona.version[*], mysqladmin -s -h"$1" -P"$2" version
UserParameter=percona.db.discovery[*], mysql -h"$1" -P"$2" -sN -e "show databases"
UserParameter=percona.dbsize[*], mysql -h"$1" -P"$2" -sN -e "SELECT COALESCE(SUM(DATA_LENGTH + INDEX_LENGTH),0) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='$3'"
UserParameter=percona.replication.discovery[*], mysql -h"$1" -P"$2" -sNX -e "show replica status" 2>/dev/null || mysql -h"$1" -P"$2" -sNX -e "show slave status"
UserParameter=percona.table.discovery[*], mysql -h"$1" -P"$2" -sN -e "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='$3'"
UserParameter=percona.tabledata[*], mysql -h"$1" -P"$2" -sNX -e "SELECT TABLE_NAME, DATA_LENGTH, INDEX_LENGTH, DATA_FREE, TABLE_ROWS FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='$3' AND TABLE_NAME='$4'"
UserParameter=percona.slave_status[*], mysql -h"$1" -P"$2" -sNX -e "show $3 status"
UserParameter=percona.get_global_variables[*], mysql -h"$1" -P"$2" -sNX -e "SHOW GLOBAL VARIABLES WHERE Variable_name IN ('thread_handling','thread_pool_max_threads','thread_pool_stall_limit')"
