ALTER TABLE ONLY graphs
	ALTER COLUMN yaxismin TYPE DOUBLE PRECISION,
	ALTER COLUMN yaxismax TYPE DOUBLE PRECISION,
	ALTER COLUMN percent_left TYPE DOUBLE PRECISION,
	ALTER COLUMN percent_right TYPE DOUBLE PRECISION;
ALTER TABLE ONLY trends
	ALTER COLUMN value_min TYPE DOUBLE PRECISION,
	ALTER COLUMN value_avg TYPE DOUBLE PRECISION,
	ALTER COLUMN value_max TYPE DOUBLE PRECISION;
ALTER TABLE ONLY services ALTER COLUMN goodsla TYPE DOUBLE PRECISION;
ALTER TABLE ONLY history ALTER COLUMN value TYPE DOUBLE PRECISION;
