ALTER TABLE ONLY trends
	ALTER COLUMN value_min TYPE DOUBLE PRECISION,
	ALTER COLUMN value_avg TYPE DOUBLE PRECISION,
	ALTER COLUMN value_max TYPE DOUBLE PRECISION;
ALTER TABLE ONLY history ALTER COLUMN value TYPE DOUBLE PRECISION;
