ALTER TABLE history_log ALTER COLUMN id SET WITH DEFAULT NULL;
ALTER TABLE history_log ALTER COLUMN itemid SET WITH DEFAULT NULL;
ALTER TABLE history_log ADD ns integer SET WITH DEFAULT '0' NOT NULL;
