.TH ZABBIX "1" "October 2009" "ZABBIX Get" "ZABBIX Monitoring server"
.SH NAME
zabbix_get \- request information from a Zabbix agent
.SH DESCRIPTION
zabbix_get is a command-line tool that communicates with a Zabbix agent and
retrieves requested information. The utility is usually used for
troubleshooting of Zabbix agents.
.SH USAGE
zabbix_get [\-hV] \fB\-s\fR<host name or IP> [\-p<port>] [\-I<ip address>] \fB\-k\fR<key>
.SH OPTIONS
.TP
\fB\-s\fR \fB\-\-host\fR <host name or IP>
Specify host name or IP address of a host.
.TP
\fB\-p\fR \fB\-\-port\fR <port number>
Specify port number of agent running on the host. Default is 10050.
.TP
\fB\-I\fR \fB\-\-source\-address\fR <ip address>
Specify source IP address
.TP
\fB\-k\fR \fB\-\-key\fR <key of metric>
Specify metric name (key) we want to retrieve.
.TP
\fB\-h\fR \fB\-\-help\fR
Give this help
.TP
\fB\-V\fR \fB\-\-version\fR
Display version number
.PP
Example: zabbix_get \fB\-s127\fR.0.0.1 \fB\-p10050\fR \fB\-k\fR"system.cpu.load[all,avg1]"
.SH NOTES
This man page was written by Christoph Haas <haas@debian.org> for the Debian
GNU/Linux distribution but may be freely used by anyone.
