.TH ZABBIX "8" "October 2009" "ZABBIX Server (daemon)" "ZABBIX Monitoring server"
.SH NAME
zabbix_server \- main process to monitor remote systems
.SH DESCRIPTION
The Zabbix server is the central component of Zabbix that is deemed the actual
"monitoring station". It talks to proxies and agents to gather system
information and evaluates triggers to alert users in case of problems.
It depends on a database backend like MySQL or PostgreSQL.
.SH USAGE
zabbix_server [\-hV] [\-c <file>] [\-n <nodeid>]
.SH OPTIONS
.TP
\fB\-c\fR \fB\-\-config\fR <file>
Specify configuration file
.TP
\fB\-h\fR \fB\-\-help\fR
give this help
.HP
\fB\-n\fR \fB\-\-new\-nodeid\fR <nodeid> convert database data to new nodeid
.TP
\fB\-V\fR \fB\-\-version\fR
display version number
.SH NOTES
This man page was written by Christoph Haas <haas@debian.org> for the Debian
GNU/Linux distribution but may be freely used by anyone.

