.TH ZABBIX_PROXY 8 "5 July 2011"
.SH NAME
zabbix_proxy \- Zabbix Proxy daemon.
.SH SYNOPSIS
.B zabbix_proxy [-hV] [-c \fIconfig-file\fR] [-R \fIoption\fR]
.SH DESCRIPTION
.B zabbix_proxy
is a Proxy daemon used for remote data collection.
.SS Options
.IP "-c, --config config-file"
Use the alternate \fIconfig-file\fR instead of \fI/etc/zabbix/zabbix_proxy.conf\fR.
.IP "-R, --runtime-control option"
Perform administrative functions according to \fIoption\fR.
.IP "-h, --help"
Display this help and exit.
.IP "-V, --version"
Output version information and exit.
.SS Runtime control options
.TP
\fBconfig_cache_reload\fR
Reload configuration cache.
.SH FILES
.TP
.I /etc/zabbix/zabbix_proxy.conf
Default location of Zabbix Proxy configuration file.
.SH "SEE ALSO"
.BR zabbix_agentd (8),
.BR zabbix_get (8),
.BR zabbix_sender (8),
.BR zabbix_server (8)
.SH AUTHOR
Alexei Vladishev <alex@zabbix.com>
