UserParameter=mariadb.ping[*], mariadb-admin -h"$1" -P"$2" ping
UserParameter=mariadb.get_status_variables[*], mariadb -h"$1" -P"$2" -sNX -e "show global status"
UserParameter=mariadb.version[*], mariadb-admin -s -h"$1" -P"$2" version
UserParameter=mariadb.db.discovery[*], mariadb -h"$1" -P"$2" -sN -e "show databases"
UserParameter=mariadb.dbsize[*], mariadb -h"$1" -P"$2" -sN -e "SELECT COALESCE(SUM(DATA_LENGTH + INDEX_LENGTH),0) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='$3'"
UserParameter=mariadb.replication.discovery[*], mariadb -h"$1" -P"$2" -sNX -e "show replica status" 2>/dev/null || mariadb -h"$1" -P"$2" -sNX -e "show slave status"
UserParameter=mariadb.table.discovery[*], mariadb -h"$1" -P"$2" -sN -e "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='$3'"
UserParameter=mariadb.tabledata[*], mariadb -h"$1" -P"$2" -sNX -e "SELECT TABLE_NAME, DATA_LENGTH, INDEX_LENGTH, DATA_FREE, TABLE_ROWS FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='$3' AND TABLE_NAME='$4'"
UserParameter=mariadb.slave_status[*], mariadb -h"$1" -P"$2" -sNX -e "show $3 status"
