/*
** Copyright (C) 2001-2026 Zabbix SIA
**
** This program is free software: you can redistribute it and/or modify it under the terms of
** the GNU Affero General Public License as published by the Free Software Foundation, version 3.
**
** This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
** without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
** See the GNU Affero General Public License for more details.
**
** You should have received a copy of the GNU Affero General Public License along with this program.
** If not, see <https://www.gnu.org/licenses/>.
**/

#include "cep_manager.h"
#include "cep.h"
#include "cep_task.h"
#include "cep_worker.h"
#include "cep_queue.h"
#include "cep_api.h"
#include "zbx_trigger_constants.h"
#include "zbxalgo.h"
#include "zbx_cep_client.h"
#include "zbx_cep.h"

#include "zbxcommon.h"
#include "zbxdb.h"
#include "zbxipcservice.h"
#include "zbxlog.h"
#include "zbxmw.h"
#include "zbxserialize.h"
#include "zbxsupervisor_client.h"
#include "zbxtimekeeper.h"
#include "zbxself.h"
#include "zbxnix.h"
#include "zbxrtc.h"
#include "zbxprof.h"
#include "zbx_rtc_constants.h"
#include "zbxthreads.h"
#include "zbxtime.h"
#include "zbxcachehistory.h"

#define CEP_WORKERS_MAX		100
#define CEP_WORKERS_DEFAULT	10

typedef enum
{
	CEP_POOL_IDLE,
	CEP_POOL_GROWING,	/* worker thread(s) are being started */
	CEP_POOL_SHRINKING	/* worker thread(s) are being stopped */
}
zbx_cep_pool_state_t;

typedef struct
{
	zbx_uint64_t	eventid;
	zbx_cep_task_t	*task;
}
zbx_cep_blocker_event_t;

typedef struct
{
	zbx_cep_origin_t	origin;
	zbx_cep_task_t		*task;
}
zbx_cep_blocker_object_t;

typedef struct
{
	zbx_mw_manager_t		base;

	zbx_vector_mw_task_ptr_t	commits;		/* tasks ready to be committed */
	int				commit_task_num;	/* number of active commit tasks */

	/* when event tasks is ready to be comitted it blocks other tasks by: */
	/*   eventid - other tasks referring to this specific event           */
	/*   object  - other tasks generated by this object                   */
	zbx_hashset_t			blocker_events;		/* blockers by events */
	zbx_hashset_t			blocker_objects;	/* blockers by objects */
}
zbx_cep_manager_t;

static zbx_hash_t	cep_blocker_object_hash(const void *a)
{
	zbx_cep_blocker_object_t	*object = (zbx_cep_blocker_object_t *)a;

	return cep_origin_hash(&object->origin);
}

static int	cep_blocker_object_compare(const void *a1, const void *a2)
{
	zbx_cep_blocker_object_t	*o1 = (zbx_cep_blocker_object_t *)a1;
	zbx_cep_blocker_object_t	*o2 = (zbx_cep_blocker_object_t *)a2;

	return cep_origin_compare(&o1->origin, &o2->origin);
}

/******************************************************************************
 *                                                                            *
 * Purpose: free CEP manager resources                                        *
 *                                                                            *
 * Parameters: manager - [IN] the CEP manager instance                        *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_free(zbx_cep_manager_t *manager)
{
	zbx_mw_manager_clear(&manager->base);

	/* workers are created after queue, if queue failed there will be no workers to stop/destroy */
	if (NULL != manager->base.queue)
	{
		cep_queue_clear((zbx_cep_queue_t *)manager->base.queue);
		zbx_free(manager->base.queue);

		if (NULL != manager->base.workers)
		{
			for (int i = 0; i < manager->base.workers_max; i++)
				zbx_free(manager->base.workers[i]);

			zbx_free(manager->base.workers);
		}
	}

	zbx_cep_api_release();

	zbx_vector_mw_task_ptr_clear_ext(&manager->commits, cep_task_free);
	zbx_vector_mw_task_ptr_destroy(&manager->commits);

	zbx_hashset_destroy(&manager->blocker_events);
	zbx_hashset_destroy(&manager->blocker_objects);

	zbx_free(manager);
}

/******************************************************************************
 *                                                                            *
 * Purpose: create and initialize CEP manager instance                        *
 *                                                                            *
 * Parameters: workers_num - [IN] initial number of workers                   *
 *             dbpool      - [IN] database connection pool                    *
 *             stats       - [OUT] initialization statistics                  *
 *             error       - [OUT] error message                              *
 *                                                                            *
 * Return value: pointer to the created CEP manager instance or NULL on       *
 *               error                                                        *
 *                                                                            *
 ******************************************************************************/
static zbx_cep_manager_t	*cep_manager_create(const zbx_thread_info_t *info, zbx_dbconn_pool_t *dbpool,
		zbx_cep_init_stats_t *stats, char **error)
{
	zbx_cep_manager_t	*manager;
	int			ret = FAIL;
	zbx_cep_t		*cep;
	zbx_cep_worker_t	**workers;
	zbx_cep_queue_t		*queue;

	manager = (zbx_cep_manager_t *)zbx_calloc(NULL, 1, sizeof(zbx_cep_manager_t));
	workers = (zbx_cep_worker_t **)zbx_calloc(NULL, (size_t)CEP_WORKERS_MAX, sizeof(zbx_cep_worker_t *));

	for (int i = 0; i < CEP_WORKERS_MAX; i++)
		workers[i] = cep_worker_create(dbpool);

	queue = cep_queue_create();

	zbx_hashset_create(&manager->blocker_events, 0, ZBX_DEFAULT_ID_HASH_FUNC, ZBX_DEFAULT_UINT64_COMPARE_FUNC);
	zbx_hashset_create(&manager->blocker_objects, 0, cep_blocker_object_hash, cep_blocker_object_compare);

	zbx_vector_mw_task_ptr_create(&manager->commits);

	manager->commit_task_num = 0;

	if (SUCCEED != zbx_mw_manager_init(&manager->base, info, ZBX_IPC_SERVICE_CEP, ZBX_PROCESS_TYPE_CEP_WORKER,
			(zbx_mw_worker_t **)workers, CEP_WORKERS_MAX, CEP_WORKERS_DEFAULT, cep_worker_entry,
			(zbx_mw_queue_t *)queue, error))
	{
		goto out;
	}

	if (FAIL == cep_api_create(error))
		goto out;

	zbx_cep_api_acquire();

	cep_cache_acquire(&cep);
	cep_init(cep, dbpool, stats);
	cep_dump(cep, "cache initialization");
	cep_cache_release(&cep);

	ret = SUCCEED;
out:
	if (SUCCEED != ret)
	{
		cep_manager_free(manager);
		manager = NULL;
	}

	return manager;
}

/******************************************************************************
 *                                                                            *
 * Purpose: add remote task to CEP manager                                    *
 *                                                                            *
 * Parameters: manager      - [IN]  CEP manager instance                      *
 *             client       - [IN]  IPC client                                *
 *             message      - [IN]  IPC message                               *
 *             response     - [IN]  response buffer                           *
 *             response_len - [IN]  length of the response buffer             *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_add_remote_task(zbx_cep_manager_t *manager, zbx_ipc_client_t **client,
		zbx_ipc_message_t **message, unsigned char *response, zbx_uint32_t response_len)
{
	zbx_mw_task_t	*task;

	task = cep_create_task_remote(*client, *message, response, response_len);

	zbx_mw_queue_lock(manager->base.queue);
	cep_queue_push((zbx_cep_queue_t *)manager->base.queue, task);
	zbx_mw_queue_unlock(manager->base.queue);

	*client = NULL;
	*message = NULL;
}

/******************************************************************************
 *                                                                            *
 * Purpose: add assess trigger events task to CEP manager                     *
 *                                                                            *
 * Parameters: manager - [IN] CEP manager instance                            *
 *             client  - [IN] IPC client handle                               *
 *             message - [IN] IPC message descriptor                          *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_add_assess_trigger_events(zbx_cep_manager_t *manager, zbx_ipc_client_t **client,
	zbx_ipc_message_t **message)
{
	unsigned char*	response;
	int		queries_num;

	queries_num = zbx_cep_peek_event_queries((*message)->data);
	response = (unsigned char*)zbx_malloc(NULL, (size_t)queries_num);

	cep_manager_add_remote_task(manager, client, message, response, (zbx_uint32_t)queries_num);
}

/******************************************************************************
 *                                                                            *
 * Purpose: add new events task to CEP manager                                *
 *                                                                            *
 * Parameters: manager - [IN] CEP manager instance                            *
 *             client  - [IN] IPC client handle                               *
 *             message - [IN] IPC message descriptor                          *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_add_events(zbx_cep_manager_t *manager, zbx_ipc_client_t **client,
		zbx_ipc_message_t **message)
{
	unsigned char*	response = (unsigned char *)zbx_malloc(NULL, sizeof(int));

	cep_manager_add_remote_task(manager, client, message, response, (zbx_uint32_t)sizeof(int));
}

/******************************************************************************
 *                                                                            *
 * Purpose: check trigger dependency status                                   *
 *                                                                            *
 * Parameters: manager - [IN] CEP manager instance                            *
 *             client  - [IN] IPC client handle                               *
 *             message - [IN] IPC message descriptor                          *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_check_trigger_deps(zbx_cep_manager_t *manager, zbx_ipc_client_t **client,
	zbx_ipc_message_t **message)
{
	unsigned char*	response;

	response = (unsigned char*)zbx_malloc(NULL, 1);

	cep_manager_add_remote_task(manager, client, message, response, 1);
}

/******************************************************************************
 *                                                                            *
 * Purpose: get cep statistics                                                *
 *                                                                            *
 * Parameters: manager - [IN/OUT] CEP manager                                 *
 *             client  - [IN/OUT] IPC client requesting the statistics        *
 *             message - [IN/OUT] IPC message from the client                 *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_get_stats(zbx_cep_manager_t *manager, zbx_ipc_client_t **client,
	zbx_ipc_message_t **message)
{
	unsigned char*	response;
	zbx_uint32_t	reponse_len = sizeof(zbx_uint64_t) * 3 + sizeof(int) * 5;

	response = (unsigned char*)zbx_malloc(NULL, reponse_len);

	cep_manager_add_remote_task(manager, client, message, response, reponse_len);
}

/******************************************************************************
 *                                                                            *
 * Purpose: get cep statistics                                                *
 *                                                                            *
 * Parameters: stats  - [IN/OUT] CEP startup statistics                       *
 *             client  - [IN/OUT] IPC client requesting the statistics        *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_get_init_stats(zbx_cep_init_stats_t *stats, zbx_ipc_client_t **client)
{
	unsigned char	response[sizeof(zbx_cep_init_stats_t)], *ptr = response;

	ptr += zbx_serialize_value(ptr, stats->events_num);
	ptr += zbx_serialize_value(ptr, stats->events_time);
	ptr += zbx_serialize_value(ptr, stats->tags_num);
	ptr += zbx_serialize_value(ptr, stats->tags_time);
	ptr += zbx_serialize_value(ptr, stats->suppress_num);
	ptr += zbx_serialize_value(ptr, stats->suppress_time);

	zbx_ipc_client_send(*client, ZBX_CEP_GET_INIT_STATS, response, (zbx_uint32_t)(ptr - response));
}

/******************************************************************************
 *                                                                            *
 * Purpose: sync CEP object runtime state and notify the requesting client    *
 *                                                                            *
 * Parameters: dbpool  - [IN] database connection pool                        *
 *             client  - [IN] requesting IPC client to notify on completion   *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_sync_object_state(zbx_dbconn_pool_t *dbpool, zbx_ipc_client_t **client)
{
	zbx_cep_t	*cep;
	zbx_dbconn_t	*db;

	db = zbx_dbconn_pool_acquire_connection(dbpool);

	cep_cache_acquire(&cep);
	cep_sync_object_state(cep, db);
	cep_cache_release(&cep);

	zbx_dbconn_pool_release_connection(dbpool, db);

	zbx_ipc_client_send(*client, ZBX_CEP_SYNC_OBJECT_STATE, NULL, 0);
}

/******************************************************************************
 *                                                                            *
 * Purpose: send remote CEP task response if available                        *
 *                                                                            *
 * Parameters: task - [IN] remote CEP task descriptor                         *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_flush_remote_task(zbx_cep_task_remote_t *task)
{
	if (NULL != task->response && SUCCEED == zbx_ipc_client_connected(task->client))
		zbx_ipc_client_send(task->client, task->message->code, task->response, task->response_len);
}

/******************************************************************************
 *                                                                            *
 * Purpose: block task execution if specified event is being committed        *
 *                                                                            *
 * Parameters: manager - [IN] CEP manager                                     *
 *             task    - [IN] task to block                                   *
 *             eventid - [IN] identifier of event being committed             *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_block_task_on_event(zbx_cep_manager_t *manager, zbx_cep_task_t *task,
		zbx_uint64_t eventid)
{
	zbx_cep_blocker_event_t	*blocker;

	if (NULL == (blocker = (zbx_cep_blocker_event_t *)zbx_hashset_search(&manager->blocker_events, &eventid)))
		return;

	task->blockers++;
	zbx_vector_mw_task_ptr_append(&blocker->task->blocked, &task->base);
}

/******************************************************************************
 *                                                                            *
 * Purpose: block task execution if events generated by specified object are  *
 *          being committed                                                   *
 *                                                                            *
 * Parameters: manager - [IN] CEP manager                                     *
 *             task    - [IN] task to block                                   *
 *             origin  - [IN] object generating events being committed        *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_block_task_on_object(zbx_cep_manager_t *manager, zbx_cep_task_t *task,
		zbx_cep_origin_t *origin)
{
	zbx_cep_blocker_object_t	*blocker;

	if (NULL == (blocker = (zbx_cep_blocker_object_t *)zbx_hashset_search(&manager->blocker_objects, origin)))
		return;

	task->blockers++;
	zbx_vector_mw_task_ptr_append(&blocker->task->blocked, &task->base);
}

/******************************************************************************
 *                                                                            *
 * Purpose: block task on events and objects it depends on, registering it    *
 *          as a blocker for related tasks                                    *
 *                                                                            *
 * Parameters: manager - [IN] CEP manager                                     *
 *             task    - [IN] event task to block                             *
 *                                                                            *
 * Return value: SUCCEED - task was processed                                 *
 *               FAIL - task has no event operation                           *
 *                                                                            *
 ******************************************************************************/
static int	cep_manager_block_task_event(zbx_cep_manager_t *manager, zbx_cep_task_event_t *task)
{
	if (CEP_EVENT_NONE == task->event_op)
		return FAIL;

	if (0 != task->creator.c_eventid)
		cep_manager_block_task_on_event(manager, &task->base, task->creator.c_eventid);

	for (int i = 0; i < task->eventids.values_num; i++)
		cep_manager_block_task_on_event(manager,  &task->base, task->eventids.values[i]);

	zbx_cep_origin_t	origin = {
		.source = task->db_event->source,
		.object = task->db_event->object,
		.objectid = task->db_event->objectid
	};

	cep_manager_block_task_on_object(manager, &task->base, &origin);

	if (CEP_EVENT_OPEN == task->event_op)
	{
		zbx_cep_blocker_event_t	be_local = {
				.eventid = task->db_event->eventid,
				.task = (zbx_cep_task_t *)task
		};

		zbx_hashset_insert(&manager->blocker_events, &be_local, sizeof(be_local));
	}

	if (CEP_EVENT_OPEN == task->event_op || CEP_EVENT_CLOSE == task->event_op)
	{
		zbx_cep_blocker_object_t	*bo, bo_local = {
				.origin = {
					.source = task->db_event->source,
					.object = task->db_event->object,
					.objectid = task->db_event->objectid
				}
		};

		bo = (zbx_cep_blocker_object_t *)zbx_hashset_insert(&manager->blocker_objects, &bo_local,
				sizeof(bo_local));
		bo->task = &task->base;
	}

	return SUCCEED;
}

/******************************************************************************
 *                                                                            *
 * Purpose: deregister blocker event task                                     *
 *                                                                            *
 * Parameters: manager - [IN] CEP manager                                     *
 *             task    - [IN] event task to deregister                        *
 *                                                                            *
 * Comments: Object blocker is removed only if it is still registered for     *
 *           this task, as another task may have taken over the block.        *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_deregister_blocking_task_event(zbx_cep_manager_t *manager, zbx_cep_task_event_t *task)
{
	if (CEP_EVENT_OPEN == task->event_op)
		zbx_hashset_remove(&manager->blocker_events, &task->db_event->eventid);

	if (CEP_EVENT_OPEN == task->event_op || CEP_EVENT_CLOSE == task->event_op)
	{
		zbx_cep_blocker_object_t	*bo;
		zbx_cep_origin_t		origin = {
				.source = task->db_event->source,
				.object = task->db_event->object,
				.objectid = task->db_event->objectid
		};

		if (NULL != (bo = (zbx_cep_blocker_object_t *)zbx_hashset_search(&manager->blocker_objects, &origin)))
		{
			if (bo->task == &task->base)
				zbx_hashset_remove_direct(&manager->blocker_objects, bo);
		}
	}
}

/******************************************************************************
 *                                                                            *
 * Purpose: deregister blocker task                                           *
 *                                                                            *
 * Parameters: manager - [IN] task    - [IN] task to deregister               *
 *                                                                            *
 * Return value: SUCCEED - task type was recognized and deregistered          *
 *               FAIL - task type is not supported for deregistration         *
 *                                                                            *
 ******************************************************************************/
static int	cep_manager_deregister_blocking_task(zbx_cep_manager_t *manager, zbx_mw_task_t *task)
{
	switch (task->type)
	{
		case CEP_TASK_EVENT:
			cep_manager_deregister_blocking_task_event(manager, (zbx_cep_task_event_t *)task);
			return SUCCEED;
	}

	return FAIL;
}

/******************************************************************************
 *                                                                            *
 * Purpose: deregister committed tasks as blockers and queue tasks they were  *
 *          blocking for commit once their last blocker is cleared            *
 *                                                                            *
 * Parameters: manager - [IN] CEP manager                                     *
 *             task    - [IN] commit task containing committed tasks          *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_unblock_commit_task(zbx_cep_manager_t *manager, zbx_cep_task_commit_t *task)
{
	for (int i = 0; i < task->tasks.values_num; i++)
	{
		zbx_cep_task_t *committed = (zbx_cep_task_t *)task->tasks.values[i];

		cep_manager_deregister_blocking_task(manager, &committed->base);

		for (int j = 0; j < committed->blocked.values_num; j++)
		{
			zbx_cep_task_t	*blocked = (zbx_cep_task_t *)committed->blocked.values[j];

			if (0 == --blocked->blockers)
				zbx_vector_mw_task_ptr_append(&manager->commits, &blocked->base);
		}
	}
}

/******************************************************************************
 *                                                                            *
 * Purpose: process task for commit, blocking it on its dependencies if       *
 *          needed, and queue it for commit once unblocked                    *
 *                                                                            *
 * Parameters: manager - [IN] CEP manager                                     *
 *             task    - [IN] task to commit                                  *
 *                                                                            *
 * Return value: SUCCEED - task was queued for commit or blocked pending      *
 *                         dependencies                                       *
 *               FAIL - task was not queued, either because it is a remote    *
 *                      or commit task, or event blocking failed              *
 *                                                                            *
 ******************************************************************************/
static int	cep_manager_commit_task(zbx_cep_manager_t *manager, zbx_mw_task_t *task)
{
	switch (task->type)
	{
		case CEP_TASK_REMOTE:
			cep_manager_flush_remote_task((zbx_cep_task_remote_t *)task);
			return FAIL;
		case CEP_TASK_EVENT:
			if (SUCCEED != cep_manager_block_task_event(manager, (zbx_cep_task_event_t *)task))
				return FAIL;
			break;
		case CEP_TASK_ADD_TAGS:
			break;
		case CEP_TASK_COMMIT:
			cep_manager_unblock_commit_task(manager, (zbx_cep_task_commit_t *)task);
			manager->commit_task_num--;
			return FAIL;
	}

	if (0 == ((zbx_cep_task_t *)task)->blockers)
		zbx_vector_mw_task_ptr_append(&manager->commits, task);

	return SUCCEED;
}

/******************************************************************************
 *                                                                            *
 * Purpose: process finished CEP tasks and handle commits                     *
 *                                                                            *
 * Parameters: manager - [IN] CEP manager instance                            *
 *             tasks   - [IN] vector of finished CEP tasks                    *
 *                                                                            *
 * Comments: Remote tasks are flushed, event-related tasks with pending       *
 *           operations are queued for commit, and other tasks are freed.     *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_process_finished(zbx_cep_manager_t *manager, zbx_vector_mw_task_ptr_t *tasks)
{
	for (int i = 0; i < tasks->values_num; i++)
	{
		if (SUCCEED != cep_manager_commit_task(manager, tasks->values[i]))
			cep_task_free(tasks->values[i]);
	}

	zbx_vector_mw_task_ptr_clear(tasks);
}

/******************************************************************************
 *                                                                            *
 * Purpose: enqueue commit task for pending CEP operations                    *
 *                                                                            *
 * Parameters: manager - [IN] CEP manager instance                            *
 *                                                                            *
 * Comments: Creates a commit task for all queued commit operations and       *
 *           pushes it to the CEP manager queue.                              *
 *                                                                            *
 ******************************************************************************/
static void	cep_manager_flush_commmits(zbx_cep_manager_t *manager)
{
	zbx_mw_task_t	*task = cep_create_task_commit(&manager->commits);

	zbx_mw_queue_lock(manager->base.queue);
	cep_queue_push((zbx_cep_queue_t *)manager->base.queue, task);
	zbx_mw_queue_unlock(manager->base.queue);

	manager->commit_task_num++;
}

static int	cep_manager_commit_limit(zbx_cep_manager_t *manager, const zbx_thread_cep_manager_args_t *args)
{
	if (1 == manager->base.workers_num)
		return 1;

	if (args->commit_limit > manager->base.workers_num - 1)
		return manager->base.workers_num - 1;

	return args->commit_limit;
}

/******************************************************************************
 *                                                                            *
 * Purpose: CEP manager main thread function                                  *
 *                                                                            *
 * Parameters: args - [IN] thread arguments                                   *
 *                                                                            *
 * Return value: NULL                                                         *
 *                                                                            *
 ******************************************************************************/
void	*zbx_cep_manager_thread(void *args)
{
#define CEP_MANAGER_DELAY_SEC		0
#define CEP_MANAGER_DELAY_NS		5e8
#define CEP_MANAGER_BATCH_LIMIT		1000
#define CEP_MANAGER_FLUSH_TIMEOUT	1.0

	char					*error = NULL;
	zbx_ipc_client_t			*client;
	zbx_ipc_message_t			*message;
	double					time_stat, time_idle = 0, time_flush;
	zbx_supervisor_unit_args_t		*unit_args = (zbx_supervisor_unit_args_t *)args;
	const zbx_thread_info_t			*info = &unit_args->args.info;
	int					server_num = info->server_num,
						process_num = info->process_num;
	unsigned char				process_type = info->process_type;
	const zbx_thread_cep_manager_args_t	*cep_args = (const zbx_thread_cep_manager_args_t *)unit_args->args.args;
	zbx_cep_manager_t			*manager;
	zbx_vector_mw_task_ptr_t		tasks;
	int					shutdown = 0;
	zbx_cep_stats_t				stats = {0};
	zbx_cep_init_stats_t			init_stats;

#define	STAT_INTERVAL	5	/* if a process is busy and does not sleep then update status not faster than */
				/* once in STAT_INTERVAL seconds */


	zbx_supervisor_update_activity("%s starting", unit_args->name);
	zabbix_log(LOG_LEVEL_INFORMATION, "thread started");

	zbx_update_selfmon_counter(info, ZBX_PROCESS_STATE_BUSY);

	zbx_vector_mw_task_ptr_create(&tasks);

	if (NULL == (manager = cep_manager_create(info, unit_args->shared->dbpool, &init_stats, &error)))
	{
		zabbix_log(LOG_LEVEL_CRIT, "cannot initialize CEP manager: %s", error);
		zbx_free(error);
		zbx_exit(EXIT_FAILURE);
	}

	/* initialize statistics */
	time_stat = zbx_time();

	zbx_supervisor_update_activity("%s #%d started", get_process_type_string(process_type), process_num);

	zbx_supervisor_set_process_running(server_num);

	time_flush = zbx_time();

	while (1)
	{
		int		pending_num;
		double		time_start = zbx_time();

		if (STAT_INTERVAL < time_start - time_stat)
		{
			zbx_cep_stats_t	stats_tmp;
			zbx_uint64_t	accessed_num, processed_num, discarded_num;

			cep_stats_collect(&stats_tmp);

			accessed_num = stats_tmp.events_accessed - stats.events_accessed;
			processed_num = stats_tmp.events_processed - stats.events_processed;
			discarded_num = stats_tmp.events_discarded - stats.events_discarded;

			zbx_supervisor_update_activity("%s #%d [assessed:" ZBX_FS_UI64 " processed:" ZBX_FS_UI64
					" discarded:" ZBX_FS_UI64 " events, idle %.1fs, during %.1fs]",
					get_process_type_string(process_type), process_num,
					accessed_num, processed_num, discarded_num,
					time_idle, time_start - time_stat);

			time_stat = time_start;
			time_idle = 0;
			stats = stats_tmp;
		}

		zbx_update_selfmon_counter(info, ZBX_PROCESS_STATE_IDLE);

		(void)zbx_mw_manager_recv(&manager->base, &client, &message);

		zbx_update_selfmon_counter(info, ZBX_PROCESS_STATE_BUSY);

		double	time_now = zbx_time();

		time_idle += time_now - time_start;

		zbx_prof_update(get_process_type_string(process_type), time_now);

		if (NULL != message)
		{
			switch (message->code)
			{
				case ZBX_CEP_ASSESS_TRIGGER_EVENTS:
					cep_manager_add_assess_trigger_events(manager, &client, &message);
					break;
				case ZBX_CEP_CHECK_TRIGGER_DEPS:
					cep_manager_check_trigger_deps(manager, &client, &message);
					break;
				case ZBX_CEP_GET_STATS:
					cep_manager_get_stats(manager, &client, &message);
					break;
				case ZBX_CEP_GET_INIT_STATS:
					cep_manager_get_init_stats(&init_stats, &client);
					break;
				case ZBX_CEP_ADD_EVENTS:
					cep_manager_add_events(manager, &client, &message);
					break;
				case ZBX_CEP_ADD_USER_CLOSE_EVENT:
				case ZBX_CEP_SUPPRESS_EVENTS:
				case ZBX_CEP_UNSUPPRESS_EVENTS:
				case ZBX_CEP_UPDATE_SEVERITIES:
				case ZBX_CEP_ADD_EVENT_TAGS:
				case ZBX_CEP_DELETE_EVENTS:
					cep_manager_add_remote_task(manager, &client, &message, NULL, 0);
					break;
				case ZBX_CEP_SYNC_OBJECT_STATE:
				cep_manager_sync_object_state(unit_args->shared->dbpool, &client);
					break;
				case ZBX_RTC_SHUTDOWN:
					zabbix_log(LOG_LEVEL_DEBUG, "shutdown message received, terminating...");
					shutdown = 1;
					break;
			}

			zbx_ipc_message_free(message);
		}

		if (NULL != client)
			zbx_ipc_client_release(client);

		/* only stop cep when history syncers no longer require it */
		if ((!ZBX_IS_RUNNING() || 1 == shutdown) && 0 == zbx_hc_refcount_peek())
		{
			if (0 == manager->commits.values_num && 0 == manager->blocker_events.num_data &&
					0 == manager->blocker_objects.num_data)
			{
				int	is_empty;

				zbx_mw_queue_lock(manager->base.queue);
				is_empty = cep_queue_is_empty((zbx_cep_queue_t *)manager->base.queue);
				zbx_mw_queue_unlock(manager->base.queue);

				if (SUCCEED == is_empty)
					break;
			}
		}

		zbx_mw_queue_lock(manager->base.queue);
		(void)zbx_mw_queue_drain_completed(manager->base.queue, &tasks);
		pending_num = cep_queue_pending_commits_num((zbx_cep_queue_t *)manager->base.queue);
		zbx_mw_queue_unlock(manager->base.queue);

		if (0 != tasks.values_num)
		{
			int	commits_num = manager->commits.values_num;

			cep_manager_process_finished(manager, &tasks);

			if (0 == commits_num && 0 != manager->commits.values_num)
				time_flush = time_now;
		}

		if (0 != manager->commits.values_num &&
				manager->commit_task_num < cep_manager_commit_limit(manager, cep_args))
		{
			int	commits_num = manager->commits.values_num;

			if ( CEP_MANAGER_BATCH_LIMIT <= commits_num || 0 == pending_num ||
					CEP_MANAGER_FLUSH_TIMEOUT < time_now - time_flush)
			{
				cep_manager_flush_commmits(manager);
			}
		}
	}

	zbx_supervisor_update_activity("%s [terminating]", unit_args->name);

	/* on normal exit the shutdown message already has been processed and no more messages will be sent */
	if (SUCCEED != ZBX_EXIT_STATUS())
		zbx_rtc_unsubscribe_service(cep_args->config_timeout, ZBX_IPC_SERVICE_CEP);

	cep_manager_free(manager);

	zbx_deinit_regexp_env();
	zbx_vector_mw_task_ptr_destroy(&tasks);

	zbx_supervisor_update_activity("%s [terminated]", unit_args->name);
	zbx_free(args);

#undef STAT_INTERVAL

	return NULL;
}
