## Process this file with automake to produce Makefile.in

noinst_LIBRARIES = libzbxcep.a

libzbxcep_a_CFLAGS = \
	$(TLS_CFLAGS)

libzbxcep_a_SOURCES = \
	cep_manager.c \
	cep_manager.h \
	cep_worker.c \
	cep_worker.h \
	cep_queue.c \
	cep_queue.h \
	cep_task.c \
	cep_task.h \
	cep_db.c \
	cep_db.h \
	cep.c \
	cep.h \
	cep_api.c \
	cep_api.h \
	cep_correlation.c \
	cep_correlation.h \
	cep_rule.c \
	cep_rule.h \
	cep_rule_operation.c \
	cep_rule_operation.h \
	cep_window.c \
	cep_window.h \
	cep_event.c \
	cep_event.h \
	cep_js.c \
	cep_js.h

